### ISSUE TITLE
Adaptative solver settings

### ISSUE THREAD

**Issue by oscarfasanchez** [MODFLOW-USGS/modflow6#1001]
**Is your feature request related to a problem? Please describe.**
I'm working with Pest, in monte Carlo realizations, so I got very different models, when I use ATS, transient stress periods improve its convergence, but many models have more problems in the steady iterations, so I need a higher number of outer iterations. I'm struggling with the solver to improve the convergence of many models. if I set a higher number of outer iterations, some models get convergence. but models that use ATS(that already ran successfully before) increase their running time by almost 70%(from 3 to 5 hours for instance). They waste a lot of outer iterations in transient stress periods without success, just to overcome the problem later with ATS as they did before.

**Describe the solution you'd like**
It would be great to use different solver settings for time steps using ATS, or at least allow to use a different number of outer iterations.

**Comment by langevin-usgs** [comment]
This has been added to the requested features list.  Agreed that it would be worthwhile.
