### ISSUE TITLE
EVT doesn't work with SSM.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1005]
**Describe the bug**
This is either a bug or a documentation error.
Including an EVT package in the SSM package can cause MODFLOW to incorrectly issue an error message. The documentation for the SSM package states "Thus, the AUXMIXED option is designed to work with the Evapotranspiration
(EVT) and Recharge (RCH) Packages where water may be withdrawn at a concentration that is less
than the cell concentration." This implies that EVT can be included as a source in the SSM package.

**To Reproduce**
Run the attached model.

**Expected behavior**
Model should continue past attempting to read the SSM package input or else the documentation should state that EVT packages should not be used with SSM.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version 21H2
[SsmBub.zip](https://github.com/MODFLOW-USGS/modflow6/files/9269397/SsmBub.zip)

**Comment by langevin-usgs** [comment]
When I run this with the most recent develop version, I get this error:

```
ERROR REPORT:

  1. Problem with GWF-GWT exchange GWF-GWT_1.  The GWF model must be solved
     by a different IMS than the GWT model. Furthermore, the IMS specified
     for GWF must be listed in mfsim.nam before the IMS for GWT.
```

When I change the order so GWF is solved before GWT, then I do not see the EVT error reported here (thought the model does not converge).  Feel free to reopen if you find there is still an error.
