### ISSUE TITLE
Enable observations of mass flow rates through simple boundaries like WEL, CHD, DRN, GHB, and RIV when GWT is used.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1014]
**Is your feature request related to a problem? Please describe.**
At present, the observation utility allows for observations of fluid flow through boundaries. These can potentially be used in model calibration. However, there isn't a similar ability to report observations of mass flow through the same boundaries when GWT is used. The concentrations can be saved in the budget file but for those to be used in model calibration, it may be necessary to save the budget information for every time step and then to extract just the right information from what could be a very large file.

**Describe the solution you'd like**
I would like for new observation types to be defined for use with GWT that records the mass flow rates through simple boundaries such as WEL, CHD, DRN, GHB, and RIV packages.

**Describe alternatives you've considered**
The only alternative that I can see is to extract the data from the budget file.

**Additional context**
none

**Comment by langevin-usgs** [comment]
Good suggestion.  We need to improve the number of supported OBS types for GWT.  Will try to make this a priority.

**Comment by langevin-usgs** [comment]
Added to feature request list.
