### ISSUE TITLE
Unhelpful error message generated when an input file is missing.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1018]
**Describe the bug**
When an input file is missing. the error message that is generated doesn't give any actionable information such as the name of the missing file.

**To Reproduce**
run the attached model
[CncObs.zip](https://github.com/MODFLOW-USGS/modflow6/files/9396483/CncObs.zip)
The error message is 
ERROR REPORT:

  1.        SPECIFIED FILE STATUS: OLD
  2.        SPECIFIED FILE FORMAT: FORMATTED
  3.        SPECIFIED FILE ACCESS: SEQUENTIAL
  4.        SPECIFIED FILE ACTION: READ
  5.          IOSTAT ERROR NUMBER: 29
  6.   -- STOP EXECUTION (openfile)

**Expected behavior**
The name of the missing file should be included in the error message.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by langevin-usgs** [comment]
Have you tried the nightly-build version?  This should have been fixed already.

**Comment by rbwinst-usgs** [comment]
Sorry. You're right. It was already fixed in the nightly build.

Richard B. Winston
US Geological Survey
Integrated Modeling and Prediction Division
***@***.******@***.***>
https://profile.usgs.gov/rbwinst<http://water.usgs.gov/nrp/gwsoftware/>
703-648-5988
on Wednesdays: 301 474-2762
Fax: 703 648-5274

The following are excellent guides especially for beginning modelers.
Reilly, T.E., 2001, System and boundary conceptualization in ground-water flow simulation:  U.S. Geological Survey Techniques of Water-Resources Investigations, book 3, chap. B8, 30 p.
https://water.usgs.gov/pubs/twri/twri-3_B8/<http://water.usgs.gov/pubs/twri/twri-3_B8/>

Reilly, T.E., and Harbaugh, A.W., 2004 , Guidelines for evaluating ground-water flow models: U.S. Geological Survey Scientific Investigations Report 2004-5038, 30 p.
https://pubs.usgs.gov/sir/2004/5038/

Free books on Groundwater: https://gw-project.org/books/

"Codes only live if somebody loves them." Matt Tonkin, June 2, 2015, MODFLOW and More 2015 Conference Panel Discussion.

"When you started to have that problem, when you couldn't get a solution, you could get help with that. You could not get any help if you had a conceptual screw-up in your understanding of the regional hydrology. If you didn't have a rough idea of what the evapotranspiration was, of what the big streams were doing, and how the stream flow was related to groundwater, there's where you could get into trouble where nobody else could help you." Gordon Bennett in an interview, Feb. 21, 2019.

________________________________
From: langevin-usgs ***@***.***>
Sent: Monday, August 22, 2022 2:08 PM
To: MODFLOW-USGS/modflow6 ***@***.***>
Cc: Winston, Richard B ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [MODFLOW-USGS/modflow6] Unhelpful error message generated when an input file is missing. (Issue #1018)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Have you tried the nightly-build version? This should have been fixed already.
