### ISSUE TITLE
Duplicate observation type name in UZT package.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1025]
**Describe the bug**
In the description of the observation types for the UZT package, there are two observation types that are both named infiltration. I suspect that the correct observation type for the second one should be to-mvr based on its description and how observation types in other packages are named.

**To Reproduce**
Check the observation types for the UZT package in mf6io.pdf. 

**Expected behavior**
Each observation type for a package should be unique within that package.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by rbwinst-usgs** [comment]
Based on an examination of the source code, it appears that the correct observation type for the second one labeled "infiltration" is "rej-inf-to-mvr"

**Comment by langevin-usgs** [comment]
Thanks, @rbwinst-usgs.  We're in the process of reimplementing and testing all the observations for SFT, LKT, MWT, and UZT.  Pull request #1024

**Comment by emorway-usgs** [comment]
I read @rbwinst-usgs issue report and submitted #1026, not seeing @langevin-usgs's response until after submitting.  I can close #1026 if that's best?

**Comment by langevin-usgs** [comment]
No it's fine.  I'll accept your PR and then rebase.
