### ISSUE TITLE
BUDGETCSV not working for UZF package

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#1033]
Hi Chris,

when using the BUDGETCSV option with UZF package, the following error occurs:

ERROR REPORT:
  1. UNKNOWN UZF CELLS OPTION: BUDGETCSV
UNIT ERROR REPORT:
  1. ERROR OCCURRED WHILE READING FILE
     'TEST001E_UZF_3LAY.UZF'

Tested it with: https://github.com/MODFLOW-USGS/modflow6-testmodels/tree/master/mf6/test001e_UZF_3lay
MF6 version: 6.3.0 (Windows 10)

Best regards
Andreas

**Comment by langevin-usgs** [comment]
I just tried the BUDGETCSV option with a UZF package and it seemed to work fine for me.  Can you download and check with our nightly build version located [here](https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases)?  I think we've probably made a fix but it just hasn't been officially released yet.

**Comment by tandreasr** [comment]
Hi Chris,
unfortunately it doesn't work with the nightly build either.
Attached you find the model t0 reproduce the error and the stdout output in ~mon_output.txt
Best regards
Andreas

[__model.zip](https://github.com/MODFLOW-USGS/modflow6/files/9539700/__model.zip)
[~mon_output.txt](https://github.com/MODFLOW-USGS/modflow6/files/9539701/mon_output.txt)

**Comment by langevin-usgs** [comment]
@tandreasr, I apologize.  There was a bug in setting this option that would cause it to fail intermittently.  I had tested it when you first reported the issue and it worked fine for me, but after a closer look there was a problem.  I submitted a fix this morning, and if all goes well, it should be available tonight on the nightly build.  Thanks for reporting!
