### ISSUE TITLE
Issues with WITHDRAWAL in LAK and LKT 

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#1043]
**Describe the bug**
When withdrawal is specified in the LAK package stress period data, it is not reported correctly in the list file or observations. It also appears that the water is withdrawn by LKT at a concentration 0 instead of the concentrations of the lake. 

**To Reproduce**
1. Set up flow and transport models that run separately using FMI
2. Set a withdrawal rate for lak. List PRINT_INPUT and PRINT_FLOWS in package options and add a an obs6 file to print the withdrawal
3. In .lkt, list PRINT_CONCENTRATION and PRINT_FLOWS
4. Run the model
5. In the lst file for the gwf model, find 'LAK PACKAGE (LAK-1) DATA FOR PERIOD ' for the period with withdrawal. The specified withdrawal is printed here.
6. In the lst file for the gwf model, find 'LAK-1 PACKAGE - SUMMARY OF FLOWS FOR EACH CONTROL VOLUME   PERIOD' for the period with withdrawal. Notice withdrawal is listed as 0, but the mass balance error is positive and equal to the specified withdrawal. Note that the model converged fine, so the mass balance error is not real.  
7. In the lst file for the gwf model, find 'LAK-1 BUDGET FOR ENTIRE MODEL AT END OF TIME STEP ' for the period with withdrawal. Notice withdrawal is listed as 0.
8. in the LAK observation output, notice the withdrawal is listed as 0. 
9. In the lst file for the gwt model, note that 'withdrawal' mass is listed as 0. 
10. A hand calculation indicates that the concentration in the lake is the result of 0 concentration water being removed, thus increasing the concentration of the lake. 

**Expected behavior**
The withdrawal mass should be printed correctly in the lst and obs files for both lak and lkt. Water removed by lkt should be at the concentration of the lake, not 0. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: nightly build 20220913

**Comment by langevin-usgs** [comment]
@RyanConway91, thank you for reporting this issue.  I think I tracked down the problem and made the fix.  It should be available tonight after the nightly build finishes.  Please let me know if you are still experiencing problems by reopening this issue.
