### ISSUE TITLE
Incorrect input file for ex-gwt-prudic2004t2

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1053]
In the Lake package, the following line should be added to the Options section.
  LENGTH_CONVERSION   3.28081
because an outlet is specified and the model length unit is feet.

**Comment by rbwinst-usgs** [comment]
Alternatively, add a comment to explain why the LENGTH_CONVERSION is not included.

**Comment by langevin-usgs** [comment]
@emorway-usgs, I know you have a lot on your plate, but it would be great if you could take this to completion.
