### ISSUE TITLE
UZF memory leak

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/modflow6#107]
The code below in uzf_ar looks like it may be a memory leak.  First the elements array is allocated, and then each element is again allocated.

```
    !
    ! -- Allocate UZF objects plus one extra for work array
    allocate(this%elements(this%nodes+1))
    do i = 1, this%nodes + 1
      allocate(this%elements(i))
    enddo
```

**Comment by echristi** [comment]
I have a model that I converted from NWT to MODFLOW 6 and this seems to be an issue.  It quickly blows up the RAM then eventually reports back insufficient virtual memory and indicates gwf3uzf8.f90 is the issue.   Using official release of 6.0.4.  Checking to see if progress has been made on this.

**Comment by langevin-usgs** [comment]
We've seen this before with a NWT model converted to MODFLOW 6.  The MODFLOW 6 UZF package does not have the option to work as a recharge package, which is an option with the NWT UZF package.  This is a response that we recently sent to someone that encountered this:

"Hey Scott, it looks like you are using UZF as a simple recharge package, which doesn't simulate wetting fronts.  Unfortunately, the MODFLOW 6 UZF package does not have that same capability.  We probably should add something to the mf5to6 converter to handle this specific case."

Does this explain your situation?

**Comment by echristi** [comment]
Do you mean MODFLOW 6 doesn’t support the option of having IUZFOPT in the UZF package for NWT set to <=0?  No, I’m not doing that but the NWT model is steady-state. So, not really simulating the wetting fronts.  For my current need regular recharge package will work fine so I’m going to use that.
However, I did manually make a very simple UZF package and it worked just fine (NUZFCELLS = 1000).  If I increase the number of UZF cells the memory problem does come back (NUZFCELLS = 100000).
Also, MF5toMF6 does not fill in thtr and thti when SPECIFYTHTI and SPECIFTHTR are not used in the NWT UZF package.

**Comment by langevin-usgs** [comment]
Do you have a tiny MODFLOW 6 model (with a lot of UZF cells) that you could zip up and post here for me to test?

**Comment by echristi** [comment]
The attached very simple model with UZF will cause the memory to explore.
[uzf_large.zip](https://github.com/MODFLOW-USGS/modflow6/files/3075125/uzf_large.zip)
