### ISSUE TITLE
Add lag time to MOVER

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#1070]
How hard would it be to add a time lag to mover? For example, for a simple watershed where DRNS and MOVER are used to route runoff to a LAK,  if I compare the MOVER flux timeseries to a simple runoff hydrograph runoff curve method for a precip event, I get a single spike from MOVER where as from the curve number method (and from basic hydrology) I know this is not the case. If I could add a lag time to each MOVER cell based on the distance from the DRN to the LAK, I think I could do a lot better.

Also, could a 'Discussion' tab be added this github page like there is for flopy?

**Comment by langevin-usgs** [comment]
Added to feature request list.
