### ISSUE TITLE
Budget bug involving UZF and MVR packages in MODFLOW 6 and maybe ZONEBUDGET

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1075]
**Describe the bug**
The budget written by MODFLOW 6 to the listing file has a much different value from that derived by adding up related terms in the cell-by-cell flow file generated by MODFLOW 6 or written by ZONEBUDGET

**To Reproduce**
Run the attached MODFLOW 6 and ZONEBUDGET models. Look at the budgets for the UZF, SFR, and MVR packages in the MODFLOW 6 listing file. The amount reported as moved from UZF to MVR in the UZF budget is much less than the amount reported as moved to MVR in the MVR budget.
In the ZONEBUDGET budget, the there is a term for flow to MVR but not for flow from MVR.

**Expected behavior**
The budget term from UZF to MVR in the UZF budget should be the same or similar to the budget term from UZF to MVR in the MVR budget.
In the ZONEBUDGET budget, the there should be term for flow both from and to MVR.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
[UZF_Budget_Bug.zip](https://github.com/MODFLOW-USGS/modflow6/files/9940971/UZF_Budget_Bug.zip)

**Comment by rbwinst-usgs** [comment]
This is a simplified version of the model. 
One stress period instead of 2. 
DIS instead of DISV
Larger cells.
[Simplified.zip](https://github.com/MODFLOW-USGS/modflow6/files/9941513/Simplified.zip)

**Comment by emorway-usgs** [comment]
Hi @rbwinst-usgs, thanks for the reproducible example.  To make sure I'm on the same page as you, I'm keying in on this statement: 
> The amount reported as moved from UZF to MVR in the UZF budget is much less than the amount reported as moved to MVR in the MVR budget.

The following screen shot seemingly supports that statement with a significant imbalance:

![apparent_imbalance](https://user-images.githubusercontent.com/3236576/201442751-e45c479b-8fa0-4b80-90e9-88a2df83eca4.png)

However, there's more to the story, I think.  We also need to factor in what's reported in the global budget, i.e., GWD:

![for_balance](https://user-images.githubusercontent.com/3236576/201442894-40800d8b-c39f-468f-a0ba-58da9316f7ba.png)

When we do that, I think we're OK.  It may be that I'm missing your larger concern.  If I have, please don't hesitate to point me to the issue. 

Also, I'll add that I think the issue you've raised does point to a part of the budget that perhaps could be improved with additional line items.  For example, perhaps you were expected something like this (proposed part highlighted in red):

![budg_idea](https://user-images.githubusercontent.com/3236576/201443717-57aa1e61-582e-4257-b50b-65afadc259a1.png)

However, there are probably some significant programmatic hurdles to this kind of reporting.

**Comment by rbwinst-usgs** [comment]
The UZF budget appears to show a large imbalance. The imbalance appears similar in size to the amount coming from UZF in the MVR budget. How is a user to know whether the imbalance represents a problem in the model if, as you say, there isn't a problem.

Richard B. Winston
US Geological Survey
Integrated Modeling and Prediction Division
***@***.******@***.***>
https://profile.usgs.gov/rbwinst<http://water.usgs.gov/nrp/gwsoftware/>
703-648-5988
on Wednesdays: 301 474-2762
Fax: 703 648-5274

The following are excellent guides especially for beginning modelers.
Reilly, T.E., 2001, System and boundary conceptualization in ground-water flow simulation:  U.S. Geological Survey Techniques of Water-Resources Investigations, book 3, chap. B8, 30 p.
https://water.usgs.gov/pubs/twri/twri-3_B8/<http://water.usgs.gov/pubs/twri/twri-3_B8/>

Reilly, T.E., and Harbaugh, A.W., 2004 , Guidelines for evaluating ground-water flow models: U.S. Geological Survey Scientific Investigations Report 2004-5038, 30 p.
https://pubs.usgs.gov/sir/2004/5038/

Free books on Groundwater: https://gw-project.org/books/

"Codes only live if somebody loves them." Matt Tonkin, June 2, 2015, MODFLOW and More 2015 Conference Panel Discussion.

"When you started to have that problem, when you couldn't get a solution, you could get help with that. You could not get any help if you had a conceptual screw-up in your understanding of the regional hydrology. If you didn't have a rough idea of what the evapotranspiration was, of what the big streams were doing, and how the stream flow was related to groundwater, there's where you could get into trouble where nobody else could help you." Gordon Bennett in an interview, Feb. 21, 2019.

________________________________
From: Eric Morway ***@***.***>
Sent: Friday, November 11, 2022 6:26 PM
To: MODFLOW-USGS/modflow6 ***@***.***>
Cc: Winston, Richard B ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MODFLOW-USGS/modflow6] Budget bug involving UZF and MVR packages in MODFLOW 6 and maybe ZONEBUDGET (Issue #1075)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @rbwinst-usgs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frbwinst-usgs&data=05%7C01%7Crbwinst%40usgs.gov%7C083756bb025644b54aeb08dac43c2d59%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638038059998400147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K63WoSPWZzrQH%2BDIraniOS0gHt5DYiawfOa3X8gS%2FY0%3D&reserved=0>, thanks for the reproducible example. To make sure I'm on the same page as you, I'm keying in on this statement:

The amount reported as moved from UZF to MVR in the UZF budget is much less than the amount reported as moved to MVR in the MVR budget.

The following screen shot seemingly supports that statement with a significant imbalance:

[apparent_imbalance]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3236576%2F201442751-e45c479b-8fa0-4b80-90e9-88a2df83eca4.png&data=05%7C01%7Crbwinst%40usgs.gov%7C083756bb025644b54aeb08dac43c2d59%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638038059998400147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ABmKyqRCdXxisweGCYJbicrIqF3NQO%2F%2BjUFNYB1kuew%3D&reserved=0>

However, there's more to the story, I think. We also need to factor in what's reported in the global budget, i.e., GWD:

[for_balance]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3236576%2F201442894-40800d8b-c39f-468f-a0ba-58da9316f7ba.png&data=05%7C01%7Crbwinst%40usgs.gov%7C083756bb025644b54aeb08dac43c2d59%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638038059998400147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6xVePYgTFM5953LZsiFDCeKqJspFPKIlbH6IEkxj0I0%3D&reserved=0>

When we do that, I think we're OK. It may be that I'm missing your larger concern. If I have, please don't hesitate to point me to the issue.

Also, I'll add that I think the issue you've raised does point to a part of the budget that perhaps could be improved with additional line items. For example, perhaps you were expected something like this (proposed part highlighted in red):

[budg_idea]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3236576%2F201443717-57aa1e61-582e-4257-b50b-65afadc259a1.png&data=05%7C01%7Crbwinst%40usgs.gov%7C083756bb025644b54aeb08dac43c2d59%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638038059998400147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qdhDNu%2BWT0TfhAkdLGamGNe88DFFsr%2FU6DiRifCBE8Q%3D&reserved=0>

However, there are probably some significant programmatic hurdles to this kind of reporting.

**Comment by langevin-usgs** [comment]
I believe there are two things going on here.  (1) UZF in MODFLOW 6 is designed so that the user should put UZF cells in all GWF cells that may be above or contain the water table.  (2) If the user does not do this, then there appears to be a bug in the UZF code that results in a mass balance error.  For this model, UZF cells are placed only in the top layer, but in some locations the water table is in deeper layers.  If the water table is in a deeper layer, then the UZF cell in layer 1 does not send any water to GWF.  For this problem, the solution is to add UZF cells to deeper layers, and I suspect the problem will behave as intended.  In the meantime, we are also working on a fix so that this water is not lost.
