### ISSUE TITLE
BUDGETCSV option in Lake package not accepted

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1079]
**Describe the bug**
When the BUDGETCSV is the first option in the Lake package, MODFLOW stops with an error message.

**To Reproduce**
Run the attached model.
[ex-gwf-lak-p02 - ModifiedLakePackage.zip](https://github.com/MODFLOW-USGS/modflow6/files/9963128/ex-gwf-lak-p02.-.ModifiedLakePackage.zip)
This was originally reported by Giovanni Firmani, g.firmani@gmail.com

**Expected behavior**
run normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by langevin-usgs** [comment]
This was fixed in #1035.  This model runs with the nightly-build version [here:](https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases)  .

**Comment by giovannifi** [comment]
Hi, thanks a lot for the super quick turnaround with this. I am currently using this new build and I noticed a slightly different (better in my opinion) behaviour of the solution method. It seems that the new mf6 build requires now the definition of two IMS packages when dealing with GWF and GWT models for example. This is a great thing as the closure parameters can be calibrated for each type of solution (head in the first case and concentration for the second case). However, I have not found a way to define the "solutiongroup" in the simulation name file (mfsim.nam) using flopy. I tried to use the module `flopy.mf6.ModflowNam()` but it look ineffective (it does not make any modification of the mfsim.nam file). 
At the moment I am manually editing the mfsim.nam file that flopy spits out.

I understand that this is an off-topic question, but would you be able to help with this?

Many thanks in advance

**Comment by giovannifi** [comment]
@langevin-usgs thanks a lot! I reviewed some of your examples and I found the command `sim.register_ims_package()` that I applied for each IMS package I created that solved my problem. Now the file mfsim.nam is created as I wanted.

I am still surprised that the `flopy.mf6.ModfloNam()` module it does not look to work or probably I am not able to use it properly.
