### ISSUE TITLE
Documentation: Section "Treatment of dry cells" in Newton formulation is missing?

### ISSUE THREAD

**Issue by Huite** [MODFLOW-USGS/modflow6#1080]
I've been trying to discover how MODFLOW6 treats dry cells with the Newton formulation enabled. I do not seem to able to find this in the MODFLOW6 documentation (I've searched for every instance of the word "dry"). I would expect such a section in: Documentation for the MODFLOW 6 Groundwater Flow Model (tm6a55.pdf), either under "Formulation of Newton-Raphson Equations for Solution" or in the NPF section.

Fortunately, the MODFLOW-NWT documentation (tm6a37.pdf) has a very clear explanation in a section called "Treatment of Dry Cells". From glancing through the source code, it seems like MODFLOW6 uses the same approach. I feel this section could be included with only some minor modifications.

**Comment by langevin-usgs** [comment]
Closing as not an issue with the MODFLOW 6 program.  Agreed that documentation could be improved.
