### ISSUE TITLE
Change 'inflow' to 'ext-inflow' in LAK. 

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#1081]
in the PERIOD block of the LAK package, one option for laksetting is 'INFLOW'. However, all other packages (LKT, SFR, SFT, ect) and obs utilities that have an equivalent setting call it 'EXT-INFLOW'. This is confusing. Is the LAK 'INFLOW' somehow different from 'EXT-INFLOW'? If not, it should be called 'EXT-INFLOW' for consistency.

**Comment by langevin-usgs** [comment]
The LAK and SFR Packages both allow INFLOW as a PERIOD block setting.  EXT-INFLOW and INFLOW are both different observation types and have slightly different meanings.
