### ISSUE TITLE
MAW: abstraction then injection bore, injections not applied when rate_scaling is enabled

### ISSUE THREAD

**Issue by giovannifi** [MODFLOW-USGS/modflow6#1087]
**Describe the bug**
I am running a transient simulation where I model some abstraction bores with the MAW package. Some of my bores start abstracting for a few months and then the same bores are used for injection. I set the MAW package with the option RATE_SCALING when the bores abstract in order to reduce the abstraction rate with the depletion of the aquifer and eventually stop the abstraction if the water table falls below the assigned level threshold. When the bores are injecting I do not assign the option RATE_SCALING. So, during the simulation the periods when the bore pumps work OK. However, when the bores become injection wells the injections are not simulated although they are declared in the input file. I am not really sure why this is happening, however if I do not set the option RATE_SCALING for the pumping periods, the injections work. I created a test model where I reproduced the issue with only one bore. Please see the script below that creates the required packages to run the model

```
import flopy
import numpy as np

path_ws = r'F:\Working_Folder\testing'
name = "tutorial01_mf6"
h1 = 100
h2 = 90
Nlay = 10
N = 101
L = 400.0
H = 50.0
k = 1.0

sim = flopy.mf6.MFSimulation(
    sim_name=name, exe_name="mf6", version="mf6", sim_ws=path_ws
)

nam = flopy.mf6.ModflowNam(sim, continue_=True)

tdis = flopy.mf6.ModflowTdis(
                             sim, pname="tdis", time_units="DAYS", nper=3,
                             perioddata=[(1.0, 1, 1.0), (10, 10, 1.0), (10, 10, 1.0)],
                             # ats_perioddata=[(1, 1, 0.01, 10, 1.1, 2.), (2, 1, 0.01, 10, 1.1, 2.)],
                             # maxats=2
                            )

ims = flopy.mf6.ModflowIms(sim, pname="ims", complexity="SIMPLE")

# ats = flopy.mf6.ModflowUtlats(sim, maxats=2, perioddata=[(1, 1, 0.01, 10, 1.1, 2.), (2, 1, 0.01, 10, 1.1, 2.)])

model_nam_file = "{}.nam".format(name)

gwf = flopy.mf6.ModflowGwf(sim, modelname=name, model_nam_file=model_nam_file, )
sim.register_ims_package(ims, [gwf.name])

bot = np.linspace(-H / Nlay, -H, Nlay)
# bot = -50.
delrow = delcol = L / (N - 1)
dis = flopy.mf6.ModflowGwfdis(
    gwf,
    nlay=Nlay,
    nrow=N,
    ncol=N,
    delr=delrow,
    delc=delcol,
    top=0.0,
    botm=bot,
)

start = h1 * np.ones((Nlay, N, N))
ic = flopy.mf6.ModflowGwfic(gwf, pname="ic", strt=start)

steady = {0: True}
transient = {1: True}
npf = flopy.mf6.ModflowGwfnpf(gwf, icelltype=1, k=k, save_flows=True)
sto = flopy.mf6.ModflowGwfsto(gwf, iconvert=1, ss=1e-4, sy=0.1, steady_state=steady,
                              transient=transient)

chd_rec = []
chd_rec.append(((0, int(N / 4), int(N / 4)), h2))
for layer in range(0, Nlay):
    for row_col in range(0, N):
        chd_rec.append(((layer, row_col, 0), h1))
        chd_rec.append(((layer, row_col, N - 1), h1))
        if row_col != 0 and row_col != N - 1:
            chd_rec.append(((layer, 0, row_col), h1))
            chd_rec.append(((layer, N - 1, row_col), h1))
chd = flopy.mf6.ModflowGwfchd(
    gwf,
    pname='chd',
    maxbound=len(chd_rec),
    stress_period_data=chd_rec,
    save_flows=True,
)

iper = 0
ra = chd.stress_period_data.get_data(key=iper)

# Create the output control (`OC`) Package
headfile = "{}.hds".format(name)
head_filerecord = [headfile]
budgetfile = "{}.cbb".format(name)
budget_filerecord = [budgetfile]
saverecord = [("HEAD", "ALL"), ("BUDGET", "ALL")]
printrecord = [("HEAD", "LAST")]
oc = flopy.mf6.ModflowGwfoc(
    gwf,
    saverecord=saverecord,
    head_filerecord=head_filerecord,
    budget_filerecord=budget_filerecord,
    printrecord=printrecord,
)


well_packagedata = [(0, 0.1, -5., 100., 'SPECIFIED', 1, 'well1')]

hk_skin = 1.0e3
well_condata = [(0, 0, (0, 0, 9), 0., 0., hk_skin, 0.)]

well_data = [(0, 'STATUS', 'ACTIVE'), (0, 'RATE', 0.)]
well_data1 = [(0, 'STATUS', 'ACTIVE'), (0, 'RATE', -5.), (0, 'RATE_SCALING', -4., 5)]
well_data2 = [(0, 'STATUS', 'ACTIVE'), (0, 'RATE', 10.)]
well_perioddata = {0: well_data, 1: well_data1, 2: well_data2}

obs_wells = [('well1_head', 'head', 1), ('well1_rate', 'rate', 1)]
osb_rates_file_name = 'wells_out.csv'

maw = flopy.mf6.modflow.mfgwfmaw.ModflowGwfmaw(gwf, pname='maw', save_flows=True, nmawwells=1,
                                               packagedata=well_packagedata, connectiondata=well_condata,
                                               perioddata=well_perioddata, boundnames=True,
                                               observations={osb_rates_file_name: obs_wells})


sim.write_simulation()
# sim.run_simulation()
```

**To Reproduce**
1. run the script above to create the packages
2. run the model via the dos command line
3. open the lst file of the flow model and check the MAW water balance of the very last stress period. YOu will notice that there is no water in the system from the MAW although the MAW package is set to inject 10 kL/d
4. try all the points above but this time disable the rate_scaling option (replace the line `well_data1 = [(0, 'STATUS', 'ACTIVE'), (0, 'RATE', -5.), (0, 'RATE_SCALING', -4., 5)]` with `well_data1 = [(0, 'STATUS', 'ACTIVE'), (0, 'RATE', -5.)]`). You will notice this time that in the last stress period there is an injection in the system

**Expected behavior**
I would expect the model to apply the injection of 10kL/d in the last stress period

**Desktop (please complete the following information):**
 - OS: Windows 10
 - MF version: MF6 version 6.4.0 (release candidate)

**Comment by giovannifi** [comment]
I had a second thought about the above and I think I got where the problem is. The RATE_SCALING option is actually carried on also for the following stress periods although this is not specifically declared. This option, however, works with an opposite behaviour when the sign of the rate is changed. In case of injection Rate_scaling prevents any injections if the water table is actually above the assigned threshold which the case of my example above.
So, the question is this is the expected behaviour of the software. In my opinion it is not really nice that the rate_scaling option is applied by default to all the following stress periods if this is not explicitly declared.
I think my workaround is to assign a suitable scale_rating option when the bore becomes an injection well. I tested it with the code I posted earlier and it works

**Comment by langevin-usgs** [comment]
It's probably not clear but this is the expected behavior.  The user guide says this:

> All of the advanced stress package information in the PERIOD block will continue to apply for subsequent stress periods until the end of the simulation, or until another PERIOD block is encountered. When a new PERIOD block is encountered only the wells specified in the new period block will be changed. A well
not specified in the new period block will continue to behave according to its specification in the previous PERIOD block.

As you've found, these  "mawsettings" only change the specific setting.  I don't think we have a way to fully reset all the well settings.

I think you have two options, for the injection wells, you can change the pump elevation and scaling length so that the rate is not changed from your intended value (which is what you've already discovered), or, you could create two wells, one for injection and one for withdrawal, and turn the on/off appropriately so they apply to the intended periods.

**Comment by giovannifi** [comment]
I adopted the first option as mentioned earlier. I thought about the two wells but I think it is too convoluted and also would create potential errors in the post processing.
