### ISSUE TITLE
Compiler warnings are not checked anymore in the CI

### ISSUE THREAD

**Issue by Hofer-Julian** [MODFLOW-USGS/modflow6#1097]
I see that compiler warnings are not checked anymore in the CI since https://github.com/MODFLOW-USGS/modflow6/pull/1076
Fine, if that's a conscious decision, but I just wanted to make sure this wasn't an oversight.

**Comment by w-bonelli** [comment]
@Hofer-Julian that was moved from its own workflow into the `build` job in `ci.yml`, unless I'm misunderstanding something warnings are [still checked](https://github.com/MODFLOW-USGS/modflow6/blob/develop/.github/workflows/ci.yml#L62)?

**Comment by Hofer-Julian** [comment]
Indeed, I haven’t seen that it’s now part of a bigger chain.

thanks @w-bonelli
