### ISSUE TITLE
Error messages by VSC package

### ISSUE THREAD

**Issue by AndreasRIHU** [MODFLOW-USGS/modflow6#1098]
Hi Chris,
in order to test your new VSC package, I modified an existing example project.
But the VSC package gives a couple of error messages in regard to the drn package for cells which do not contain drains at all.
I've attached the modified example and a screenshot of the error.
Best regards
Andreas
![Error_VSC](https://user-images.githubusercontent.com/117801520/205312745-84048b4f-4398-4124-a087-a7efd29df0bf.jpg)
[__test205_gwtbuy-henrytidal.zip](https://github.com/MODFLOW-USGS/modflow6/files/10141768/__test205_gwtbuy-henrytidal.zip)

**Comment by emorway-usgs** [comment]
@AndreasRIHU Thanks for the reproducible example, taking a look at it now.

**Comment by emorway-usgs** [comment]
When VSC was added, a new function named `bnd_store_user_cond` was added to `BoundaryPackage.f90`.  

In the following, code:

```
    !
    ! -- store backup copy of conductance values
    do l = 1, nlist
      nodeu = nodelist(l)
      noder = this%dis%get_nodenumber(nodeu, 0)
      if (noder <= 0) then
        call this%dis%nodeu_to_string(nodeu, nodestr)
        write (errmsg, *) &
          ' Cell is outside active grid domain: '// &
          trim(adjustl(nodestr))
        call store_error(errmsg)
      end if
      condinput(l) = rlist(2, l)
    end do
    !
    ! -- return
    return
```
the `do` loop needs to be removed since nodelist already has reduced node numbers, this bit of code shouldn't have been duplicated here.  This fix will be made available in a minor release.
