### ISSUE TITLE
Cascading water between UZF-UZF through the MVR is not working properly

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#1116]
**Describe the application**
In my application for a 'real' model, I am cascading the available water (REJ-INF and GWD) from the upslope UZF cells to the downgradient UZF cells. I have a lot of UZF-UZF connections in which each UZF can be a provider and/or receiver with making sure that the sum of the FACTORs for any UZF provider = 1). I am also using the COMPLEX option in the IMS (so inner and outer convergence criteria = 0.1). 

**Describe the bug**
While making sure that all the water from any UZF provider will be moved to the next downgradient UZF receivers (sum of FACTORs of each UZF provider = 1), in principle, there should be no remaining REJINF and GWD (so they should be zero) and all the water should go to REJINF-To-MVR and GWD-To-MVR. However, it was not the case, as for many UZF providers, there are still large values for REJINF and GWD

**To Reproduce**
With a great help of @emorway-usgs, we have made a small version out of the big 'real' model (so only 12 cells out of 23302) and only (24 MVR connections). I need to mention that from our tests we found out that the convergence criteria plays a big role to show/not show the error. So, when tightening the convergence criteria to 0.001, the problem is solved. However, this will not help when going back to the big 'real' model, which will not converge with that tightened criteria. The small version could be used as an autotest (attached here: [test_gwf_mvr_cascades.py.txt](https://github.com/MODFLOW-USGS/modflow6/files/10231941/test_gwf_mvr_cascades.py.txt)).

So, from the attached code, if we take one example - one MVR connection  (to make things clear)
1. 100% of the rejected infiltration in the fifth MVR connection should be moved from the first UZF object listed (as listed in the UZF input) to the 2nd UZF object listed (FACTOR = 1.0).
3. If you go to line 767 of the attached code, which explains the REJINF from UZF1 to UZF2,
4.  the output from that line indicates the error (REJINF of UZF1 is not 0)
5. To show/not show the error, you will need to tight/lose the convergence criteria in line 603  

**Expected behavior**
A possible solution is that the transferred MVR flows could be added to the convergence checks while the head criterion can remain at 0.1, or something to that effect

**Screenshots**
a screenshot shows the 12 cell of the model. The arrow shows the connection we describe (from UZF 1 to UZF2)
![cascade_voroni](https://user-images.githubusercontent.com/54531356/207723275-d21607ca-147c-4899-aa47-2ebc110d2cef.png)

**Desktop (please complete the following information):**
 - OS: [both Windows and Linux]
 - Version [e.g. 6.4]

**Comment by langevin-usgs** [comment]
Hi @MostafaGomaa93, thanks for this information.  So it seems like this is not really a bug, but rather a byproduct of a solution that is not fully converged.  There are already convergence checks on a couple of the uzf terms (rejected infiltration, groundwater recharge, and groundwater discharge) and I added one more for the inflows to uzf from mover.  As you mentioned, the simple problem you provided gives a better answer when dvclose is set smaller.  With the new convergence check, this simple test problem behaves the same way.  dvclose must be set to 0.001 in order for the test to give the expected results.

It's possible that for your larger model, this additional convergence check will improve your results, but you may still have convergence problems. The check involves converting the mover inflow rate to an equivalent depth over the uzf cell, which is how a comparison is made to dvclose.  Before I formally make this change to UZF, it might be helpful if you would test it for your real model.  I've attached a zipped windows executable here with the additional convergence check.  If you haven't looked already, turn on the PACKAGE_CONVERGENCE FILEOUT option for UZF and look at the terms  in the resulting csv file that may be causing convergence problems.  You will now see a qfrommvr term included.

[mf6.exe.zip](https://github.com/MODFLOW-USGS/modflow6/files/10239738/mf6.exe.zip)

**Comment by MostafaGomaa93** [comment]
Hello Mr. @langevin-usgs . Thanks for your reply

If its not too much work, would you mind send me a linux executable (same as the one you send for windows with the additional convergence check)? I will do some tests in the big model and will get back to you
