### ISSUE TITLE
Size of ./.git directory

### ISSUE THREAD

**Issue by scharlton2** [MODFLOW-USGS/modflow6#1122]
As @mjr-deltares mentioned on 2022-12-21, cloning the [MODFLOW-USGS/modflow6](https://github.com/MODFLOW-USGS/modflow6) repository takes a long time due to the size of the `./.git` folder.

Although a single branch can be cloned and checked out using:

`git clone --branch develop --single-branch git@github.com:MODFLOW-USGS/modflow6.git modflow6-develop `

Here are the sizes of the `./.git` directory when the --single-branch option is used::
| Branch                                                          |  Size        |
|------------------------------------------------|-----------|
|  upstream/develop                     |   14 MB |
|  upstream/gh-pages                    |   1.17 GB |
|  upstream/lnf                         |   6.5 MB |
|  upstream/master                     |      17 MB |
|  upstream/parallel                     |   5.2 MB |
|  upstream/post-release-6.4.1-reset      |   43 MB |
|  upstream/v6.4.1                     |    16.5 MB |
|  upstream/v6.4.1rc                    |   16.5 MB |
|  upstream/vkd                        |    6.57 MB |

Here's the beginning of the diff from the most recent commit https://github.com/MODFLOW-USGS/modflow6/commit/01d5f531bfe02520d9455106bdbd4e8076319544 on the gh-pages branch:

```
diff --git a/_array_handlers_8f90.html b/_array_handlers_8f90.html
index c71247854e..53ca5851cc 100644
--- a/_array_handlers_8f90.html
+++ b/_array_handlers_8f90.html
@@ -163,7 +163,7 @@ Functions/Subroutines</h2></td></tr>
 <div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
   <ul>
     <li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.html">src</a></li><li class="navelem"><a class="el" href="dir_ff383ddf1aa4eab0c4ce7910366d05a5.html">Utilities</a></li><li class="navelem"><a class="el" href="_array_handlers_8f90.html">ArrayHandlers.f90</a></li>
-    <li class="footer">Generated on Fri Dec 16 2022 13:26:44 for MODFLOW 6 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1 </li>
+    <li class="footer">Generated on Mon Dec 19 2022 15:24:52 for MODFLOW 6 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1 </li>
   </ul>
 </div>
 </body>
diff --git a/_array_handlers_8f90_source.html b/_array_handlers_8f90_source.html
index 89b4d69f14..418821f359 100644
--- a/_array_handlers_8f90_source.html
+++ b/_array_handlers_8f90_source.html
@@ -580,7 +580,7 @@ $(document).ready(function(){initNavTree('_array_handlers_8f90_source.html','');
 <div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
   <ul>
     <li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.html">src</a></li><li class="navelem"><a class="el" href="dir_ff383ddf1aa4eab0c4ce7910366d05a5.html">Utilities</a></li><li class="navelem"><a class="el" href="_array_handlers_8f90.html">ArrayHandlers.f90</a></li>
-    <li class="footer">Generated on Fri Dec 16 2022 13:26:44 for MODFLOW 6 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1 </li>
+    <li class="footer">Generated on Mon Dec 19 2022 15:24:52 for MODFLOW 6 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1 </li>
   </ul>
 </div>
 </body>
diff --git a/_array_reader_base_8f90.html b/_array_reader_base_8f90.html
index 090e871c20..c6b187fb4c 100644
--- a/_array_reader_base_8f90.html
+++ b/_array_reader_base_8f90.html
@@ -163,7 +163,7 @@ Functions/Subroutines</h2></td></tr>
 <div id="nav-path" class="navpath"><!-- id is needed for treeview function! -->
   <ul>
     <li class="navelem"><a class="el" href="dir_68267d1309a1af8e8297ef4c3efbcdba.html">src</a></li><li class="navelem"><a class="el" href="dir_ff383ddf1aa4eab0c4ce7910366d05a5.html">Utilities</a></li><li class="navelem"><a class="el" href="dir_df36ecf71f54111e308f6afa8aa107ba.html">ArrayRead</a></li><li class="navelem"><a class="el" href="_array_reader_base_8f90.html">ArrayReaderBase.f90</a></li>
-    <li class="footer">Generated on Fri Dec 16 2022 13:26:44 for MODFLOW 6 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1 </li>
+    <li class="footer">Generated on Mon Dec 19 2022 15:24:52 for MODFLOW 6 by <a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1 </li>
   </ul>
 </div>
 </body>

```

Which, uncompressed is 1.3 MB.

I don't think it's necessary to store all of this (most of which is different dates) in the repository since it could be regenerated by running doxygen again and using a regexp to replace the dates.

I recommend we remove the `gh-pages` branch and modify [./.github/workflows/docs.yml](https://github.com/MODFLOW-USGS/modflow6/blob/develop/.github/workflows/docs.yml) to delete the `gh-pages` branch at the end of the job (If there's no option to do so in the [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#github-pages-action) action.

@scharlton2 AKA Scott no. 2

**Comment by w-bonelli** [comment]
It looks like GitHub Pages [no longer require a source branch at all](https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/#protecting-github-pages-deployments), even to build from:

> GitHub Pages are now tracking deployments instead of builds. A source branch is not required anymore and is at the discretion of a workflow’s triggers

From what I can tell `peaceiris/actions-gh-pages` still expects a branch, but if artifacts are regenerated on each build we could use the action [`actions/deploy-pages`](https://github.com/actions/deploy-pages), which seems to do the same thing but supports either branch or arbitrary actions as the source

**Comment by w-bonelli** [comment]
addressed by https://github.com/MODFLOW-USGS/modflow6/pull/1210, the `gh-pages` branch has been removed
