### ISSUE TITLE
Allow GWT IDOMAIN to be different from GWF IDOMAIN

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/modflow6#1129]
It would be useful to allow the GWT active domain to be smaller than the GWF active domain.  MODFLOW 6 currently requires that the GWF IDOMAIN is the same as the GWT IDOMAIN.  It may be possible to lift this restriction by modifying the GWT FMI Package to perform the necessary cell mapping/remapping.

**Comment by langevin-usgs** [comment]
Added to requested feature list.

**Comment by wpbonelli** [comment]
PRT could follow suit on this feature.

**Comment by emorway-usgs** [comment]
...and GWE too?

**Comment by aprovost-usgs** [comment]
GWT, GWE, and PRT could all potentially benefit from being able to have a different IDOMAIN array than the GWF they're exchanging with.  Though the capability might have different ramifications, or might require different restrictions, for each kind of model.  Just an intuitive feeling at this point, based on the fact that GWE keeps dry cells active (whereas GWF doesn't always) and that PRT is a simply different kind of animal that isn't solving a matrix equation.  Maybe it's all straightforward, but we'll need to think it through carefully.
