### ISSUE TITLE
PERLEN=0 for Steady-state

### ISSUE THREAD

**Issue by VermeulenPTM** [MODFLOW-USGS/modflow6#1133]
**Describe the bug**
MODFLOW6 terminates whenever PERLEN=0 disregarding the fact whether the timestep is transient or steady-state. This might be irrelevant and why not set PERLEN<>0 for a steady-state? Well, in the postprocessing, reading the outputfiles (HED and CBC), we need to know whether the results are steady- of belong to a transient timestep. We used PERLEN (written in the HED and CBC) files to make that descision. Thinking on this now, as TDIS is above each (sub)model with their STO package that determines whether DELT is used in the first place, a check on PERLEN<>0, is perhaps more appropriate at the processing of the STO package?

**To Reproduce**
Run a steady-state model and set PERLEN=0

**Expected behavior**
Model should continue, but it gives an error message and stops.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version	10.0.19042 Build 19042

**Comment by langevin-usgs** [comment]
Hi @VermeulenPTM, thanks for letting us know about this issue.  We will take a look.

**Comment by ScottBoyce** [comment]
Hi @VermeulenPTM, I was asked to look into your problem. I tried running a few of the MF6 example problems that had PERLEN=0 but was unable to replicate your issue. 

If you are comfortable, could you should the model you are having issues with or construct a simplified model that replicates the error? That will make it very easy for me to find the problem in the debugger.

Thanks

**Comment by VermeulenPTM** [comment]
Hi Scott,

Attached is a simple example, perlen is set to 0.0 for a steady-state model.

Greetings,
Peter

**Comment by ScottBoyce** [comment]
Thanks Peter (@VermeulenPTM),
I dont think the file attached correctly.
You may need to go directly to the issue forum on gitup and upload it to the issue chat window on here.

Scott

**Comment by VermeulenPTM** [comment]
Hi Scott,

Here is the example. In the code of MF6, you see reason for the stop here, the RETURN makes it an error, maybe it should be a CYCLE instead.

      ! -- Warn if perlen is zero
      if(perlen(kper) == DZERO) then
         write(iout, fmtpwarn) kper
         return
      end if

Greetings,
Peter
[MF6.ZIP](https://github.com/MODFLOW-USGS/modflow6/files/10454931/MF6.ZIP)

**Comment by jdhughes-usgs** [comment]
@VermeulenPTM just confirmed that your test model ran with the fix in PR #1139
