### ISSUE TITLE
Incorrect Error Message

### ISSUE THREAD

**Issue by VermeulenPTM** [MODFLOW-USGS/modflow6#1142]
**Describe the bug**
I think comparing two reals give an incorrect error message, the statement says both are equal but the message says they are different. There might be an error in the syntax of the error message as I do believe both are different.

ERROR REPORT:

  1. RIV BOUNDARY (7142) RIVER BOTTOM (    0.0600) IS LESS THAN CELL BOTTOM (
        0.0600)

**To Reproduce**

**Expected behavior**
I think comparing the reals is different than the echo used to describe the problem

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by langevin-usgs** [comment]
Verified that the code makes the correct comparison.  See [here](https://github.com/langevin-usgs/modflow6/blob/9ed141213c55eb2ed375eb1dc4997b9063976659/src/Model/GroundWaterFlow/gwf3riv8.f90#L153).  Suspect that this is a precision issue in the input files.  The error message is using f10.4 to report river bottom and cell bottom elevations.
