### ISSUE TITLE
The error happen when I run MPI-parallelized modflow6

### ISSUE THREAD

**Issue by lj-cug** [MODFLOW-USGS/modflow6#1174]
I downloaded MODFLOW6-parallel-6.2.1 some months ago, and later I compile the code using mpif90 compiler.
When I run the pleasant lake case like: mpirun -np 2 mf6
I told me the error: "ERROR REPORT: 1. Program error in slnmpiinit"
Other problem is I cannot find the repo of MPI parallel version now. Is it not available or in heavy development?
Could you please give me some hints?
Li Jian

**Comment by verkaik** [comment]
Hi Li,

I think you are using my prototyping code:

https://github.com/verkaik/modflow6-parallel

No, this code is not in heavy development and quite stable though. See e.g. https://gmd.copernicus.org/preprints/gmd-2022-226/ for its most recent application.

Did you pre-compile the code with preprocessor definition MPI_PARALLEL? How did you modify your input? In the mfsim.nam you should add the keyword DOMAIN_DECOMPOSITION in the options block:

BEGIN OPTIONS
  MEMORY_PRINT_OPTION SUMMARY
  DOMAIN_DECOMPOSITION 2
END OPTIONS

DOMAIN_DECOMPOSITION should be equal to the number of MPI processes you are using, hence np. In the models block you should assign each GWF model to a MPI process rank ID, starting from 1, something like:

BEGIN MODELS
  GWF6 .\m1_1\m1_1.nam m1_1 1
  GWF6 .\m1_2\m1_2.nam m1_2 2
END MODELS

Best, Jarno

**Comment by lj-cug** [comment]
Thank you very much! I will try it tomorrow. thanks for your help!li jian中国地质大学-------- 原始邮件 --------发件人： Jarno Verkaik ***@***.***>日期： 2023年3月20日周一 傍晚6:06收件人： MODFLOW-USGS/modflow6 ***@***.***>抄送： lj-cug ***@***.***>, Author ***@***.***>主    题： Re: [MODFLOW-USGS/modflow6] The error happen when I run MPI-parallelized modflow6 (Issue #1174)
Hi Li,
I think you are using my prototyping code:
https://github.com/verkaik/modflow6-parallel
No, this code is not in heavy development and quite stable though. See e.g. https://gmd.copernicus.org/preprints/gmd-2022-226/ for its most recent application.
Did you pre-compile the code with preprocessor definition MPI_PARALLEL? How did you modify your input? In the mfsim.nam you should add the keyword DOMAIN_DECOMPOSITION in the options block:
BEGIN OPTIONS
MEMORY_PRINT_OPTION SUMMARY
DOMAIN_DECOMPOSITION 2
END OPTIONS
DOMAIN_DECOMPOSITION should be equal to the number of MPI processes you are using, hence np. In the models block you should assign each GWF model to a MPI process rank ID, starting from 1, something like:
BEGIN MODELS
GWF6 .\m1_1\m1_1.nam m1_1 1
GWF6 .\m1_2\m1_2.nam m1_2 2
END MODELS
Best, Jarno

**Comment by jdhughes-usgs** [comment]
Not for main MODFLOW 6 repo.

**Comment by lj-cug** [comment]
Sorry for asking the parallelized modflow6 in this repo, but I cannot find the issue in Verkaik's forked repo.

**Comment by lj-cug** [comment]
Sorry for asking the parallelized modflow6 in this repo, but I cannot find the issue in Verkaik's forked repo.
Thank you, Verkaik!  I have compiled modflow6-parallel-6.2.1 with the option MPI_PAEALLEL, and modify the mfsim.nam as you suggested. But when I run mf6 using mpirun -np 2 mf6. The simulation time is longer than the serial mode. Could you please check my .nam file? It's better to send me an example can be run in parallel mode. Thanks !



BEGIN OPTIONS
MEMORY_PRINT_OPTION SUMMARY
DOMAIN_DECOMPOSITION 2
END OPTIONS

BEGIN TIMING
  TDIS6 mfusg_C.tdis
END TIMING

BEGIN MODELS
#modeltype      namefile      modelname
#   GWF6        mfusg_C.nam    GWF_1
GWF6 		mfusg_C.nam 	GWF_1 1
GWF6 		mfusg_C.nam 	GWF_1 2                 
END MODELS

BEGIN EXCHANGES
END EXCHANGES

BEGIN SOLUTIONGROUP 1
  MXITER 1
  IMS6      mfusg_C.ims GWF_1
END SOLUTIONGROUP
