### ISSUE TITLE
The problem for running modflow6-parallel

### ISSUE THREAD

**Issue by lj-cug** [MODFLOW-USGS/modflow6#1178]
Sorry for asking the parallelized modflow6 problem in this repo, but I cannot find the issue submitting in Verkaik's forked repo. And thank you Verkaik for you suggestion. I have two questions as following:
 (1) I have compiled modflow6-parallel-6.2.1 with the option MPI_PAEALLEL, and modify the mfsim.nam as you suggested. But when I run mf6 using mpirun -np 2 mf6. The simulation time is longer than the serial mode. Could you please check my .nam file? It's better to send me an example can be run in parallel mode. 
(2) Should I conduct the domain decomposition manually?  I cannot find any tutorial for running parallelized modflow6 simulation.
Thanks !
I use the modflow6-largetestmodels/test1000_751x751

BEGIN OPTIONS
MEMORY_PRINT_OPTION SUMMARY
DOMAIN_DECOMPOSITION 2
END OPTIONS

BEGIN TIMING
TDIS6 mfusg_C.tdis
END TIMING

BEGIN MODELS
#modeltype namefile modelname
#GWF6 mfusg_C.nam GWF_1

GWF6 mfusg_C.nam GWF_1 1
GWF6 mfusg_C.nam GWF_1 2
END MODELS

BEGIN EXCHANGES
END EXCHANGES

BEGIN SOLUTIONGROUP 1
MXITER 1
IMS6 mfusg_C.ims GWF_1
END SOLUTIONGROUP

**Comment by verkaik** [comment]
Hi,

Let's continue this issue on my fork:

https://github.com/verkaik/modflow6-parallel/issues/1

**Comment by mjr-deltares** [comment]
thanks @verkaik , and closing this issue on this board
