### ISSUE TITLE
libmf6 should not call exit

### ISSUE THREAD

**Issue by mwtoews** [MODFLOW-USGS/modflow6#1247]
It's very easy to "surprisingly" exit a Python script using either xmipy or modflowapi using this short script:
```python
from xmipy import XmiWrapper

lib = "/path/to/libmf6.so"
wd = "/tmp"  # path exists, but does not have any simulation
m = XmiWrapper(lib, working_directory=wd)
m.set_int("ISTDOUTTOFILE", 0)
m.initialize()
print("the script has already exited, and this is never shown")
```
which has exit code 2 and shows this stdout:
```
                                   MODFLOW 6
                U.S. GEOLOGICAL SURVEY MODULAR HYDROLOGIC MODEL
                        VERSION 6.4.1 Release 12/09/2022
...
 Writing simulation list file: mfsim.lst

ERROR REPORT:

  1. Could not open "mfsim.nam" on unit 1001. Specified file status OLD.
     Specified file format FORMATTED. Specified file access SEQUENTIAL.
     Specified file action READ. IOSTAT error number 29. STOP EXECUTION in
     subroutine openfile().
```
This is because of several MF6 subroutintes:

- Some allocate/read subroutine that encounters an error (e.g. missing file), which calls...
- `subroutine store_error`, which captures a useful error message and then calls...
- `subroutine ustop`, which prints a final message to the output device (if enabled) and then calls...
- `subroutine stop_with_error` which does `call exit(ireturn_err)` and exits the thread (along with Python) returning an error code 2
- Note that this is equivalent to calling `sys.exit(2)` mid-way in a Python script, except that it is instead called within a ctypes instance. It's not exactly a "crash", but it is not expected.

The Fortran (or C) exit statement is only appropriate for the main program. Libraries should never call exit, but instead return a non-zero integer.

There are potentially 1400 places in MF6 that call `store_error`, which means this is a big vulnerability to the stability of libmf6, since any of these can similarly "exit" the main application.

The expected behaviour should send the error message to BMI (using mf6bmiError module), then return BMI_FAILURE from the library method. So for this example, `m.initialize()` would raise `XMIError` with a message "Could not open "mfsim.nam" on unit 1001..." but keep the ctypes library instance and Python interpreter after the exception.

**Comment by mwtoews** [comment]
USTOP has been around MODFLOW since the 1990s, probably earlier.

Refactoring the whole API would be a big effort (e.g. changing subroutines to functions, checking return codes, etc.), so I agree that a wrapper approach is probably much simpler.

There are some clever ideas in [this Q/A](https://stackoverflow.com/questions/19596375/intercepting-fortran-stop-from-c)) worth exploring which work with C/C++. Other attempts have been made with Fortran ([doi:10.1145/2502932.2502933](https://doi.org/10.1145/2502932.2502933)), but I'm not sure if they would intercept a STOP and/or EXIT signal. Other ideas found [here](https://en.wikibooks.org/wiki/Fortran/error_handling).

**Comment by mjr-deltares** [comment]
Hi @mwtoews 

Thanks for sharing your insights. You're right, the refactoring you mention (with return codes all the way down) is a path we have explicitly decided not to follow. And then there is the issue of portability with many of the solutions that are around that didn't seem to be satisfying. But, you are right that this remains a big pitfall of the current API and we will increase the priority of this issue on the development roadmap!
