### ISSUE TITLE
Allow the user to set the validate mode (isim_mode) when calling the bmi function "initialize"

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1291]
**Is your feature request related to a problem? Please describe.**
I would like to be able to import an existing model using libmf6.dll. However, at present, the model will actually perform the simulation. It would be better to use the validate option but that isn't available in libmf6.dll

**Describe the solution you'd like**
Either create a new function called before initialize that sets the validate mode.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by mjr-deltares** [comment]
Hi @rbwinst-usgs , I think we can disclose that option through the API one way or another. Will add this to the list of features to work on. Feel free to discuss details on this or other functionality you might need for your use case on our regular development meeting.

**Comment by rbwinst-usgs** [comment]
Thank you for the invitation but I decline. I would appreciate it if you would cite any software you used in the publication and sending me the citation of the publication once it is in print.

Richard B. Winston
US Geological Survey
Integrated Modeling and Prediction Division
***@***.******@***.***>
https://profile.usgs.gov/rbwinst<http://water.usgs.gov/nrp/gwsoftware/>
703-648-5988
on Wednesdays: 301 474-2762
Fax: 703 648-5274

The following are excellent guides especially for beginning modelers.
Reilly, T.E., 2001, System and boundary conceptualization in ground-water flow simulation:  U.S. Geological Survey Techniques of Water-Resources Investigations, book 3, chap. B8, 30 p.
https://water.usgs.gov/pubs/twri/twri-3_B8/<http://water.usgs.gov/pubs/twri/twri-3_B8/>

Reilly, T.E., and Harbaugh, A.W., 2004 , Guidelines for evaluating ground-water flow models: U.S. Geological Survey Scientific Investigations Report 2004-5038, 30 p.
https://pubs.usgs.gov/sir/2004/5038/

Free books on Groundwater: https://gw-project.org/books/

"Codes only live if somebody loves them." Matt Tonkin, June 2, 2015, MODFLOW and More 2015 Conference Panel Discussion.

"When you started to have that problem, when you couldn't get a solution, you could get help with that. You could not get any help if you had a conceptual screw-up in your understanding of the regional hydrology. If you didn't have a rough idea of what the evapotranspiration was, of what the big streams were doing, and how the stream flow was related to groundwater, there's where you could get into trouble where nobody else could help you." Gordon Bennett in an interview, Feb. 21, 2019.

________________________________
From: mjr-deltares ***@***.***>
Sent: Thursday, July 13, 2023 1:44 PM
To: MODFLOW-USGS/modflow6 ***@***.***>
Cc: Winston, Richard B ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MODFLOW-USGS/modflow6] Allow the user to set the validate mode (isim_mode) when calling the bmi function "initialize" (Issue #1291)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi @rbwinst-usgs<https://github.com/rbwinst-usgs> , I think we can disclose that option through the API one way or another. Will add this to the list of features to work on. Feel free to discuss details on this or other functionality you might need for your use case on our regular development meeting.
