### ISSUE TITLE
Crash in GwfGwtExchange.F90

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#1293]
Hi,

I've found a bug inside \src\Exchange\GwfGwtExchange.f90 (line 381 ff).
This only occurs for models with more than one exchanges of that type.

The original source looks like that:

            areEqual = all(gwfEx%nodem1 == gwtConn%prim_exchange%nodem1)
            areEqual = areEqual .and. &
                       all(gwfEx%nodem2 == gwtConn%prim_exchange%nodem2)

But you forgot to compare the number of nodes for both models before the all(), which crashes if they are not equal.
This is my proposal as a replacement for the code above:

            areEqual = SIZE(gwfEx%nodem1)==SIZE(gwtConn%prim_exchange%nodem1)
            if (areEqual) areEqual = all(gwfEx%nodem1 == gwtConn%prim_exchange%nodem1)
            if (areEqual) areEqual = all(gwfEx%nodem2 == gwtConn%prim_exchange%nodem2)

Additionally I had to change the way you deal with areEqual, because Fortran per default doesn't use
short-circuit evaluation, meaning that 'areEqual.and.' still evaluates the second part leading to a crash anyway.
Changing to an 'if (areEqual)' instead did the job.

Best regards
Andreas

**Comment by langevin-usgs** [comment]
Thank you for this @tandreasr. Many of us are out of the office this week and next, but we will take a look soon and get this fixed.
