### ISSUE TITLE
Question regarding errors in parallel mode

### ISSUE THREAD

**Issue by AndreasRIHU** [MODFLOW-USGS/modflow6#1308]
Hi,
I'm currently testing the parallel mode of Modflow6 and got it running quite well.
But with some projects I do get crashes.
Do you want me to post those crashes here inside an issue or (due to the still alpha state) do you prefer to be contacted directly
and if so: whom should I contact?
Best regards
Andreas

**Comment by jdhughes-usgs** [comment]
Hi @AndreasRIHU I think it would be good for you to post an issue for problems you encounter with the parallel functionality. It would be good if you also added the parallel label to the issue.

**Comment by AndreasRIHU** [comment]
Hi
thanks for clarifying.

Here is my problem with the parallel build:

I tried to build the parallel version of Modflow6 under Win11 and WSL2 Ubuntu (22.04) trying both gcc/gfortran 11.3 and 9.5 with the very same result. I also tried the master vs. the develop branch without any difference.

Here are all the steps taken:

     Meson install:
       sudo apt install build-essential
       sudo apt install python3-pip
       sudo apt install openmpi-bin
       pip3 install --user meson     (for these 2 I had to use pip3 because the version provided by apt was <1.1.0 required by MF6)
       pip3 install --user ninja

     Petsc build
       curl -O https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.18.5.tar.gz (I've tried 18.2, 18.3 and 19.3 as well)
       tar -xzvf petsc-3.18.5.tar.gz
       rem *.gz
       cd petsc-3.18.5
       ./configure --download-openmpi --download-fblaslapack
       make PETSC_DIR=/home/arost/petsc-3.18.5 PETSC_ARCH=arch-linux-c-debug all
       make PETSC_DIR=/home/arost/petsc-3.18.5 PETSC_ARCH=arch-linux-c-debug check
       in ~/.bashrc (first line):
         export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/petsc-3.18.5/arch-linux-c-debug/lib/"
         export PKG_CONFIG_PATH=$HOME/petsc-3.18.5/arch-linux-c-debug/lib/pkgconfig

     Modflow6 build in ~/:
       git clone -b master --single-branch https://github.com/MODFLOW-USGS/modflow6.git  (tried latest develop as well)
       cd modflow6
       mkdir build
       PATH=~/.local/bin:$PATH
       meson setup build -Ddebug=false -Dparallel=true --prefix=$(pwd) --libdir=bin --reconfigure
       meson install -C build
       meson test --verbose --no-rebuild -C build

All worked fine all the way to the very last line, from which 4 out off 5 tests fail (logfile attached)
Does anyone has any idea what's wrong with the above approach or are there still bugs for building under WSL2?

Here are the test outputs:

[__test.zip](https://github.com/MODFLOW-USGS/modflow6/files/12196832/__test.zip)

Thanks and best regards
Andreas

**Comment by langevin-usgs** [comment]
Hi Andreas, I can't tell from your log file what the problem is, but I can tell you that we've had good luck building on WSL.  We have a set of instructions [here](https://github.com/jdhughes-usgs/parallel-modflow6-class/blob/main/wsl_setup.md), which might be helpful for you.  I'm guessing they are pretty similar to what you did, but we are using the the conda-forge channel (and conda) rather than pip.

**Comment by jdhughes-usgs** [comment]
can you run `mpiexec -n 2 ./mf6 -v -p` from the `bin` directory?

**Comment by AndreasRIHU** [comment]
mpiexec -n 2 ./mf6 -v -p

leads to exactly the same error:

[DESKTOP-SFJNUGB:00465] *** Process received signal ***
[DESKTOP-SFJNUGB:00465] Signal: Segmentation fault (11)
[DESKTOP-SFJNUGB:00465] Signal code: Address not mapped (1)
[DESKTOP-SFJNUGB:00465] Failing at address: (nil)
[DESKTOP-SFJNUGB:00465] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fe67d74b520]
[DESKTOP-SFJNUGB:00465] *** End of error message ***
Segmentation fault

I'm going to try Chris' suggestion now.

Best regards
Andreas

**Comment by AndreasRIHU** [comment]
Hi Chris,

I've just folowed the steps you send me.
I had to use 
  Miniconda3-py39_23.5.2-0-Linux-x86_64.sh
instead of
  Miniconda3-latest-Linux-x86_64.sh
because the latter wouldn't run due to a md5 checksum error.

Besides of that the errors during the final testing phase persist.
Any other ideas?

Best regards
Andreas

**Comment by AndreasRIHU** [comment]
Hi Chris,
me again - I've overlooked, that the build process still took the Petsc version, which I compiled before.
After removing that one and starting from
   conda env create
again, now all works as expected without any errors.
Thanks for helping!
Best regards
Andreas
