### ISSUE TITLE
Parallel error (WSL2) with CSV_INNER_OUTPUT

### ISSUE THREAD

**Issue by AndreasRIHU** [MODFLOW-USGS/modflow6#1318]
Another problem in MPI mode is the above mentioned option inside IMS package.
When specified, it crashes mf6 somewhere in Petsc (regardless of the model used)
Best regards
Andreas

**Comment by jdhughes-usgs** [comment]
This is a known limitation of the parallel version. Linear solver output when using PETSc has only received limited effort.

**Comment by mjr-deltares** [comment]
Hi @AndreasRIHU, the refactoring of the Numerical Solution and full integration of the PETSc solver is on the list for this year. (I should mention that the work load is challenging though, so it might not make it into the next release)
