### ISSUE TITLE
Improve time series input efficiency for large models

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#1338]
When specifying time series variable for a large number of cells, MF6 takes a very long time to initialize the input. This makes the time series feature not applicable for large models. In my example run times are **30 seconds** vs **30 minutes** for the same model with and without time series inputs.

Not sure if it is the problem of my model or MF6, or version specific (`MF 6.4.2 06/28/2023`). If it is MF6, is it possible to improve it?

**Comment by langevin-usgs** [comment]
Thank you for this, @ougx.  This is definitely an issue, and we have seen the problem with some of our own testing.  It has to do with how we look up the time series name.

**Comment by langevin-usgs** [comment]
This should be fixed with #1649.  Please reopen if that's not the case.
