### ISSUE TITLE
Bug in exporting viscosity file.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1342]
**Describe the bug**
When a viscosity file is written, the description is recorded as '         VISCOSI' instead of '       VISCOSITY'

**To reproduce**
Activate the "  VISCOSITY FILEOUT " option in the Viscosity package and run the model. Then check the description of the data in the file.

**Expected behavior**
The description of the data should be '       VISCOSITY'.

 ** Cause**
In the viscosity package source code, '         VISCOSITY' has 18 characters instead of 16.

        call this%dis%record_array(this%visc, this%iout, iprint, ibinun, &
                                   '         VISCOSITY', cdatafmp, nvaluesp, &
                                   nwidthp, editdesc, dinact)

**Comment by emorway-usgs** [comment]
Thanks for pointing this issue out, @rbwinst-usgs
