### ISSUE TITLE
Source directory in Makefile 

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#1373]
The path for `SOURCEDIRX` uses back slash `\`. It wont work in Linux. I assume this was created using pymake in Windows. But usually makefile is used when compiling in other OS.

**Comment by wpbonelli** [comment]
Hi @ougx makefiles are tested in CI on [Mac](https://github.com/MODFLOW-USGS/modflow6/actions/runs/6339142276/job/17217882280#step:16:36) and [Linux](https://github.com/MODFLOW-USGS/modflow6/actions/runs/6339142276/job/17217878753#step:16:36). They should work on both. The path separators all look to be forward slash `/`, maybe you are looking at the `VPATH` assignment, which is split over multiple lines with backslashes?

**Comment by ougx** [comment]
Ahh, probably these were changed when packing into release version. The files I looked at were from the release zip and they were back slash.

**Comment by wpbonelli** [comment]
> Ahh, probably these were changed when packing into release version

Yep, they are regenerated for the release. Note that on Windows they can only be used with GNU fortran, not Intel fortran.
