### ISSUE TITLE
PRT with quadtree and voronoi grids

### ISSUE THREAD

**Issue by rhugman** [MODFLOW-USGS/modflow6#1434]
In regard to #1389. I've been experimenting with PRT in @aprovost-usgs 's fork and hit (what I think are) a few bugs for DISV grids. 

This is for a case with high conductivity in a few cells, lots of layers and pass-through cells in some of them (idomain==-1). I have not been able to generate a synthetic case that replicates the issue. Can provide versions of the model files if it helps.

**Describe the bug**

With a GRIDGEN generated quadtree grid, some particle locations (x,y) are recorded outside the model domain for some tstps, but then "bounce" back. The simulation completes successfully: 
![image](https://github.com/MODFLOW-USGS/modflow6/assets/60137311/de356f8d-bb54-48a5-b732-386f3535d984)

Same model, but using a Voronoi grid, MF6 crashes with the following error message:

![image](https://github.com/MODFLOW-USGS/modflow6/assets/60137311/297d07c5-824f-4385-a02a-0a16fb44cb9d)

If using ATS, this message is printed to the command line, then eventually crashes with the same issue above:

![image](https://github.com/MODFLOW-USGS/modflow6/assets/60137311/b5107703-c0f4-4465-81f0-29cd1bd1fe2d)

**Environment**
 - Windows11
 - VERSION 6.5.0.dev0+prt (preliminary) 10/07/2023
 - MODFLOW 6 compiled Oct 07 2023 02:19:02 with Intel(R) Fortran Intel(R) 64
   Compiler Classic for applications running on Intel(R) 64, Version 2021.7.0
                             Build 20220726_000000

**Comment by aprovost-usgs** [comment]
@rhugman Thank you for your interest in PRT and for reporting the issue. We believe the problems stem from the fact that the PRT tracking algorithm is not currently formulated to handle adjacent cell faces that meet at a 180-degree angle, and this is exactly the situation that arises from quadtree refinement, as well as (somewhat surprisingly) in Voronoi grids generated by flopy. (We'll update the description in #1389 to be more explicit about that.)  We believe we have a solution to that limitation of PRT and are planning to update the algorithm prior to release, but we're in the early stages of that effort. Thanks for offering to provide your model files - they might be helpful for testing once we get the algorithm updated. Please feel free to email me directly at aprovost@usgs.gov, and we can arrange for an efficient transfer of the files.

**Comment by rhugman** [comment]
thanks @aprovost-usgs; I'll be in touch via email.

**Comment by aprovost-usgs** [comment]
@rhugman Thank you

**Comment by langevin-usgs** [comment]
Am closing this as it is being handled separately.
