### ISSUE TITLE
Incorrect flow term label written to MAW binary budget file.

### ISSUE THREAD

**Issue by RichardWinston** [MODFLOW-USGS/modflow6#1442]
**Describe the bug**
In table 52 (as of 11/22/2024; formerly table 40 when this issue was originally opened) of `mf6io.pdf`, it says that the last term written to the MVR budget file is `FW-RATE-TO-MVR` but the actual label written for this term is `CONSTANT-TO-MVR`.

**Comment by emorway-usgs** [comment]
I started looking into this by creating a new test problem; it seems there's a bit more going on that first anticipated.  Will chat with the lead developers to try and figure out what's needed.

**Comment by emorway-usgs** [comment]
@langevin-usgs, if #2069 looks good, I think that'll resolve this issue.
