### ISSUE TITLE
The latest MF6 won't read multilayer binary initial head file correctly

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#1477]
For a DIS grid, `STRT` is read as `DOUBLE1D` which will skip headers of lower layers in the HDS file. `6.4.2` works fine.

**Comment by mjreno** [comment]
Hi @ougx, IC input processing was changed in [this](https://github.com/MODFLOW-USGS/modflow6/commit/1b220d470ccf1f52781b6c23751d9308b7ab9d0a) commit, earlier versions might be ok.  If possible can you provide an example input file that will cause the problem?  Thanks for reporting!
