### ISSUE TITLE
MF6 REWETTING OPTION

### ISSUE THREAD

**Issue by ArMOdr** [MODFLOW-USGS/modflow6#1495]
I am trying to applying rewetting option to the MF6 NPF package. However , MF6 comes up with this error:

ERROR REPORT:

  1. File unit 1009: Error converting "IWETIT" to a real number in following
     line:
  2. REWET WETFCT IWETIT 1 IHDWET 0

It seems like it is reading a flag instead of the actual number. 

This is how I have included in the NPF package:

# NPF package
 BEGIN OPTIONS
  REWET WETFCT IWETIT 1 IHDWET 0
 END OPTIONS

This is really no example file or much information in MF6 manual about rewetting. 

Any help with this issue would be appreciated.

**Comment by mjreno** [comment]
Hi @ArMOdr what version of Modflow 6 are you using?  There is information about this option in the mf6io pdf document that accompanies each build and release.  According to that document, it looks like the keyword "WETFCT" is expecting a numeric argument- I think that when "IWETIT" is read instead that this causes the error.

**Comment by ArMOdr** [comment]
I am using the latest release. This is what the manual says:

REWET—activates model rewetting. Rewetting is off by default.
wetfct—is a keyword and factor that is included in the calculation of the head that is initially established at a cell
when that cell is converted from dry to wet.
iwetit—is a keyword and iteration interval for attempting to wet cells. Wetting is attempted every IWETIT iteration.
This applies to outer iterations and not inner iterations. If IWETIT is specified as zero or less, then the
value is changed to 1.
ihdwet—is a keyword and integer flag that determines which equation is used to define the initial head at cells
that become wet. If IHDWET is 0, h = BOT + WETFCT (hm - BOT). If IHDWET is not 0, h = BOT + WETFCT
(THRESH).


I tried this:

BEGIN OPTIONS
   REWET WETFCT 1 IWETIT 1 IHDWET 0
 END OPTIONS

Gives me a different error:

ERROR REPORT:

  1. Error in GRIDDATA block: WETDRY not found.

**Comment by mjreno** [comment]
Hi @ArMOdr in the same document and section the NPF GRIDDATA block is described.  The description for the parameter WETDRY includes the comment: WETDRY must be specified if “REWET” is specified in the OPTIONS block.

Have you defined WETDRY in the GRIDDATA block?
