### ISSUE TITLE
Incorrect documentation of spcsetting in SPC file

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1498]
**Describe the bug**
The description of spcsetting for Stress Package Concentrations (SPC) in mf6io.pdf is as follows.
spcsetting—line of information that is parsed into a keyword and values. Keyword values that can be used to
start the MAWSETTING string include: CONCENTRATION.

I think "MAWSETTING" should have been "spcsetting".

**Comment by emorway-usgs** [comment]
Hello @rbwinst-usgs, Are you still seeing this even after pulling all the latest PRs?  I think this was addressed by #1475 ([see change that was made here](https://github.com/MODFLOW-USGS/modflow6/pull/1475/files)).  If you recently pulled all the latest and you're still seeing this issue in mf6io.pdf, then I probably missed another instance of the typo.

**Comment by rbwinst-usgs** [comment]
You are correct. It appears to already be fixed in utl-spc.dfn.
