### ISSUE TITLE
Supporting time varying streambed hydraulic conductivity in SFR

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#1519]
Is it possible to simulate time-varying SFR conductance in MF6? I don't see there is an option in the documentation. I noticed this PR #768 but it doesn't seem to apply to SFR.

**Comment by emorway-usgs** [comment]
I'm wondering if you meant time varying streambed hydraulic conductivity (parameter name `rhk` [in SFR](https://modflow6.readthedocs.io/en/latest/_mf6io/gwf-sfr.html#:~:text=greater%20than%20zero.-,rhk,-real%20value%20that))?  Conductance will vary as wetted streambed area changes if you're using the n-point x-section option, for example.  Currently there is not support for varying `rhk` through time. 

Depending on @langevin-usgs's thoughts, perhaps this feature could be considered for addition to the **Requested Features** list on the [wiki](https://github.com/MODFLOW-USGS/modflow6/wiki).

**Comment by ougx** [comment]
Thanks, @emorway-usgs. That's correct. We want to apply a time varying multiplier factor to the conductance like in MF 5's `Condfact` parameter. I am thinking some kind of `AUXMULTNAME` option. Or add the option of `sfrsetting` for `rhk`, `rbth` or `rwid` or `rlen`.

**Comment by langevin-usgs** [comment]
When we first wrote the SFR Package in MODFLOW 6 we tried to limit the number of adjustable parameters, especially related to how a stream network might change over time.  There is the option to activate and deactivate reaches, so you can do what you want now, but it would require a complex turning on and off of reaches with different rhk values.  Recognizing that this may not be the best approach for gradual changes to rhk, I think we could consider adding support for time-varying rhk in a future release.  We are in the process of implementing a new "input data model" approach for reading the advanced packages, such as SFR, so I think waiting until after that is completed would make most sense.

**Comment by langevin-usgs** [comment]
BEDK is now supported as a sfrsetting.  Close with #1747.
