### ISSUE TITLE
Time-variant materials (TVM) package

### ISSUE THREAD

**Issue by damianmerrick** [MODFLOW-USGS/modflow6#170]
Several people have expressed an interest in having a package implemented in MODFLOW-6 that allows groundwater flow cell material properties to change over time, similar to the TVM package in MODFLOW-USG. This is of particular benefit for mining models, and the lack of this functionality is currently a barrier to adoption of MF6 for many modellers in this domain.

I am interested in developing such a package for MF6, and would appreciate any comments on what would make this acceptable for inclusion in the main code repository rather than solely as an independent side effort.

For reference, I have attached my latest documentation from the USG-Transport version of TVM.

[TVM v2_TransientTransport.pdf](https://github.com/MODFLOW-USGS/modflow6/files/3316442/TVM.v2_TransientTransport.pdf)

Initial thoughts are to adopt a similar approach whereby the input data for host K and S fields are left untouched and a separate input file is used to specify either changed property values or value multipliers at specified cells on a per-stress period basis.

A couple of considerations have been noted in a brief initial discussion with @langevin-usgs :

- There are related tools, such as GWWebFlow and Flopy, that may rely on static hydraulic conductivity and storage fields. Will these need modification to work with (a) existing non-TVM models and (b) new models which make use of TVM?

- XT3D compatibility with a changing K field.

**Comment by masterdrigo** [comment]
I am one of those users that cannot switch to MF-6 because I use TVM along with TIB with the ATS option of the OC package in MF-USG for most, if not all of my models. Hopefully this request can be developed!
Cheers.

**Comment by prashanth31** [comment]
This would be a nice addition and would be helpful for evaluating mining sites where tailings properties change with time.

**Comment by langevin-usgs** [comment]
Implemented in https://github.com/MODFLOW-USGS/modflow6/commit/45facbe487f257c5a02ea56a339eb25d1ce19c15
