### ISSUE TITLE
GW seepage and drain discharge separation

### ISSUE THREAD

**Issue by elappala** [MODFLOW-USGS/modflow6#1706]
A lot of my models are used to evaluate irrigation of treated wastewater effluent on sprayfieds.  One of the state Non-discharge Rule requirements is that the watertable has to remain at least 1 foot below land surface under all climatic ands irrigation conditions.  Using the areas where seepage occurs is the fastest way for me ti estimate this for project scoping purposes.  Otherwise I have to model the watertable elevations and subtract it from the land surface and map it, which I do for the final permitting of projects. 
I am able to model seepage to the surface and to drains separately in MFNWT but apparently cannot do so in MF6 
So the solution seems to be to have MF6 UZF package include the sumulation of  gw seepage and to write it out to the CBD file fo I can fetch it and map it

**Comment by langevin-usgs** [comment]
Closing this issue.  Feel free to reopen if the suggested solution doesn't work for your case.
