### ISSUE TITLE
CSV_OUTPUT Option in IMS6

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#172]
Hi Chris,

I've got 3 proposals for enhancements regarding the CSV_OUTPUT option.
Background is, that we are using a monitor program to follow the course of all significant convergence criterions in order to be able to detect mal-behaving solutions.
But I think this might be interesting for other users too...

1.) Could you write the CSV after each outer iteration instead of doing it just at the end of each 
     time step for all iterations at once? Or provide a flag to achieve this behaviour optionally?

2.) Is it possible to separate control of solver output to CSV from the one written to the list file.
     Usually you don't need it at both files...
     This could be achieved for example adding either additional options to PRINT_OPTION 
     targetting the CSV only or (better in my opinion) by adding a new CSV_PRINT_OPTION 
     Variable OR always write ALL to CSV independently from PRINT_OPTION specified or not.

3.) Could you output the advanced boundary condition convergence criterions to CSV too?

Thanks in advance
Andreas Rost

**Comment by langevin-usgs** [comment]
Thanks, @tandreasr, we will take a look at this when we start preparation for our next release.  Although information is written to mfsim.lst for each outer iteration, information is only written to the csv file after the outer iteration loop as you noticed.  I know we put some thought into when and how to write this information, so we'll have to look and see whether or not it can be done without causing any side effects.  Thanks for the suggestions.
