### ISSUE TITLE
Crash in parallel (floating divide by zero)

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#1734]
Hi again,

another bug in parallel execution related to the test case attached

Every parallel execution of:

 "...\mf6.5.0.dev2_win64par\bin\mpiexec.exe" -np 2 "...\mf6.5.0.dev2_win64par\bin\mf6.exe" --PARALLEL mfsim.nam

results in "floating divide by zero" in stress period 48.
Even with -np 1 it crashes.
Only the serial call runs flawlessly:

"...\mf6.5.0.dev2_win64par\bin\mf6.exe" mfsim.nam

Tested with latest nightly build on Windows.
[_Parallel Issue.zip](https://github.com/MODFLOW-USGS/modflow6/files/14998579/_Parallel.Issue.zip)

**Comment by jdhughes-usgs** [comment]
@tandreasr IMS includes protections for over solving that is currently not available with PETSC. We are currently working on implementing similar protections with PETSc. A final PR will likely be merged in the next few days.

**Comment by mjr-deltares** [comment]
The PR #1688 went in today. I have tested the new build on your model and it did no longer cause a 'divide by zero' floating point exception. However, there appear to be convergence issues (with IMS as well as PETSc) that will need some attention.
A possible strategy from here would be: try and have the model running and converging properly with IMS, check the results, then just add the flag '-p' to activate the PETSc solver while still running on a single process and see if the results are reproduced. Then finally scale up to multiple cores using mpiexec.

**Comment by tandreasr** [comment]
Hi Martijn,
thank you very much - as for the convergence problems: it was just meant as a test case for the parallel workflow.
