### ISSUE TITLE
`read_value_or_time_series_adv` with 'WITHDRAWAL' vs 'WITHDRAWL'

### ISSUE THREAD

**Issue by mwtoews** [MODFLOW-USGS/modflow6#1749]
There is a potential bug related to a typo here: https://github.com/MODFLOW-USGS/modflow6/blob/f3a4c0c1577617e66d3db049bf7660c8aaf159de/src/Model/GroundWaterFlow/gwf-lak.f90#L3084-L3094

Note the case for the correctly spelled "WITHDRAWAL" term, but `read_value_or_time_series_adv` is called with typo "WITHDRAWL".

**Comment by langevin-usgs** [comment]
Closed with #1748
