### ISSUE TITLE
GWT: active transport area smaller than GWF area results in Exception

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#175]
Hi Chris,
I'm currently fiddling around with the new transport options available in MF6.
One problem regarding those:
Is it currently possible to use a smaller model domain for transport, than for flow.
The GWF & GWT DIS files in my test case are identical except for the idomain, which restricts GWT to a subdomain of GWF (as done before in older MODFLOW/MT3D versions).
But now the test case fails at subroutine fmi_fc()@268, because this%flowerr() has the GWT dimensions, whilst packobj%nodelist() refers to the GWF dimensions.
Attached you find a screenshot illustrating the issue.
Best regards,
Andreas Rost
![Error GWT](https://user-images.githubusercontent.com/13199371/60809182-5e3b1580-a18a-11e9-9ae4-00d32b3a3d3c.jpg)

**Comment by langevin-usgs** [comment]
At the moment the discretization must be identical between the two models.  There is lots that could be done with this in the future, but for now this is the case.  We need to add a check to make sure this is the case and issue an error and terminate if not.
