### ISSUE TITLE
Exception in calcdispellipse()

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#176]
Hi Chris,
Just to inform you about another error:
If you don't specify SAVE_SPECIFIC_DISCHARGE in the NPF package,
the above mentioned routine crashes due to the access to this%fmi%gwfspdis(), which is an invalid pointer in this case...
Best regards,
Andreas Rost

**Comment by langevin-usgs** [comment]
Perfect.  Thanks for letting us know about these issues.  As you are noticing, some of the error checking has not been implemented yet.

**Comment by tandreasr** [comment]
You're welcome :-)

**Comment by langevin-usgs** [comment]
Additional error checking has been added to the transport code.
