### ISSUE TITLE
Exception in xt3d_iallpc()

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#177]
Sorry Chris,

I just read in the docs, that GWF-GWF exchanges currently do not support XT3D.
So you may forget about the error below :-)

Do you have any time frame to implement this for Exchanges too?
I personally think that exchanges are the most important cases for a GNC alternative when porting older rectangular models with refined areas to MF6.
Best regards
Andreas

**Comment by tandreasr** [comment]
The attachment made the text unreadable in the first place - here we go again...

Hi Chris,
me again :-)

I've encountered another error while trying to use the NPF XT3D option.
The code crashes inside above mentioned subroutine @ line 1181
Error XT3D
as illustrated in the attachment.
Obviously inbr1(1) has got an invalid value of 0 resulting in an invalid subrange error when accessing this%icelltype(mm).
My model consists of 3 coupled rectangular DIS grids using exchages.
So do you have any idea what might be wrong or a possible workaround for that?
(besides switching of XT3D of course :-)
Best regards
Andreas

**Comment by tandreasr** [comment]
![Error XT3D](https://user-images.githubusercontent.com/13199371/60950833-35d12980-a2f8-11e9-9fef-1d846c8bb85f.jpg)

**Comment by langevin-usgs** [comment]
@tandreasr, can you make a small test problem that reproduces this error? If so please attach a zip file (excluding model result files) and we can take a look.  XT3D should work within a model even when the model is connected by an exchange with another model.  Also, we are currently evaluating approaches for applying XT3D across models.  There is no time frame yet for when this might be available, so unfortunately, ghost nodes are your only option at the moment.

**Comment by tandreasr** [comment]
Hi Chris,
thanks for your answer.
Unfortunately the test case isn't that small, but I've attached it anyway.
The error occurs right after MF6 starts, so it should be easy to reproduce.
As you might have noticed, it already contains transport models,
so you need the transport fork to run it :-)
Don't hesitate to contact me, if there are further questions.
Best regards,
[__modell_err_with_xt3d.zip](https://github.com/MODFLOW-USGS/modflow6/files/3420348/__modell_err_with_xt3d.zip)

Andreas

**Comment by langevin-usgs** [comment]
I took a quick look at this issue, but I ran into problems right away.  I see dry cells, and that can certainly cause problems.  I shut off xt3d in the flow models and turned off transport, but the model is still having problems.  Will have to close this issue unless we can find a smaller problem that shows the problem.
