### ISSUE TITLE
 nightly build: Error message regression in nightly build (6.5.0.dev2 (preliminary) 05/06/2024)

### ISSUE THREAD

**Issue by pya** [MODFLOW-USGS/modflow6#1774]
The maximum length of  a model name is limited to 16 characters. If the name is too long MF6 shows an error message. This message changed from version 6.4.1 to the current nightly build. I think it is missing valuable information now. I created a model with a too long model name on purpose.

With `mf6: 6.4.1 Release 12/09/2022`, I get:

```
ERROR REPORT:

  1.     ERROR. INVALID MODEL NAME: GWF_NAME___TEN123
  2.     NAME LENGTH OF 17 EXCEEDS MAXIMUM LENGTH OF 16

UNIT ERROR REPORT:

  1. ERROR OCCURRED WHILE READING FILE 'mfsim.nam'
 
```

But with `mf6: 6.5.0.dev2 (preliminary) 05/06/2024`, I get:

```
ERROR REPORT:

  1. Exchange has invalid (unrecognized) model name(s): GWF_NAME___TEN12
     GWT_NAME___TEN12

UNIT ERROR REPORT:

  1. ERROR OCCURRED WHILE READING FILE 'mfsim.nam'
```

The latter message is not as helpful as the older one from version 6.4.1.

I am on macOS arm64 (Sonoma 14.3).

**Comment by mjreno** [comment]
This should be addressed in the MODFLOW 6.5.0 release.  Thanks for reporting @pya!
