### ISSUE TITLE
Detect for multiple FILEOUT entries with the same filename

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1786]
**Describe the bug**
 When running a model containing the MWT package, the following error message is displayed.
ERROR REPORT:

  1. Itemno must be > 0 and <=       0

UNIT ERROR REPORT:

  1. Error occurred while reading file
     'C:\ModelingTools\ModelMuse\PracticeModels\MwtBug2\MwtBug.Chem.mwt'

**To reproduce**
run the attached flow and transport models using RunModel.bat

**Expected behavior**
No error report should be needed for this model.

**Environment**
 - Windows 10
 - MODFLOW 6 nightly build from May 13, 2024.
[MwtBug2.zip](https://github.com/MODFLOW-USGS/modflow6/files/15299576/MwtBug2.zip)

**Comment by langevin-usgs** [comment]
I just ran this model with our develop version, and it seems to run fine.  This is what I see at the end of `mfsim.lst`.

```
 Run end date and time (yyyy/mm/dd hh:mm:ss): 2024/05/15 20:16:05
 Elapsed run time:  1.015 Seconds

WARNING REPORT:

  1. The well bottoms in multi-aquifer well package MAW-1 were reset to the
     bottom of the connected cell 1 times.
 Normal termination of simulation.
```

Can you double check this?  Perhaps you were running with 6.4.4?  Thanks.

**Comment by rbwinst-usgs** [comment]
Yes. I'm sure.
  VERSION 6.5.0.dev2 (preliminary) 05/15/2024
![image](https://github.com/MODFLOW-USGS/modflow6/assets/10761318/442e13d6-5e51-47db-8c6d-3c8937e8b469)

**Comment by langevin-usgs** [comment]
Are you using a different mfsim.nam than the one in the file?  Maybe this batch file swaps it out?

![image](https://github.com/MODFLOW-USGS/modflow6/assets/3372403/fe394ab5-d72c-4c50-b5e7-2b277dc8cb18)

**Comment by langevin-usgs** [comment]
On Mac

![image](https://github.com/MODFLOW-USGS/modflow6/assets/3372403/16477926-f32e-49df-81d9-b5c58f0e15bc)


On Windows

![image](https://github.com/MODFLOW-USGS/modflow6/assets/3372403/747230cd-9c6e-4081-92a3-64c7a50b22f4)

**Comment by rbwinst-usgs** [comment]
The batch file first copies and runs a mfsim.nam file for a flow model and then does the same for a transport model. The error occurs in the transport model.

**Comment by langevin-usgs** [comment]
Looks like the problem is in your MAW input file.  You repeat the "BUDGET FILEOUT" record. I think the second one should be "BUDGETCSV FILEOUT".  The binary data gets written to the CSV file instead of the intended file, so the transport simulation finds an empty budget file for MAW.  We probably shouldn't allow two entries of "BUDGET FILEOUT".  That would have helped.  Might be something for the Input Data Processor at some point, @mjreno?

![image](https://github.com/MODFLOW-USGS/modflow6/assets/3372403/2eb47004-9375-41cc-9f08-2cfdf34fdc4f)

**Comment by rbwinst-usgs** [comment]
You're right. My mistake.

**Comment by mjreno** [comment]
Agree @langevin-usgs.  This type of checking is already being supported for FILEIN tags as certain tags can be read more than once (TS6) but not most.  FILEOUT tags are treated as just a string type currently but we could use the same approach as FILEIN- read them all and throw an error when multiple uses of the tag aren't supported.  It will depend somewhat on upcoming changes to the memory manager- if the memory manager throws an error when a particular mempath is attempted to be allocated more than once that would do it as well.  The IDM solution is dependent on MAW/MWT being updated for IDM.

**Comment by langevin-usgs** [comment]
@mjreno, any additional thoughts on this?  Or maybe we should add a trap in the individual packages themselves?

**Comment by mjreno** [comment]
Let me think through this a bit today @langevin-usgs, maybe there is something we can do pre-release.

**Comment by langevin-usgs** [comment]
Close with #2068
