### ISSUE TITLE
CNC printing to gwt.lst

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#1821]
**Describe the bug**
CNC is printing information to the gwt.lst file. I do not have print_input in the gwt.nam or gwt.cnc. 

gwt.lst:
![image](https://github.com/MODFLOW-USGS/modflow6/assets/25184697/2dee614b-4d89-4768-b5a7-f9e6ccb938f5)

gwt.cnc:
![image](https://github.com/MODFLOW-USGS/modflow6/assets/25184697/b52265e8-9285-4ba3-9160-10463dc46ccf)

This is problem for me because my simulation has has ~35k cnc per kper and I have over 500 kpers (I know this is reflects poor model design... oops), so my lst ends up so huge I can't open it to look at stuff

**Environment**
 - MODFLOW 6 version: 6.4.3

**Comment by mjreno** [comment]
Hi @RyanConway91 I just ran a test in version 6.4.4 and didn't see this issue.  Is it possible to run your model in the most recent version of MODFLOW  6 to verify?

**Comment by langevin-usgs** [comment]
Closing.  Reopen if problem still exists.
