### ISSUE TITLE
PRT model EMS freezes with quadtree disv grid

### ISSUE THREAD

**Issue by robinkeegan** [MODFLOW-USGS/modflow6#1857]
I have a groundwater flow model with a disv quadtree grid generated with gridgen. I am running the PRT model using the cell-by-cell budget and heads files from the groundwater flow model. The PRT model runs to completion if I release the particles where the resulting path line does not pass through any refined cells. However, if I change the release location and the particles encounter a refinement along the flow paths the model gets stuck solving. Interestingly there isn’t a convergence error and it just keeps trying to solve at the current time step, although never getting past the current step. I tried both reducing and increasing the convergence criteria but that didn’t fix the issue. 

I did see this previous issue raised by Rui and was wondering if the limitation around quad tree grids been resolved? If so, does anyone have an idea what could be causing this issue?
https://github.com/MODFLOW-USGS/modflow6/issues/1434#issue-1984711620

I am using MF 6.5.0 on windows 11. 

Thanks

Robin

**Comment by wpbonelli** [comment]
@robinkeegan thanks for reporting this. The issue discussed in #1434 should be resolved, though it's possible you've discovered an edge case or an altogether different bug.

Is the model hanging in an internal time step, or is it the simulation's last? One way this could happen is if your particles are stuck in a cycle in the flow field. By default particles are tracked beyond the end of the simulation until they terminate, as MODPATH would with stop time option 2 (we have discussed changing this in a soon forthcoming release as it can not only hang but can easily eat all the machine's available disk space). Do you see any rows getting added to the track output file when it gets stuck? To rule out this possibility you could also try setting a `STOPTIME` in the PRP package.

If this happens in an internal time step there is something else going on.

**Comment by wpbonelli** [comment]
Another thought: do your refinement levels change abruptly? I.e. do you have shared faces with more than one "extra" vertex, from the perspective of the less-refined cell? We have discussed this situation but we don't have a test case covering it yet.

**Comment by robinkeegan** [comment]
@wpbonelli thankyou for looking into this so quickly. 
The error occurs at stress period 24 timestep 13. There are 140 stress periods and 30 timesteps per stress period so it isn't the last timestep.
The screenshot shows the position of the particle prior to the solver freezing. The track is shaded from white to blue where white is 0 days elapsed and blue is 320 days. It seems like the issue occurs when the particle is moving from cell 24897 to 24902. 

<img width="316" alt="image" src="https://github.com/MODFLOW-USGS/modflow6/assets/33276428/5e5b7142-d623-422e-8fd1-4ee9383aa599">

**Comment by wpbonelli** [comment]
@robinkeegan are you able to share this model? That would help get to the bottom of this quickly. Please feel free to upload here or email to

* wbonelli [at] ucar [dot] edu
* aprovost [at] usgs [dot] gov

If it's under wraps we will need to try to reproduce independently &mdash; in this case any/all info you can provide would help, in particular about the grid. It would be a huge help to see (perhaps just the relevant portion of) the DISV input file.

**Comment by robinkeegan** [comment]
@wpbonelli apologies I can't share the model but I will attempt to put together a similar example at some stage in the next week and will email it through.

**Comment by wpbonelli** [comment]
#1874 fixes a problem which may be related to this issue &mdash; particles encountering sinks were not terminated properly, causing the program to enter an endless loop. @robinkeegan the patch will be included in [tonight's build](https://github.com/MODFLOW-USGS/modflow6-nightly-build)

**Comment by wpbonelli** [comment]
@robinkeegan please reopen if you are still seeing this issue.
