### ISSUE TITLE
Add delimiter option in OBS outputs

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#1864]
It could be preferable to read space delimited file for some programs such as PEST. It will be great that we can add this option in OBS packages.

**Comment by langevin-usgs** [comment]
I'm pretty sure you can write an instruction file for PEST that supports CSV files.  Is this not the case?

**Comment by jtwhite79** [comment]
Example instruction file for two obs and two output times, assuming the csv has a header file:

```
pif ~
l2 ~,~ !obs1_1! ~,~ !obs2_1!
l1 ~,~ !obs1_2! ~,~ !obs2_2!
...
```

(pest and pest++ are both optimized to read large csv files)

**Comment by ougx** [comment]
yes, you can; however you need to specify comma like `~,~` where `~` is the PEST maker. It can become very redundant when there are many obs in one line. It will not breaking anything but it is more convenient like the example below: 

comparing
`l1  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w  w !MR1408452T199308! w !MR1408452T199309! w !MR1408452T199310! w  w  w !MR1408452T199401! w !MR1408452T199402! w !MR1408452T199403!`
vs
``l1  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~  ~,~ !MR1408452T199308! ~,~ !MR1408452T199309! ~,~ !MR1408452T199310! ~,~  ~,~  ~,~ !MR1408452T199401! ~,~ !MR1408452T199402! ~,~ !MR1408452T199403!``

**Comment by langevin-usgs** [comment]
Probably best here to avoid introducing a new option.
