### ISSUE TITLE
gwf3dis BOTM griddata: read_array_dbl3d_all or read_array_dbl3d?

### ISSUE THREAD

**Issue by Huite** [MODFLOW-USGS/modflow6#189]
Hi,

I'm trying to write binary griddata for a Structured Discretization case. In this case, I'm writing both idomain and botm data to a binary file.

From the source, it was pretty straightforward to figure out that a header is required:
```fortran
   ! -- Read the header line from the binary file
    read(locat, iostat=istat, iomsg=ermsgr) kstp, kper, pertim, totim, text, &
      m1, m2, m3
```

I've succesfully written an IDOMAIN griddata file and ran a model with it, with it giving the appropriate results. However, I had it crash on the binary BOTM case. Looking at the code, I'm a little puzzled about the following in https://github.com/MODFLOW-USGS/modflow6/blob/972d598662b519ab3c039891cd49577b4803b3d9/src/Model/GroundWaterFlow/gwf3dis8.f90#L376 

```fortran
          case ('TOP')
            call ReadArray(this%parser%iuactive, this%botm(:,:,0), aname(3), &
                            this%ndim, this%ncol, this%nrow, this%iout, 0)
            lname(3) = .true.
          case ('BOTM')
            call this%parser%GetStringCaps(keyword)
            if (keyword .EQ. 'LAYERED') then
              call ReadArray(this%parser%iuactive, this%botm(:,:,1:this%nlay), &
                              aname(4), this%ndim, this%ncol, this%nrow, &
                              this%nlay, this%iout, 1, this%nlay)
            else
              nvals = this%ncol * this%nrow * this%nlay
              call ReadArray(this%parser%iuactive, this%botm(:, :, 1:this%nlay), &
                              aname(4), this%ndim, nvals, this%iout)
            end if
            lname(4) = .true.
          case ('IDOMAIN')
            call this%parser%GetStringCaps(keyword)
            if (keyword .EQ. 'LAYERED') then
              call ReadArray(this%parser%iuactive, this%idomain, aname(5),    &
                              this%ndim, this%ncol, this%nrow, this%nlay,      &
                              this%iout, 1, this%nlay)
            else
              call ReadArray(this%parser%iuactive, this%idomain, aname(5),    &
                              this%ndim, this%nodesuser, 1, 1, this%iout, 0, 0)
            end if
```

In case of TOP, the ReadArray ends up calling `read_array_dbl2d`, and for IDOMAIN, it uses `read_array_int3d`. However, in case of BOTM, it calls `read_array_dbl1d`, via `read_array_dbl3d_all`. This then results in error, because `nval` is recomputed incorrectly in this case for the three dimensional BOTM array, in  `read_binary_header`, in https://github.com/MODFLOW-USGS/modflow6/blob/972d598662b519ab3c039891cd49577b4803b3d9/src/Utilities/ArrayReaders.f90#L1073 

```fortran
    read(locat, iostat=istat, iomsg=ermsgr) kstp, kper, pertim, totim, text, &
      m1, m2, m3

    ...
    ! -- Assign the number of values that follow the header
    nval = m1 * m2
    !
    ! -- return
    return
```

From the header, the number of columns, rows, and layers is read as m1, m2, and m3; but only m1 and m2 are used to compute the number of values. This obviously results in an insufficient number of floats to fill the complete 3d BOTM array, and modflow errors. 

In this case, it's fixable by multiplying `nval` by `m3`, provided the data is flat. But I don't think that's the right solution. Shouldn't BOTM be read using `read_array_dbl3d` just like IDOMAIN is read by `read_array_int3d` for structured discretization?

In that case, `read_array_dbl2d` is called repeatedly, so it reads in a header after every layer, and my binary griddata should be structured as follows:
```
{header}
{nrow * ncol values}
{header}
{nrow * ncol values}
etc.
```

Instead of:
```
{header}
{nlay * nrow * ncol values}
```

I can provide a (minimum) working example, but this seems like a fairly straightforward case.

**Comment by langevin-usgs** [comment]
We can take a look at this for the next release.  But I guess one quick question is whether or not you have the LAYERED keyword.  If LAYERED is specified, then it should read in bottom by layer with a new header for each 2D grid of data.  If LAYERED is not specified, then it should read a 1D vector of size nlay*nrow*ncol.

**Comment by Huite** [comment]
Right, it being LAYERED or not makes sense, I hadn't properly considered that. My griddata in the `.dis` file doesn't have any LAYERED entries:

```
begin griddata
  delr
    constant 250.0
  delc
    constant 250.0
  top
    open/close mymodel/dis/top.bin (binary)
  botm
    open/close mymodel/dis/bottom.bin (binary)
  idomain
    open/close mymodel/dis/idomain.bin (binary)
end griddata
```

I think there's two changes required, changing the nvals:
```fortran
nval = m1 * m2 * m3
```
instead of:
https://github.com/MODFLOW-USGS/modflow6/blob/972d598662b519ab3c039891cd49577b4803b3d9/src/Utilities/ArrayReaders.f90#L1111
(Although it still ends up getting recomputed? I guess it should check if the `nval`s match.)

And if IDOMAIN isn't layered I think the else branch should look similar to the call for BOTM:
```fortran
 else 
   call ReadArray(this%parser%iuactive, this%idomain(:, :, 1:this%nlay), aname(5),    & 
                   this%ndim, nvals, this%iout) 
```

rather than:
https://github.com/MODFLOW-USGS/modflow6/blob/972d598662b519ab3c039891cd49577b4803b3d9/src/Model/GroundWaterFlow/gwf3dis8.f90#L398-L400

In that case, IDOMAIN will also be read via the ReadArray interface using `read_array_int3d_all` rather than `read_array_int3d`.


Currently a non-LAYERED IDOMAIN is read with the following arguments, calling `read_array_int3d`:
```
iu=this%parser%iuactive = some unit number
iarr=this%idomain = 3 dimensional array
aname=aname(5) = "idomain"
ndim=this%ndim = 3
ncol= this%nodesuser = nlay * nrow * ncol
nrow=1
nlay=1
iout=this%iout = some unit number
k1=0
k2=0
```
Because it's being called with `ncol=this%nodeuser`, it actually fills the IDOMAIN array correctly (since the array just gets reshaped between the subroutine calls).

So it feels (to me) like it's calling the wrong subroutine, but because how ncol, nrow, and nlay arguments are given, it still returns the right result! I'll have a look if my suggestions above break any tests or not.

Anyway, I'm a little wiser! Thanks.

**Comment by langevin-usgs** [comment]
Maybe this is all a little unclear, but I think it's all intentional.   These calls had to be somewhat generalized so that that the overloading works for the different discretization types.  If there is a way to make this all clearer, that would be great.  But I think it has been pretty extensively tested and hopefully should be bug free.

**Comment by langevin-usgs** [comment]
I'm going to close this for now, as I don't think there are any problems here, except perhaps that these methods could be clarified.
