### ISSUE TITLE
IDM time series reading shows incorrect input file as the culprit

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/modflow6#1892]
**Describe the bug**
When the IDM time series reader runs into an error, it submits the correct error message using `store_error()` but there is no subsequent call to terminate the simulation.  The model then proceeds until the next `count_errors()` causes the program to terminate, and wherever that call occurs, it lists that input file as the culprit.

The attached model shows the following error message, which lists `ts01.oc` as the culprit, but the bad input is actually in ts01.wel.  

```
Writing simulation list file: mfsim.lst
 Using Simulation name file: mfsim.nam

    Solving:  Stress period:     1    Time step:     1

ERROR REPORT:


  1. Error in list input. Expected numeric value or time-series name, but
     found 'tswrong'.

UNIT ERROR REPORT:

  1. Error occurred while reading file 'ts01.oc'
```

The following is the well input file that refers to a nonexistent time series record.

```
BEGIN options
  PRINT_INPUT
  PRINT_FLOWS
  TS6  FILEIN  ts01.wel.ts
END options

BEGIN dimensions
  MAXBOUND  2
END dimensions

BEGIN period  1
  1 3 3 ts01
  1 3 3 tswrong
END period  2
```

[test_mf6model_0-ts01_0.zip](https://github.com/user-attachments/files/15932413/test_mf6model_0-ts01_0.zip)

**Comment by mjreno** [comment]
Fixed with #1894.
