### ISSUE TITLE
Improve accuracy of ex-gwt-mt3dsupp82

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1912]
**Is your feature request related to a problem? Please describe.**
In example ex-gwt-mt3dsupp82, the percent discrepancy in the flow model is 0.31. This could be improved.

**Describe the solution you'd like**
Modify the .ims file to improve the accuracy. A suggested .ims file is shown below.

BEGIN options
END options

BEGIN NONLINEAR
END NONLINEAR

BEGIN LINEAR
  INNER_DVCLOSE 1.000000000000E-004
END LINEAR

**Comment by emorway-usgs** [comment]
Updated the FloPy script with No. [221](https://github.com/MODFLOW-USGS/modflow6-examples/pull/221) on the MODFLOW6-examples repo.

**Comment by emorway-usgs** [comment]
closed via PR [221](https://github.com/MODFLOW-USGS/modflow6-examples/pull/221) over on the modflow6-examples repo
