### ISSUE TITLE
Improve the accuracy of ex-gwt-moc3d-p02tg

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1913]
**Is your feature request related to a problem? Please describe.**
In ex-gwt-moc3d-p02tg, the percent discrepancy in the flow model is 0.13. This can be improved by setting INNER_DVCLOSE to 1.000000000000E-004.

**Describe the solution you'd like**
Include INNER_DVCLOSE to 1.000000000000E-004 in the .ims model

BEGIN options
  PRINT_OPTION  summary
END options

BEGIN linear
  INNER_MAXIMUM  300
  LINEAR_ACCELERATION  bicgstab
  INNER_DVCLOSE 1.000000000000E-004
END linear

**Comment by emorway-usgs** [comment]
Confirmed the behavior originally reported by @rbwinst-usgs; namely that the percent discrepancy reported in the flow model was reduced from 0.13 to 0.0 by specifying a closure criterion in the IMS input.  Better to have a perfect flow balance when doing transport!

Closing via [#222](https://github.com/MODFLOW-USGS/modflow6-examples/pull/222) on the [modflow6-examples repo](https://github.com/MODFLOW-USGS/modflow6-examples).
