### ISSUE TITLE
Missing file type for Energy transport name file.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1916]
**Describe the bug**
MVE is not listed as one of the allowed file types in the Energy transport name file.

**To reproduce**
See image

**Expected behavior**
Add MVE as a file type of the Energy transport name file.

**Screenshots**
![image](https://github.com/MODFLOW-USGS/modflow6/assets/10761318/036a5701-482b-4bbf-86d3-4df9a5244445)

**Comment by emorway-usgs** [comment]
closed with #1927
