### ISSUE TITLE
Multiplier auxiliary parameter doesn't work for UZF

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1917]
**Describe the bug**
Using an AUXMULTNAME with the UZF package results MODFLOW stopping with a nonsensical error message.

**To reproduce**
Run the attached model or see the attached mfsim.lst file.

ERROR REPORT:

  1. Total uzf cell area ( 5000.000000000000 ) exceeds the gwf cell area (
     10000.00000000000 ) of cell (1,2,2)              which includes uzf
     cell(s): 1.
  2. Total uzf cell area ( 5000.000000000000 ) exceeds the gwf cell area (
     10000.00000000000 ) of cell (1,2,3)              which includes uzf
     cell(s): 2.
  3. Total uzf cell area ( 5000.000000000000 ) exceeds the gwf cell area (
     10000.00000000000 ) of cell (1,3,2)              which includes uzf
     cell(s): 3.
  4. Total uzf cell area ( 5000.000000000000 ) exceeds the gwf cell area (
     10000.00000000000 ) of cell (1,3,3)              which includes uzf
     cell(s): 4.

UNIT ERROR REPORT:

  1. Error occurred while reading file
     'C:\ModelingTools\ModelMuse\PracticeModel\uzfMultiplier\UzfMultiplier.uzf
     '

**Expected behavior**
The model should run normally

[UzfMultiplier.zip](https://github.com/user-attachments/files/16029773/UzfMultiplier.zip)

**Comment by emorway-usgs** [comment]
Thanks for identifying this issue, @rbwinst-usgs.  Suggested fix submitted with PR #1930.

**Comment by emorway-usgs** [comment]
Closed via #1930
