### ISSUE TITLE
Slow Windows parallel CI tests

### ISSUE THREAD

**Issue by wpbonelli** [MODFLOW-USGS/modflow6#1955]
The parallel mf6 CI tests are taking [~1.5h on Windows](https://github.com/MODFLOW-USGS/modflow6/actions/runs/9959561412/job/27517057814#step:6:1941). Just the tests, not even including setup and build steps. By comparison, on mac they take 1m, on linux 1.5m.

I can't try to reproduce locally at the moment (Windows machine is down)

**Comment by mjr-deltares** [comment]
The fix has been merged. Inclusion of serial tests again in the parallel build is another issue.
