### ISSUE TITLE
typographical error "trcking"

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1976]
**Describe the bug**
In the mf6io.pdf, the following sentence misspells "tracking".
"In this case, FMI reads the simulated head and flows from these files and makes them available to the particle-trcking model."

**Comment by rbwinst-usgs** [comment]
This has already been fixed in the nightly build

**Comment by wpbonelli** [comment]
Closing as this has been fixed.
