### ISSUE TITLE
Release Times file format not specified

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1977]
**Describe the bug**
In PRT models it says 
"RELEASE_TIMESFILE—keyword indicating release times file name will follow
timesfile—name of the release times file. RELEASE_TIMES and RELEASE_TIMESFILE are mutually exclusive."
However, the format of a release times file is not specified and no examples are provided.

**Comment by rbwinst-usgs** [comment]
The TRACK_TIMESFILE format is also undescribed.

**Comment by rbwinst-usgs** [comment]
By experiment, it appears that the release times file must consist of a list of real numbers with one number per line. It isn't clear that the TRACK_TIMESFILE follows the same format because in a test, MODFLOW 6 crashed when I tried that.

**Comment by wpbonelli** [comment]
@rbwinst-usgs the same format should go for `TRACK_TIMESFILE`. The logic to parse the file is identical, or at least ought to be. Could you share the model that produces the crash? I will take a look.

Thanks for putting this through its paces.

**Comment by rbwinst-usgs** [comment]
[modfied_ex-prt-mp7-p03.zip](https://github.com/user-attachments/files/16599107/modfied_ex-prt-mp7-p03.zip)
Here is the example
