### ISSUE TITLE
In PRT model, multiple PRP6 can be specified in the name file

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1978]
**Describe the bug**
In the description of the file types for the PRT model (Table 42) it states "The capability to provide a package name also indicates that the PRT Model can have more than one package of that Ftype." The package name column is empty for all packages indicating that none of the packages can have more than one instance in the name file. However, example ex-prt-mp7-p01 contains two PRP6 files.

**Comment by wpbonelli** [comment]
Multiple PRP packages are indeed supported, they are analogous to particle groups in modpath. I will fix the docs. Thanks @rbwinst-usgs.
