### ISSUE TITLE
PRT fails to account for DRAPE option in MF6 model using Newton Under Relax Option

### ISSUE THREAD

**Issue by javgs-bd** [MODFLOW-USGS/modflow6#2014]
We have been trying to implement PRT in a transient problem where the phreatic surface starts within a lower, relatively impermeable hydrogeological unit, and will raise in time to reach more permeable units. This is caused by a local recharge from the surface that starts at some time within the model simulation.
We use the newton-raphson options to deal with the conversion of layers from dry to partially saturated. We have found that PRT crashes when releasing particles in the initially dry layer, regardles of the DRAPE option, when it should i) terminate the particles instead with ISTATUS 9 according to the docs (particle terminated immediately upon release into a dry cell) or ii) move the particles to the uppermost layer with partial saturation.

**Describe the bug**
When using newton-raphson in the flow model, and particles are released in an initially dry layer, PRT crashes regardless of the DRAPE setting. 

**To reproduce**
In the attached notebook, 
[ex-prt-tr.zip](https://github.com/user-attachments/files/16873587/ex-prt-tr.zip)

1.- Go to the PRP section an uncomment this line, which makes particles to be released in layer 0. The uppermost and initially dry layer.
````# offsets = [(-1,0,0),(-1,-1,0), (-1,1,0), (-1,0,-1), (-1,0,1)]    # particles are released in layer 0````

The PRT simulation should crash with the message in screenshot 1, even when DRAPE is set to True.

2. In the GWF SIM  and GWF Model section comment the following line. To deactivate NR option.
````newtonoptions   = 'NEWTON UNDER_RELAXATION',   ````

The PRT simulation would run to completion, particle trajectories change, but most importantly the flow solution is not the expected one as the upper layer remains dry. DRAPE seems to have been taken effect here.

3. An additional check can be made of activating back the NR option and setting DRAPE to False in the PRP section. The PRT simulation fails again with the same message (screenshot 2),

**Expected behavior**
Particles should be either terminated or moved to the uppermost active layer according to DRAPE

**Screenshots**
![image](https://github.com/user-attachments/assets/6d0f316e-81f4-4698-b836-2ae57ac7d233)
![image](https://github.com/user-attachments/assets/d6414c2a-e6e7-418f-93b2-0c00290e7600)
![image](https://github.com/user-attachments/assets/513ea75f-8597-4a3e-bfd6-11e37a722dfd)

**Environment**
 - Operating system Windows 11
 - MODFLOW 6 version 6.5.0 (screenshot 3)
- Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- flopy version: 3.8.0

**Comment by wpbonelli** [comment]
Thanks for reporting this @javgs-bd. There are at least three separate issues here.

1) The div-0 FPE you are seeing has been fixed by a previous patch. The develop branch / nightly build is not affected by it.

2) There was a bug in the release time selection logic which produced additional/erroneous release times. This is fixed by #2017 which I will merge shortly.

However there is still a crash when newton is enabled and the particles are released from layer 0 (dry). With a layer 0 release, newton off, and drape on, the pathlines look reasonable; with drape off, the particles terminate immediately as expected. So this seems newton-specific. Currently, expected behavior with newton is to pass particles in dry cells instantaneously down to the water table &mdash; this means drape is redundant with newton. For what it's worth, this is not a permanent solution (we are considering more realistic options) but it is consistent with MODPATH 7.

We are digging in and hope to have a fix soon.

@aprovost-usgs please correct me if I got anything wrong here

**Comment by javgs-bd** [comment]
Hi @wpbonelli many thanks for looking into this. I just wanted to leave some comments to give more context on the particular case.

The example we built to report this is mimicking a more complex 3D tailings storage facility seepage model where only contaminant migration released into the initially dry more permeable layers are of interest. We are currently using MP7 because it is working as expected with newton, but we have to unrotate the whole grid for that. We are looking forward to migrate to PRT. I can't check today but I will do tomorrow. I'm almost sure that MP7 removes particles in dry cells when drape is on and the solution is using newton. 

The drape action is critical because it prevents us to model many particles we don't need to. As the phreatic surface is raising, the model time and SP at which it reaches the initially dry layers is dependent on many the model parameters (namely, the hydraulic properties of different layers and tailings recharge rates), which are in turn, uncertain/adjustable parameters within an ensemble of models. We can't anticipate a precise release time, and therefore, removing particles released in dry layers makes a huge different in particle simulation times.

I wonder if leaving the released particles in dry layers with velocity = 0, as long as the head is below the cell bottom, could be an option in PRT. That would be neat (even better than removal via drape) because it would make the simulation require only one initial release. By releasing in many times or SPs, we are only trying to detect when the target layers became saturated and started contaminant movement.

**Comment by javgs-bd** [comment]
Hello @wpbonelli. Apologies for the delay on this. In this notebook we were checking that MP7 was eliminating particles released into dry layers even with newton activated. 
I hope this helps in the process of finding what's going on with PRT. As I commented previously, that v=0 for particles in released dry cells would be a life saver.


[ex-prt-tr 3.zip](https://github.com/user-attachments/files/16982704/ex-prt-tr.3.zip)


![image](https://github.com/user-attachments/assets/4fca7b97-0278-4732-b6a9-1130410c533b)

**Comment by wpbonelli** [comment]
@javgs-bd this model is very useful for debugging. Could we add it (with attribution) to the repo as a test case?

**Comment by wpbonelli** [comment]
Ok, maybe some progress, after some prototyping and discussion with @aprovost-usgs.. Please correct me if anything below is off base. Apologies for the delay on this as well.

As defined, `DRAPE` applies to particles released into inactive cells. To apply it to dry-but-active cells as well would be to depart from MF6.5 and from MP7. A new option to drape in dry cells could work, but we decided instead to keep release-time logic simple and to control behavior in dry cells with tracking-time options.

#2066 adds a `DRY_TRACKING_METHOD` option deciding how dry particles (particles in dry-but-active cells, or above the water table in active, partially saturated cells) behave. The choices are to drop vertically/instantaneously to the water table like in MF6.5, stay in place until the cell wets, or terminate: `DROP`, `STOP`, or `STAY`.  There is more detail in the PR.

With this, here is what I see running your model in a few different configurations. I think `STAY` may be the behavior you are looking for, where particles are active but immobile until the water rises to meet them.

**Newton off, drape on**

![drape_2d](https://github.com/user-attachments/assets/b810ee94-b8da-4ccd-9d23-3c25a4d7918d)
<img width="946" alt="drape_3d" src="https://github.com/user-attachments/assets/93b4fc5a-19f2-4f42-830b-a7e28e457bd6">

**Newton on, dry: drop**

![drop_2d](https://github.com/user-attachments/assets/832cdf61-dc5b-4cc3-a0fa-62ca3b6b51b1)
<img width="777" alt="drop_3d" src="https://github.com/user-attachments/assets/9474e0eb-294a-4fde-a9ea-d6bd60085402">

**Newton on, dry: stay**

![stay_2d](https://github.com/user-attachments/assets/16e2a212-2946-4485-a13c-b13db386ff6c)
<img width="864" alt="stay_3d" src="https://github.com/user-attachments/assets/2181ab72-d858-4d49-a82c-a63f30b3bc87">

With no Newton and no drape, the particles don't go anywhere. Likewise with Newton and dry option `STOP`. So I think to get the behavior you currently have with MP7, with repeated releases and particles terminating when released into a dry cell, you could use `STOP`.

If all this seems reasonable, we can get it into the upcoming 6.6 release.

**Comment by wpbonelli** [comment]
Closed by #2066. Please reopen if needed @javgs-bd

**Comment by javgs-bd** [comment]
Hello all,
I deeply apologize for not replying to this.
I was waiting for some movement on this issue for a long time. It was only after reading the new year’s email about PRT and seeing that the “Vertical Tracking” section was addressing our issue, that I went back to github and saw all the messages. Somehow my outlook was deriving these emails to spam, but not others. Very frustrating.

I greatly appreciate all the USGS team effort put on this, and of course the example model can be used in the repo (although it maybe late for that). No attribution needed at all.

We will be testing the new options asap.
Many thanks again!

Javier

**Comment by wpbonelli** [comment]
No problem @javgs-bd let us know how the new options work for you!
