### ISSUE TITLE
only run ZONBUDGET on specific kstp, kper (s) OR allow for time varying zone arrays

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#2022]
**Is your feature request related to a problem? Please describe.**
I am using zone budget compute the budgets for a complex mine site, where zones change every year for 30 years. Currently, I have it set up where each year is its own ZONEBUDGET run with a zonation based on that mine year. ZONEBUDGET runs the entire .cbb, so I get results where all but one kper are using the wrong zonation. This leads to a lot of wasted compute time and post processing. 

**Describe the solution you'd like**
I would like to be able to only tell ZONEBUDGET to run set of kstp, kpers or allow for time varying zonation. I think the former would be easier to implement and would get me what I need.

**Comment by langevin-usgs** [comment]
I think this is a fairly specialized case that would require additional specialized code.  Unless there is more widespread need for this capability, it seems like the workaround that you are using now is best.  Zonebudget runs very quickly, so it shouldn't be a computational burden.
