### ISSUE TITLE
Floating overflow in IMS

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#2024]
Hi again,
please have a look at the following 2 models,
the first one being test006_2models_mvr_dev from:
    https://github.com/MODFLOW-USGS/modflow6-testmodels/tree/master/mf6
and the second one being derived from it using domain decomposition in order to test MF6's parallel capabilities:
    [_usgs_test006_2models_mvr_dev_wo_backslashs.zip](https://github.com/user-attachments/files/17093108/_usgs_test006_2models_mvr_dev_wo_backslashs.zip)
Here are two preprocessor screenshots of the 2 models
![_Original Testmodell](https://github.com/user-attachments/assets/d426cb62-8493-4a9c-9897-ad9d8c497347)
As you might see, the second model has the original outer parent decomposed into 2 subdomains,
while the inner one was split into 3.
![_Refined with Subdomains](https://github.com/user-attachments/assets/5f5d264a-ff3f-4877-b9fb-65b17c4554e6)
And here is the problem:
Running the original model in serial and parallel converges just fine.
But when running the decomposed model in serial mode, it crashes in IMS (D(n) getting out of double range):
![_Floating overflow in IMS](https://github.com/user-attachments/assets/3a4f91ed-50fe-415e-a9cc-50714984c490)
Running it in parallel with petSC doesn't crash, but produces totally wrong heads.
Could you please have a look into it?
Could there be a problem with too many exchanges laying to close to each other or
exchanges between different models originating from the very same cell (as in row/column 2/3 or 6/5)?
Best regards
Andreas

**Comment by tandreasr** [comment]
Hi,
thanks for having a look into this one as well :-)
Removing the mover from exg_1_5 doesn't change anything.
Additionally I removed exg_1_5 too, but the error still persists.
Best regards
Andreas

**Comment by mjr-deltares** [comment]
Hi, I think you want to check how the exchanges are generated. The solver fails for n=28 which is in parent #2. Looking at its exchanges:

![image](https://github.com/user-attachments/assets/b11b9871-23e2-4954-86b3-779ea9ad9645)

There appear to be double entries, and the 2nd occurrence has cdist equal to zero which doesn't make sense I guess. (Other exchange files show the same pattern)

Let me know if that helps.

**Comment by tandreasr** [comment]
Hi,
I should have seen this... :-(
So thank you very much for clarifying it.
Because I'm on vacation till October 21th, it might take about 3 weeks till I'm able to tell you whether this was the reason.
But as you said: double entries with cdist 0 don't make any sense.
Therefore I'm pretty optimistic about it and you might close the issue for now.
Best regards
Andreas

**Comment by mjr-deltares** [comment]
OK, great

**Comment by tandreasr** [comment]
Hi @mjr-deltares,
now I found time to check on this one again.
The corrected exchanges now produce the correct results in parallel too.
Thanks again for looking into this one.
Best regards
Andreas

**Comment by mjr-deltares** [comment]
Excellent! Thanks for reporting back and good luck with your simulations.
