### ISSUE TITLE
EXG only containing MVR with NEXG 0 doesn't work

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#2025]
Hi,
while further testing the parallel capabilities of MF6 I found another error connected to splitting a model into subdomains.
Please have a look a the following screenshot:
![_screenshot](https://github.com/user-attachments/assets/7fac738e-481a-44df-9e95-3300855db0ca)
The original model without any exchanges contained a Mover between two MAW wells located in Subdomain 3 (provider) and 10 (receiver) respectively.
When splitting the original model (test020_NT_EI from https://github.com/MODFLOW-USGS/modflow6-testmodels/tree/master/mf6)
into subdomains this mover obviously has to be moved into a new exchange (File exg_3_10.exg)
This exchange does contain the mover only, because no direct borders do exist between subdomain 3 and 10 - therefore NEXG 0.
This leads to the following error (serial and parallel mode):

ERROR REPORT:
  1. IDM unimplemented. StructArray::load_deferred_vector unsupported memtype.
 
My guess is that you haven't had such a case yet? (which in my opinion should be acceptible)
What do you think?
Here is the splitted model producing the error:
[_usgs.zip](https://github.com/user-attachments/files/17144244/_usgs.zip)

Best regards
Andreas

**Comment by mjr-deltares** [comment]
Nice find! This is an interesting edge case that we will definitely further investigate. Will let you know what possible next steps are. Thanks for reporting @tandreasr

**Comment by mjr-deltares** [comment]
Thanks @mjreno ! I am working on bringing the fix to completion now in PR #2044. Local tests look promising.

**Comment by mjr-deltares** [comment]
The fix from #2044 went in just now, closing this issue.

**Comment by tandreasr** [comment]
Hi @mjr-deltares,
I've just tested your fixes and Modflow doesn't crash anymore - Thanks!
BUT I think you should reopen that issue because:
Running it with IMS and PetSC in serial mode (just 1 rank) works as expected.
Running it however with multiple MPI ranks (tested 2,3 and 10) produces a totally different iteration behaviour and wrong results.
In case you need my model again, don't hesitate to contact me :-)
Best regards
Andreas

**Comment by tandreasr** [comment]
again me.
You might forget about reopening the issue - the fault was mine :-(
Thank you very much for solving this one!
Andreas

**Comment by mjr-deltares** [comment]
Great, thanks for reporting back to us!
