### ISSUE TITLE
Issues with running model from .bhd file of a previous run

### ISSUE THREAD

**Issue by DStrom1987** [MODFLOW-USGS/modflow6#2034]
I encountered an error while trying to run a model using the initial heads from a previous run. After troubleshooting for some time, I discovered that reverting from the nightly version to version 6.3 resolved the issue, and the model ran without problems. However, when upgrading to version 6.5, the problem reappeared. This, however seemed uncompatible with the latest version of model muse...

I managed to backtrack to a working version that seems compatible with both the most recent version of Model Muse and the initial heads from a previous run. This compatible version is 6.4.2. None of the versions after 6.4.2 work, nor do any of the versions before it, due to reasons that seem related to the latest version of Model Muse.

If anyone could look into this and possibly make a bug fix it would be greatly appreciated.

**Comment by mjr-deltares** [comment]
@ScottBoyce : could you maybe help out with this issue. Where should a Model Muse issue like this be posted?

**Comment by ScottBoyce** [comment]
@mjr-deltares 
Sure, I will check with Richard Winston to see what is going on. I still waiting on my Pascal compiler, so it might be a bit before I can take an in-depth look. (I actually think Richard already addressed this, but I need to double check).

**Comment by rbwinst-usgs** [comment]
I can confirm that this is a bug in MODFLOW 6. I have included a test case.
[TestInitalHeads2.zip](https://github.com/user-attachments/files/17634827/TestInitalHeads2.zip)

**Comment by mjr-deltares** [comment]
Thanks @rbwinst-usgs , we are looking into this and report back shortly

**Comment by langevin-usgs** [comment]
I believe we fixed a bug in MODFLOW 6 in how binary data is read with the open/close binary option.  The text in the io guide indicates:

```
A consequence of the way binary input files have been implemented in MODFLOW 6, simulated dependent variable binary output (for example, head and concentration) cannot be used as binary array input for a model. Instead, simulated dependent variable binary output must be processed and split into separate binary files for each layer or combined into a single array equal to the size of the grid (for DIS grids this would be an array equal to NCOL * NROW * NLAY).
```

The bug was fixed in version 6.4.3 and was labeled with the following entry

```
Improve error message if the size of data read from a binary array file is inconsistent with READARRAY control line and variable description keywords.
```

Not sure this is related to what you are seeing here, but thought I would mention it in case it is relevant.

**Comment by mjreno** [comment]
The io guide text mentioned above by @langevin-usgs is relevant in this case as the binary head file contains 3 separate arrays, one for each layer.  An error should be reported back to the user in this case but it is not being currently handled-  we are currently working to address this.

**Comment by mjreno** [comment]
Updated error handling should now catch this issue and report an unexpected size for the binary input.  Closing this issue for now, thanks for reporting!
