### ISSUE TITLE
Add get_cellxy procedure to DisBaseType

### ISSUE THREAD

**Issue by mjr-deltares** [MODFLOW-USGS/modflow6#204]
For the upcoming interface model, we need to construct a DISU grid from (parts of) grids of any given type. On that grid, we want to be able to run XT3D and we need the cellxy values for that.  These are currently not exposed in DisBaseType.

The proposal is to add an pure virtual procedure get_cellxy(...) to DisBaseType, and implement this in DIS, DISV, DISU. I will provide a PR with the required changes.

**Comment by langevin-usgs** [comment]
@mjr-deltares, what's the status on this?

**Comment by mjr-deltares** [comment]
@langevin-usgs the implementation is finished and (unit) tested locally, I will prepare the PR soon.

**Comment by mjr-deltares** [comment]
PR is #228
