### ISSUE TITLE
Write list budget to csv file(s)

### ISSUE THREAD

**Issue by jtwhite79** [MODFLOW-USGS/modflow6#271]
I know we all enjoy searching through the list file to see the critical and diagnostic info that the global budget provides, but could we consider writing this info to csv files?  Selfishly, this would make it easier parameter estimation processes to track the budget, but also I suspect it would make it easier for users to inspect this information graphically.

**Comment by langevin-usgs** [comment]
You're right.  It's time.  And we've been working to compartmentalize all of the budget processing into a single object and routines, which would make it relatively easy to implement and extend this in a general way.

**Comment by langevin-usgs** [comment]
In the process of adding support for this.  New BUDGETCSV option is being added to Output Control.

![image](https://user-images.githubusercontent.com/3372403/134548153-d3f10d45-7c7a-46be-b562-4d1e1dcad300.png)
