### ISSUE TITLE
NCSUBCELLS not described in CSUB package.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#289]
In the description of icsubno in the CSUB package in mf6io.pdf for MODFLOW 6 version 1.1, a reference is made to NCSUBCELLS but NCSUBCELLS is not described in the document. I suspect that NCSUBCELLS should be ninterbeds in the DIMENSIONS block

**Comment by jdhughes-usgs** [comment]
Closed by https://github.com/MODFLOW-USGS/modflow6/commit/ef46069536b0d4064a7f3b0a0355b9be1ea1ea58
