### ISSUE TITLE
CSUB flow data stored improperly

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#290]
When the 'CSUB-ELASTIC' and 'CSUB-INELASTIC' data is stored in the cell-by-cell flow file in a model using DIS or DISV, NCOL, NROW, and NLAY are not stored properly. It looks like the data is always stored as if the model was a DISU model. This makes reading the data for these two data sets unnecessarily complex.
[CSubIssue.zip](https://github.com/MODFLOW-USGS/modflow6/files/4109422/CSubIssue.zip)

**Comment by jdhughes-usgs** [comment]
These CSUB Package budget data are stored as _imeth=6_ and are of size _NINTERBEDS_ (which may not equal _NCELLS_). _CSUB-CGELASTIC_ and _CSUB-WATERCOMP_ are the only CSUB Package budget terms saved as _imeth=1_. 

I have been able to read the CSUB Package budget data from cell-by-cell files using flopy with out any issues. 

I am updating the "Description of Groundwater Flow (GWF) Model Binary Output Files" section of the "mfio.pdf" document to include a description of the CSUB Package budget data and their associated _imeth_ code. 

Does this resolve your issue?

**Comment by rbwinst-usgs** [comment]
No it does not. It should not be necessary to know the number of rows, columns, and layers in the model before reading the data in order to determine which layer, row, and column the data relates to. For example, the CHD data also uses imeth=6 but it correctly stores the number of rows, columns and layers in the cell-by-cell budget file.

Richard B. Winston
rbwinst@usgs.gov<mailto:rbwinst@usgs.gov>
https://profile.usgs.gov/rbwinst<http://water.usgs.gov/nrp/gwsoftware/>
703-648-5988
on Wednesdays: 301 474-2762
Fax: 703 648-5274

The following are excellent guides especially for beginning modelers.
Reilly, T.E., 2001, System and boundary conceptualization in ground-water flow simulation:  U.S. Geological Survey Techniques of Water-Resources Investigations, book 3, chap. B8, 30 p.
https://water.usgs.gov/pubs/twri/twri-3_B8/<http://water.usgs.gov/pubs/twri/twri-3_B8/>

Reilly, T.E., and Harbaugh, A.W., 2004 , Guidelines for evaluating ground-water flow models: U.S. Geological Survey Scientific Investigations Report 2004-5038, 30 p.
https://pubs.usgs.gov/sir/2004/5038/


"Codes only live if somebody loves them." Matt Tonkin, June 2, 2015, MODFLOW and More 2015 Conference Panel Discussion.

"When you started to have that problem, when you couldn't get a solution, you could get help with that. You could not get any help if you had a conceptual screw-up in your understanding of the regional hydrology. If you didn't have a rough idea of what the evapotranspiration was, of what the big streams were doing, and how the stream flow was related to groundwater, there's where you could get into trouble where nobody else could help you." Gordon Bennett in an interview, Feb. 21, 2019.

________________________________
