### ISSUE TITLE
Some CSUB observations are not calculated.

### ISSUE THREAD

**Issue by RichardWinston** [MODFLOW-USGS/modflow6#302]
With inelastic-compaction and inelastic-csub all results are zero even though COMPACTION_INELASTIC FILEOUT has non-zero values.
[Delay_Bug.zip](https://github.com/MODFLOW-USGS/modflow6/files/4167941/Delay_Bug.zip)

**Comment by jdhughes-usgs** [comment]
For any interbed observation you have to specify `icsubno` or `boundname`. In your example you have specified the `cellid` of the interbed. Any observation without `coarse-` or `-cell` in the Observation Type needs to be specified using `icsubno` or `boundname` (this is described in mfio.pdf).

I modified the inelastic-compaction observations to:

```
BEGIN CONTINUOUS FILEOUT CSub_Delay.inelastic-compaction_ob.csv
 'Well1_2_9_10' inelastic-compaction     300
 'Well2_4_12_7' inelastic-compaction     761
  'test' inelastic-compaction Object13
END CONTINUOUS
```
After doing this I got the same values as those in `COMPACTION_INELASTIC FILEOUT` **(See image below)**.

I also added `inelastic-compaction-cell` and `elastic-compaction-cell` observations to facilitate getting the same information as is in the `COMPACTION_ELASTIC` and `COMPACTION_INELASTIC` binary compaction files.

Let me know if I have missed anything.

![image](https://user-images.githubusercontent.com/2073498/77212473-aeba8f00-6add-11ea-928a-7f066dbd1af6.png)
