### ISSUE TITLE
Inconsistency between PRINT & SAVE HEAD for LAK Package

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#328]
Hi Chris,
another issue regarding the 2 above mentioned Output control options used for Lake stage.
For lakes that are CONSTANT at a certain stress period, PRINT works well when writing to the LST file.
On the other hand SAVE writes DHNOFLO instead of the correct (constant) stage.

My proposal:
at lak_bd() line 4209 check 

  if (this%iboundpak(n) .eq.0) then

instead of

  if (this%iboundpak(n) < 1) then

because for postprocessing purposes it is much more convenient (and consistent to list file output) to have the stage written.

Thanks in advance
Andreas

**Comment by langevin-usgs** [comment]
Yes.  Good suggestion.  We'll make that change.
