### ISSUE TITLE
IDOMAIN capability for DISU

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/modflow6#33]
Need to keep this one on the table.  Strictly speaking, it's not necessary for DISU, but it might make life a lot easier for MODFLOW-USG users.

**Comment by jdhughes-usgs** [comment]
Also requested by Alaistair Black and Sorab Panday

**Comment by langevin-usgs** [comment]
Thinking about how to implement this.  Let's say we have the following case:

![image](https://user-images.githubusercontent.com/3372403/59273030-ea562d80-8c1c-11e9-8d45-602466c44817.png)

Now, what if cell 3 is assigned an IDOMAIN value of -1 (pass through cell)?  We know that 3 is connected upward to 1 and downward to 6, which means we can bypass 3 by connecting 1 to 6 and 6 - 1 using the flow areas of the 3-1 connection and 3-6 connection.  This is straightforward, and we end up with this:

![image](https://user-images.githubusercontent.com/3372403/59273144-212c4380-8c1d-11e9-8f20-0cb80755451c.png)

The new user JA array, as written to the GRB file is:
1 2 4 5 6
2 1 4 6
3
4 1 2 5 6
5 1 4 6
6 1 2 4 5

Note that this connectivity is different from what the user enters (and we have three different connectivity arrays!).  I think we want this behavior as it clearly shows that cell 3 has no connections and that cell 1 is connected to cell 6.  Ideally, we'd just want to use the JA array specified by the user, but we have to add new connections so this isn't really possible.  And this writing of a new JA to the GRB file is how we handle IDOMAIN for DIS and DISV.  The difference here is that the user enters JA for DISU, and the resulting JA array will not be the same, although it will be written to the GRB file.

So now for a complication.  What about this case?

![image](https://user-images.githubusercontent.com/3372403/59273329-95ff7d80-8c1d-11e9-9e18-9ab5199d23df.png)

The user specified JA array is
1 2 3
2 1 3
3 1 2

The challenge here is that if we turn 2 into a pass through cell, we don’t just make a new connection between 1 and 3, because they are already connected.  And, I don't think the code and solver format allows us to have two connections between the same two cells?  I guess in this case, we'd have to add the flow areas so that A13 = A13 + A12.  I'm not sure we'd have to do anything with the CL12 array, except be sure to use the L13 and L31 lengths, and discard the L12 and L21 lengths.

Don't think there are other issues, even for more complicated cases like the one below.  I think once it is all wired up, everything will just work, but the mapping between user nodes and internal node numbers will be tricky, certainly more so than for DIS and DISV.

![image](https://user-images.githubusercontent.com/3372403/59274242-8d0fab80-8c1f-11e9-8945-dacba4781422.png)

**Comment by langevin-usgs** [comment]
This was implemented with #261, but there is no support for negative IDOMAIN values.
