### ISSUE TITLE
Typographical error in DISU error message

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#335]
On line 635 of gwf3disu8.f90, "****ERROR. UNKNOWN **DIS** DIMENSION" should be changed to "****ERROR. UNKNOWN **DISU** DIMENSION"

**Comment by langevin-usgs** [comment]
Closed with https://github.com/MODFLOW-USGS/modflow6/commit/ff705cec5d007784612a867afdf992939b41cd7a
