### ISSUE TITLE
Run Error in a transient model

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#369]
I am building a transient model with more than 1000 stress period. I only try to check running the model with 365 stress period and the model is only running until stress period number 30 then I receive an error.
Error message:
Insufficient virtual memory

I try to change the data in the IMS package to be (complex, under_relaxtion with 'DBD', inner_maximum, outer_maximum, and so on). the model runs till stress period 70 then I receive another error

Error message:
Insufficient memory to allocate Fortran RTL message buffer, message #41

**Comment by MostafaGomaa93** [comment]
I can upload the model files via a link if you need them to check 
but the drag&drop will not work because the files are big

**Comment by langevin-usgs** [comment]
UZF was refactored to handle larger models.
