### ISSUE TITLE
mf6io.pdf - LAK: CTABNAME in LAK not defined

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/modflow6#384]
Moved this comment to modflow6 repo from https://github.com/OGW-USGS/modflow6-docs/issues/4

The definition for `tab6_filename` includes a reference to `CTABNAME `that isn't defined in the mf6io documentation. Not knowing all that is going on under the hood with the tex files, I wonder if the first instance of CTABNAME should instead be something like "The file `tab6_filename` includes the number of entries..."?

![ctabname](https://user-images.githubusercontent.com/3236576/78826449-5a952300-7996-11ea-9356-82572d511bd0.png)

**Comment by jdhughes-usgs** [comment]
@langevin-usgs if you are ok with pull request we should get this in the release after Richard's review.
