### ISSUE TITLE
Add HFB resistance to EXG-package

### ISSUE THREAD

**Issue by VermeulenPTM** [MODFLOW-USGS/modflow6#406]
Hi,

Whenever the HFB package crosses different sub-models, the EXG package need to be able to incorporate a reduction in conductance for those locations. If not, there might be a leakage through the interface of the sub-models.

Now, there might be a work-around to increase the distance to the shared-interfaces, however, this is probably less accurate and robust then include an additional field in the EXG package.

Kind regards,
Peter Vermeulen (Deltares)

**Comment by mjr-deltares** [comment]
Hi @VermeulenPTM , I stumbled upon this very old issue. There is currently no plan to include this feature. Let me know if that causes a problem for you (and we can talk about that offline)
