### ISSUE TITLE
mf6io.pdf - SFR: idv defined twice

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/modflow6#417]
The first occurrence of `idv` appears in the `DIVERSIONS` block of SFR, as shown next:

![first_instance](https://user-images.githubusercontent.com/3236576/80599090-35b52e00-89df-11ea-8897-9182bc731ae0.png)
and is defined in relation to `ndv` appearing in the `PACKAGEDATA` block:

![first_instance_definition](https://user-images.githubusercontent.com/3236576/80599223-74e37f00-89df-11ea-88bc-7569f497707c.png)
So far, so good.  The second occurrence of idv appears in the `PERIOD` block of SFR:
![second_instance](https://user-images.githubusercontent.com/3236576/80600073-ba547c00-89e0-11ea-98f1-7afc206161ac.png)

and is defined:

![second_instance_definition](https://user-images.githubusercontent.com/3236576/80600127-cc361f00-89e0-11ea-8318-e9927b9dc216.png)

However, I don't think the diversion number is the same thing as what is defined in the `DIVERSIONS` block?  For example, a simulation may have 4 different stream reaches that host 1 diversion each, in which case ndv would be set equal to 1 for these 4 reaches and the corresponding idv value would be equal to 1 for all 4 diversions specified in the `DIVERSIONS` block.  However, when one wants to specify the diversion rate in the `PERIOD` block, and needs to reference which diversion they are intending to specify, I think the second instance of `idv` (in the `PERIOD` block) in this example needs to be numbered 1 through 4, where 1 would be the first diversion listed in the `DIVERSIONS` block, 2 would be the second listed diversion, and so on.  Thus, I'll add a clarifying comment to the second definition of `idv`, unless coming up with a distinct variable name for the second instance would be better (and would still bolster the variable's definition)?

**Comment by langevin-usgs** [comment]
![image](https://user-images.githubusercontent.com/3372403/80603278-cf87d580-89f5-11ea-9a9d-5df6ef7aabfa.png)
Don't forget that the sfrsetting is specified for a reach.  So I think in your case idv is 1 for each entry.  No?

**Comment by emorway-usgs** [comment]
@langevin-usgs Thank you for clarifying that.  I've submitted a PR that attempts to add your clarification to mf6io.pdf.  If you don't think it is helpful, or necessary, and lacks the sought after clarity, feel free to close without merging.
