### ISSUE TITLE
Proposal: mode to run mf6 to check model inputs for errors

### ISSUE THREAD

**Issue by alemon-aquaveo** [MODFLOW-USGS/modflow6#426]
I would like an option to run mf6 where it would not solve but would just check the model inputs for errors. I know that mf6 has already implemented many checks on the model inputs. I would find it useful to be able to check a model prior to running the model; this is particularly true for large transient models where the run time can be long.

Thanks for your consideration.

**Comment by jdhughes-usgs** [comment]
We have added a `-m validate` or `-mode validate` command line switch that implements the proposed functionality. It runs through all of the stress periods and time steps in a simulation and reads and check the input for errors but does not assemble, solve, or save/write simulation output. The screen output is change to reflect that validation is being done.

 ```
Run start date and time (yyyy/mm/dd hh:mm:ss): 2020/06/03 12:39:42

 Writing simulation list file: mfsim.lst
 Using Simulation name file: mfsim.nam

 Validating:  Stress period:     1    Time step:     1
 Validating:  Stress period:     2    Time step:     1
 Validating:  Stress period:     2    Time step:     2
 Validating:  Stress period:     2    Time step:     3
 Validating:  Stress period:     2    Time step:     4
 Validating:  Stress period:     2    Time step:     5
 Validating:  Stress period:     2    Time step:     6
 Validating:  Stress period:     2    Time step:     7
 Validating:  Stress period:     2    Time step:     8
 Validating:  Stress period:     2    Time step:     9
 Validating:  Stress period:     2    Time step:    10
 Validating:  Stress period:     3    Time step:     1

 Run end date and time (yyyy/mm/dd hh:mm:ss): 2020/06/03 12:39:44
 Elapsed run time:  2.173 Seconds

```

In `normal` simulation mode this model takes `53.221 Seconds` on my machine.
