### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/modflow6#436]
In running the hypothetical model used with MODSIM (but not yet running MODSIM), I'm noticing that the MF6-only runs are resulting in a memory leak, to the point where my computer crashes.  Do you have a utility in developer studio that can check for leaks?  Here is what task manager is indicating is happening to memory as the model progresses (mf6 is the only application running):
![mem_lk](https://user-images.githubusercontent.com/3236576/81757337-6bdcbe00-9473-11ea-8b73-debaecf9eed0.png)
![mem_lk3](https://user-images.githubusercontent.com/3236576/81757344-7303cc00-9473-11ea-9591-3be05c5b7be5.png)
![mem_lk4](https://user-images.githubusercontent.com/3236576/81757350-77c88000-9473-11ea-8294-18cc787ed508.png)

Prematurely stopping the model before it finishes, memory is restored:
![mem_lk8](https://user-images.githubusercontent.com/3236576/81757413-a8101e80-9473-11ea-9d40-da12921f86c6.png)

Attaching the problem model in case that helps identify the leak.
[modsim.zip](https://github.com/MODFLOW-USGS/modflow6/files/4619106/modsim.zip)

**Comment by langevin-usgs** [comment]
It appears to be in uzf...
