### ISSUE TITLE
UZF inital water content problem

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#453]
when running a model with > 1000 stress periods, the model always stuck and I received a message of insufficient virtual memory (probably due to memory capacity)

So, I split my model of > 1000 stress periods to a set of small models (each has a length of 25 periods), then I export the heads of the last period of set-1 (first 25 periods) to be the initial of the first period of set-2 (second 25 periods) and so on. 

but for initial water contents, the problem is that as I understand, I need to assign only one value/ cell in the UZF package data for initial water content and for exporting water content, I need to specify the depth. the initial water content affects the simulation and I don't know how to solve this !!. how to assign initial water content varied with depth? or if I need to choose only one depth, so which depth is the most representative of the unsaturated zone or how can I know that for my case?

**Comment by langevin-usgs** [comment]
We recently made some fixes to UZF, which should address the memory problems that you were having (#436).  We are planning to make a MODFLOW 6 release in June, which will have these changes.  

If you want to vary the water content with depth, then you need to have multiple model layers, and assign a different UZF object to each cell in the vertical column.  At present, there is no way to specify a variable initial water content with depth for a single cell, although that is something we might consider in the future.

**Comment by MostafaGomaa93** [comment]
Does the mf6.exe run on Linux?

**Comment by langevin-usgs** [comment]
Yes.  You can get the last distribution executable here: https://github.com/MODFLOW-USGS/executables.  Or you can compile it yourself.

**Comment by MostafaGomaa93** [comment]
I run the model on a server with more memory and with Linux system but again it stuck at stress period 595. 
I thought the memory problem can be solved but seems not unless the new MODFLOW 6 release.
