### ISSUE TITLE
Multiplication factor with external data file does not work for stress period data

### ISSUE THREAD

**Issue by tomvansteijn** [MODFLOW-USGS/modflow6#493]
For griddata the user can the define a multiplication factor in combination with the reference to an external file, for example specifying:

```
OPEN/CLOSE  '.\data\kh_l01.dat'  FACTOR  2.0
```

in the NPF package file will multiply the conductivities in the external data file with 2. One could assume that this also works with stress period data, for example in the RCH package:

```
BEGIN period  1
    OPEN/CLOSE  'data\recharge.dat'  FACTOR  0.5
END period  1
```

However in this package the multiplication factor is ignored without warning. Would be nice if multiplication factors could work for stress period data as well, or at least to make clear in the docs that factors can only be specified for time-independent griddata. Using MF6 1.0. 

The multiplication factor does work when using array-based input for the RCH package. I guess the idea is that factors do not work for list-based input.

**Comment by tomvansteijn** [comment]
The multiplication factor does work when using array-based input for the RCH package. I guess the idea is that factors do not work for list-based input.

**Comment by langevin-usgs** [comment]
Hey @tomvansteijn, it is true that the FACTOR keyword does not apply for lists; however, the AUXMULTNAME keyword can be specified for some packages.  When this keyword is specified, and auxiliary variable can be used as a scale factor on the selected column for that particular package.  For the well package, for example, the column to be scaled is the flow rate.  For the drain package, the column to be scaled is conductance.  For each package, the column that will be scaled if AUXMULTNAME is specified, is listed in the mf6io.pdf document.
