### ISSUE TITLE
MODFLOW 6 version 1.1.1 crashes with the attached example

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#494]
MODFLOW 6 version 1.1.1 crashes with the attached model. The following error messages are written to the screen.
[Colarullo2.zip](https://github.com/MODFLOW-USGS/modflow6/files/4866688/Colarullo2.zip)

forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write
Image              PC                Routine            Line        Source             
mf6.exe            00007FF6718E8E74  Unknown               Unknown  Unknown
mf6.exe            00007FF6718E6E8D  Unknown               Unknown  Unknown
mf6.exe            00007FF6716D0E98  BLOCKPARSERMODULE         264  BlockParser.f90
mf6.exe            00007FF6716D0428  BLOCKPARSERMODULE         247  BlockParser.f90
mf6.exe            00007FF6718B9DA4  TIMESERIESMODULE_        1424  TimeSeries.f90
mf6.exe            00007FF6718BB7DF  TIMESERIESMODULE_        1379  TimeSeries.f90
mf6.exe            00007FF6718BBEBE  TIMESERIESFILELIS          48  TimeSeriesFileList.f90
mf6.exe            00007FF6718BCC24  TIMESERIESMANAGER         136  TimeSeriesManager.f90
mf6.exe            00007FF6716D6CA8  BNDMODULE_mp_BND_        1260  BoundaryPackage.f90
mf6.exe            00007FF6716D1495  BNDMODULE_mp_BND_         172  BoundaryPackage.f90
mf6.exe            00007FF671704719  GWFMODULE_mp_GWF_         343  gwf3.f90
mf6.exe            00007FF671864C32  MF6COREMODULE_mp_         210  mf6core.f90
mf6.exe            00007FF6718612EA  MF6COREMODULE_mp_          30  mf6core.f90
mf6.exe            00007FF671861102  MAIN__                      5  mf6.f90
mf6.exe            00007FF6719AC87E  Unknown               Unknown  Unknown
mf6.exe            00007FF6719ACC64  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFC89757974  Unknown               Unknown  Unknown
ntdll.dll          00007FFC89B5A271  Unknown               Unknown  Unknown

**Comment by langevin-usgs** [comment]
This is crashing due to line length issues.  A couple of lines in your time series file are about 2 million characters long, which is much longer than our maximum line length of 5000 characters.  I'm working on implementation of a long line reader, which should be able to handle any size line length.  Stay tuned.
