### ISSUE TITLE
Suggestion for reducing SFR input 

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/modflow6#548]
When entering PERIOD data in SFR, which takes on the form:

_### FOR ANY STRESS PERIOD_
```
BEGIN PERIOD <iper>
<rno> <sfrsetting>
<rno> <sfrsetting>
...
END PERIOD
```
The parameter `sfrsetting` can take on the following values;
```
STATUS <status>
MANNING <manning>
STAGE <stage>
INFLOW <inflow>
RAINFALL <rainfall>
EVAPORATION <evaporation>
RUNOFF <runoff>
DIVERSION <idv> <divflow>
UPSTREAM_FRACTION <upstream_fraction>
AUXILIARY <auxname> <auxval>
```
For transient models with thousands of reaches, the burden for specifying rainfall, runoff, evaporation values can quickly add up.  For example, the input may look something like the following (though thousands of lines longer), where `sw_rain_rate` and `sw_evap_rate` are time series:
![betterway](https://user-images.githubusercontent.com/3236576/90254685-01337980-ddf8-11ea-9bb9-db331ed0c35d.png)

I was thinking it might be an enhancement to allow the user to instead specify a boundname in place of the reach number `rno`, then all reaches associated with that boundname could be provided a `RAINFALL` value with one line.  So for example, if I had a group of reaches with the boundname 'mainRiv', the input could be reduced to the following: 
```
BEGIN period 1
  1       INFLOW      main
  mainRiv RAINFALL    sw_rain_rate
  mainRiv EVAPORATION sw_evap_rate
END period
```
and spare the input size.  I think this would be a nice way to further leverage the boundname functionality.

**Comment by christianlangevin** [comment]
Added to the "Requested Features" list found on the "[MODFLOW Development Plans](https://github.com/MODFLOW-ORG/modflow6/wiki/MODFLOW-Development-Plans)" wiki.
