### ISSUE TITLE
bmi: `get_grid_nodes_per_face` and `test_get_grid_face_nodes` crash on Unix-like systems

### ISSUE THREAD

**Issue by Hofer-Julian** [MODFLOW-USGS/modflow6#566]
@mjr-deltares will pick this issue up at some point

**Comment by mjr-deltares** [comment]
will look at it, currently not top-priority as bmi grid routines are still experimental

**Comment by langevin-usgs** [comment]
Closing for now.  Feel free to reopen if still needed.
