### ISSUE TITLE
error forttl: severe(59) 

### ISSUE THREAD

**Issue by gmcm3011** [MODFLOW-USGS/modflow6#568]
Hi,

Have this error in MODFLOW-2005 VMODFLEX, any ideas?

Error Information: Image              PC                Routine            Line        Source             
Error Information: mf2005(x64).exe    00007FF67D02C5FA  Unknown               Unknown  Unknown
Error Information: forrtl: severe (59): list-directed I/O syntax error, unit 32, file D:\Project\Project V03.data\MODFLOW\NumericalGrid_2\Run2\MODFLOW-2005\XXXXfilename V03.LAK
Error Information: mf2005(x64).exe    00007FF67C486CAF  Unknown               Unknown  Unknown
Error Information: mf2005(x64).exe    00007FF67C4890A5  Unknown               Unknown  Unknown
Error Information: mf2005(x64).exe    00007FF67C4FD165  Unknown               Unknown  Unknown
Error Information: mf2005(x64).exe    00007FF67D0AC806  Unknown               Unknown  Unknown
Error Information: mf2005(x64).exe    00007FF67D0C0884  Unknown               Unknown  Unknown
Error Information: KERNEL32.DLL       00007FFFE4136FD4  Unknown               Unknown  Unknown
Error Information: ntdll.dll          00007FFFE60DCEC1  Unknown               Unknown  Unknown

**Comment by langevin-usgs** [comment]
This is not related to MODFLOW 6.
