### ISSUE TITLE
Error in Newton correction for XT3D when using RHS option

### ISSUE THREAD

**Issue by aprovost-usgs** [MODFLOW-USGS/modflow6#581]
Error in Newton correction for XT3D; qrhs should not be subtracted back out. Affects only simulations that use NEWTON with XT3D RHS.

**Comment by langevin-usgs** [comment]
This was fixed by @aprovost-usgs with https://github.com/MODFLOW-USGS/modflow6/commit/426065992704da81410e0165ff6c9078b9babf37 and released in version 6.2.0.
