### ISSUE TITLE
Newton non-convergence with the CONUS model for MODFLOW > v6.0.4

### ISSUE THREAD

**Issue by verkaik** [MODFLOW-USGS/modflow6#587]
Hi Chris/Joe,

I am testing the CONUS model for Wes and noticed divergence with the latest MODFLOW releases for at least one component model, e.g. model "1403_MF6_SS_Unconfined_250" then can be downloaded from

https://water.usgs.gov/GIS/dsdl/gwmodels/zell2020_wrr/models.14.zip

Somehow the Newton convergence criteria were changed in the code at some point. In NumericalSolution.f90 the solution outer check (sln_outer_check) is not being called anymore prior to evaluating the stopping criteria, which would make this model converge. Now it keeps on iterating forever requiring 2 inner iterations:

bicgstab: oit, iit, bih, bir = 0238, 00014, -2.4578219E-02, 6.6830255E-02
bicgstab: oit, iit, bih, bir = 0253, 00015, -2.5891643E-02, 3.9567035E-02
bicgstab: oit, iit, bih, bir = 0271, 00018, -3.3168159E-02, -2.5331073E-02
bicgstab: oit, iit, bih, bir = 0289, 00018, 9.0400940E-03, 4.7935143E-02
bicgstab: oit, iit, bih, bir = 0308, 00019, -2.5261561E-03, 8.0860946E-03
bicgstab: oit, iit, bih, bir = 0324, 00016, -1.5325797E-02, 4.9414210E-02
bicgstab: oit, iit, bih, bir = 0338, 00014, -6.0745701E-02, 8.5427135E-02
bicgstab: oit, iit, bih, bir = 0354, 00016, -7.2520562E-02, 6.4558215E-02
bicgstab: oit, iit, bih, bir = 0371, 00017, 1.2952670E-02, 9.1672041E-02
bicgstab: oit, iit, bih, bir = 0389, 00018, -4.4477820E-02, 6.4376354E-02
bicgstab: oit, iit, bih, bir = 0404, 00015, -2.7178677E-02, 7.1771286E-02
bicgstab: oit, iit, bih, bir = 0422, 00018, -4.9107034E-02, -4.6880711E-03
bicgstab: oit, iit, bih, bir = 0439, 00017, -2.1769546E-02, -2.3400456E-02
bicgstab: oit, iit, bih, bir = 0456, 00017, -1.3956342E-02, -2.1735352E-02
bicgstab: oit, iit, bih, bir = 0469, 00013, -5.6534793E-02, -8.1181616E-02
bicgstab: oit, iit, bih, bir = 0482, 00013, 4.1620522E-03, 5.1219530E-02
bicgstab: oit, iit, bih, bir = 0493, 00011, -1.8979831E-02, 9.4083704E-02
bicgstab: oit, iit, bih, bir = 0500, 00007, -4.4669554E-02, 3.3300396E-02
bicgstab: oit, iit, bih, bir = 0507, 00007, -1.3987921E-02, 1.4677988E-02
bicgstab: oit, iit, bih, bir = 0512, 00005, -5.9603747E-02, -4.5599442E-02
bicgstab: oit, iit, bih, bir = 0516, 00004, -4.2076267E-02, 5.6293499E-02
bicgstab: oit, iit, bih, bir = 0519, 00003, -7.0533022E-02, 9.0330169E-02
bicgstab: oit, iit, bih, bir = 0522, 00003, -3.7449494E-02, 4.2887144E-02
bicgstab: oit, iit, bih, bir = 0524, 00002, -2.7096957E-02, 4.3362554E-02
bicgstab: oit, iit, bih, bir = 0526, 00002, -8.4174369E-03, 2.3145888E-02
bicgstab: oit, iit, bih, bir = 0528, 00002, -4.3867887E-03, 1.4299861E-02
bicgstab: oit, iit, bih, bir = 0530, 00002, -2.9234153E-03, 9.2811789E-03
bicgstab: oit, iit, bih, bir = 0532, 00002, -1.9262243E-03, 6.0961535E-03
bicgstab: oit, iit, bih, bir = 0534, 00002, -1.2534352E-03, 4.0103914E-03
bicgstab: oit, iit, bih, bir = 0536, 00002, -8.0966234E-04, 2.6277232E-03
bicgstab: oit, iit, bih, bir = 0538, 00002, -5.2162749E-04, 1.7154031E-03
bicgstab: oit, iit, bih, bir = 0540, 00002, -3.3597954E-04, 1.1179344E-03
bicgstab: oit, iit, bih, bir = 0542, 00002, -2.1636055E-04, 7.2847039E-04
bicgstab: oit, iit, bih, bir = 0544, 00002, -1.3937936E-04, 4.7584798E-04
bicgstab: oit, iit, bih, bir = 0546, 00002, -8.9877933E-05, 3.1262910E-04
bicgstab: oit, iit, bih, bir = 0548, 00002, -5.8071313E-05, 2.0745279E-04
bicgstab: oit, iit, bih, bir = 0550, 00002, -3.7672824E-05, 1.3962435E-04
bicgstab: oit, iit, bih, bir = 0552, 00002, -2.4630723E-05, 9.5722469E-05
bicgstab: oit, iit, bih, bir = 0554, 00002, -1.6348815E-05, 6.7176647E-05
bicgstab: oit, iit, bih, bir = 0556, 00002, -1.1141132E-05, 4.8108166E-05
bicgstab: oit, iit, bih, bir = 0558, 00002, -7.8944931E-06, 3.4514218E-05
bicgstab: oit, iit, bih, bir = 0560, 00002, -5.7551842E-06, 2.3309485E-05
bicgstab: oit, iit, bih, bir = 0562, 00002, 4.1893823E-06, 1.2345078E-05
bicgstab: oit, iit, bih, bir = 0564, 00002, 2.4432122E-06, 4.3612422E-06
bicgstab: oit, iit, bih, bir = 0566, 00002, 1.3778313E-06, 2.1062663E-06
bicgstab: oit, iit, bih, bir = 0568, 00002, 7.7870766E-07, 1.3919088E-06
bicgstab: oit, iit, bih, bir = 0570, 00002, 4.6950220E-07, 9.0691316E-07
bicgstab: oit, iit, bih, bir = 0572, 00002, 2.8635191E-07, 5.6893805E-07
bicgstab: oit, iit, bih, bir = 0574, 00002, 1.8038763E-07, 3.5915107E-07
bicgstab: oit, iit, bih, bir = 0576, 00002, 1.1494755E-07, 2.2464816E-07
bicgstab: oit, iit, bih, bir = 0578, 00002, 7.4076745E-08, 1.3961017E-07
bicgstab: oit, iit, bih, bir = 0580, 00002, 4.7821445E-08, 8.5642213E-08
bicgstab: oit, iit, bih, bir = 0582, 00002, 3.0681239E-08, 5.0415736E-08
bicgstab: oit, iit, bih, bir = 0584, 00002, 1.9372953E-08, 2.7716851E-08
bicgstab: oit, iit, bih, bir = 0586, 00002, 1.1927776E-08, -1.3692016E-08
bicgstab: oit, iit, bih, bir = 0588, 00002, 7.2158057E-09, -1.1413969E-08
bicgstab: oit, iit, bih, bir = 0590, 00002, 4.3828883E-09, -9.7720179E-09
etc

Jarno.

**Comment by langevin-usgs** [comment]
Hi Jarno, do you have any more information on what the problem is?  We haven't had any issues that we know about with Newton convergence problems.
________________________________

**Comment by verkaik** [comment]
Hi Chris, did you try to run the model yourself? What I can add to my previous mail is that for MODFLOW > 6.0.4, somehow in NumericalSolution.f90 "abs(this%hncg(kiter)) <= this%dvclose" is not being satisfied, since the call "call this%sln_outer_check(this%hncg(kiter), this%lrch(1,kiter))" prior to that evaluation was removed. HUC1403 (Arches National Park at West and Mt. Wilson at East) is a pretty dry area (low recharge) and has large hillslopes, making this quite a tough model to converge.

**Comment by langevin-usgs** [comment]
This problem converges very easily, quickly, and with a zero mass balance error with simple under-relaxation.  Here is the IMS input file.  It is flip-flopping with complex, but that looks to be real and not because of something in the code.

```
BEGIN OPTIONS
  PRINT_OPTION ALL
END OPTIONS

BEGIN NONLINEAR
  outer_maximum 150
  under_relaxation simple
  under_relaxation_gamma 0.9
END NONLINEAR

BEGIN LINEAR
  inner_maximum 20
  linear_acceleration bicgstab
END LINEAR
```


```
 OUTER ITERATION SUMMARY
 ----------------------------------------------------------------------------------------------------------
                                OUTER      INNER                    STEP   MAXIMUM CHANGE MODEL-(CELLID) OR
 OUTER ITERATION STEP       ITERATION  ITERATION  MAXIMUM CHANGE SUCCESS             MODEL-PACKAGE-(NUMBER)
 ----------------------------------------------------------------------------------------------------------
 Model                              1         20       2797.9598                          1_GWF-(1,784,699)
 Model                              2         20      -2432.4163                          1_GWF-(1,784,699)
 Model                              3         20      -363.52055                          1_GWF-(1,717,350)
 Model                              4         20      -251.68656                           1_GWF-(1,59,196)
 Model                              5         20      -68.377850                          1_GWF-(1,562,228)
 Model                              6         20       123.78048                          1_GWF-(1,334,373)
 Model                              7         20      -124.00203                          1_GWF-(1,337,374)
 Model                              8         20       105.79596                          1_GWF-(1,492,438)
 Model                              9         20      -54.704849                          1_GWF-(1,605,510)
 Model                             10         20       24.405689                          1_GWF-(1,633,520)
 Model                             11         20      -27.606183                          1_GWF-(1,599,505)
 Model                             12         20      -26.035045                          1_GWF-(1,606,505)
 Model                             13         20      -12.636312                          1_GWF-(1,490,436)
 Model                             14         20      -7.9108522                          1_GWF-(1,614,517)
 Model                             15         18      -6.5148646                          1_GWF-(1,610,515)
 Model                             16         10      -1.2195649                          1_GWF-(1,601,510)
 Model                             17          7     -0.16918243                          1_GWF-(1,601,510)
 Model                             18          3 -1.78246596E-02                          1_GWF-(1,601,510)
 Model                             19          3 -2.61009921E-03                          1_GWF-(1,610,515)
 Model                             20          1 -2.26093136E-04       *                  1_GWF-(1,601,510)
 ----------------------------------------------------------------------------------------------------------
```
