### ISSUE TITLE
Proposal: stress period dependent backtracking_tolerance and outer_dvclose

### ISSUE THREAD

**Issue by ckikuchi** [MODFLOW-USGS/modflow6#589]
I have a suggestion/proposal following up on Damian's proposal to incorporate adaptive time stepping. I think that it incorporating stress period dependent backtracking_tolerance, and possibly outer_dvclose would be really helpful for improving the flexibility to work with models that have certain problematic stress periods that need more residual control to get through. For example, simulating seasonal recharge fluctuation with monthly stress periods. Is this something that could be added into future developments for MODFLOW6?
Thank you!
-Colin

**Comment by damianmerrick** [comment]
Good idea. Worth considering per-stress period modification of solver properties in general. Maybe this is doable in the meantime via BMI?

**Comment by langevin-usgs** [comment]
Yes, this is certainly doable in the meantime with BMI.  Here is an example of how you would do it using the Python xmipy wrapper, which can be installed using pip.  

```
import os
from xmipy import XmiWrapper

def bmi_return(success, simulation_folder):
    """
    parse libmf6.so and libmf6.dll stdout file
    """
    fpth = os.path.join(simulation_folder, 'mfsim.stdout')
    return success, open(fpth).readlines()


def run_libmf6(libmf6, simulation_folder=None, **kwargs):
    success = False
    init_wd = os.path.abspath(os.getcwd())
    if simulation_folder is not None:
        os.chdir(simulation_folder)

    mf6_config_file = os.path.join(simulation_folder, 'mfsim.nam')
    try:
        mf6 = XmiWrapper(libmf6)
    except Exception as e:
        print("Failed to load " + libmf6)
        print("with message: " + str(e))
        return bmi_return(success, simulation_folder)

    # initialize the model
    try:
        mf6.initialize(mf6_config_file)
    except:
        return bmi_return(success, simulation_folder)

    # time loop
    current_time = mf6.get_current_time()
    end_time = mf6.get_end_time()

    # get Python pointers to mf6 variables
    tag = mf6.get_var_address("DVCLOSE", "SLN_1")
    outer_dvclose = mf6.get_value_ptr(tag)
    tag = mf6.get_var_address("DVCLOSE", "SLN_1", "IMSLinear")
    inner_dvclose = mf6.get_value_ptr(tag)
    tag = mf6.get_var_address("KPER", "TDIS")
    kper = mf6.get_value_ptr(tag)
    tag = mf6.get_var_address("KSTP", "TDIS")
    kstp = mf6.get_value_ptr(tag)

    outer_dvclose_by_timestep = None
    inner_dvclose_by_timestep = None
    if 'outer_dvclose' in kwargs:
        outer_dvclose_by_timestep = kwargs['outer_dvclose']
    if 'inner_dvclose' in kwargs:
        inner_dvclose_by_timestep = kwargs['inner_dvclose']
    
    # simulation time loop
    idx = 0
    while current_time < end_time:

        # run the time step
        if outer_dvclose_by_timestep is not None:
            val = outer_dvclose_by_timestep[idx]
            outer_dvclose[0] = val
            print('resetting outer_dvclose to {}'.format(outer_dvclose))
        if inner_dvclose_by_timestep is not None:
            val = inner_dvclose_by_timestep[idx]
            inner_dvclose[0] = val
            print('resetting inner_dvclose to {}'.format(inner_dvclose))
        try:
            mf6.update()
        except:
            return bmi_return(success, simulation_folder)
        print("Solved for kper {} and kstp {}".format(kstp, kper))

        # update time
        current_time = mf6.get_current_time()

        # increment counter
        idx += 1

    # cleanup
    try:
        mf6.finalize()
        success = True
    except:
        return bmi_return(success, simulation_folder)

    if simulation_folder is not None:
        os.chdir(init_wd)

    # cleanup and return
    return bmi_return(success, simulation_folder)

# run an example from the mf6 distribution
libmf6 = os.path.abspath('./bin/libmf6.so')
simulation_folder = './ex-gwf-advtidal/'
assert os.path.isfile(libmf6)
assert os.path.isdir(simulation_folder)
# set outer dvclose to 1.e-6 for first time step and 1.e-8 for remaining time steps
outer_dvclose = [1.e-6] + 3 * 120 * [1.e-8]
# set inner dvclose to 1/10 value of outer dvclose
inner_dvclose = [dv / 10 for dv in outer_dvclose]
res = run_libmf6(libmf6, simulation_folder, 
                 outer_dvclose=outer_dvclose,
                 inner_dvclose=inner_dvclose)
```

The run_libmf6() function is a general function that will run any valid MODFLOW 6 model using the libmf6.dll (or libmf6.so on Mac and Linux).  At the moment, the trick is knowing internal MODFLOW 6 variable names and how to access them.  And some variables can be changed, and some can't unless you know what you're doing.  So you can't just change a backtracking variable through BMI if backtracking isn't on for example.  But there are many internal MODFLOW 6 variables that can be modified by the user through BMI.  And the inner and outer dvclose (head change criteria) can be changed, and in this case they are changed by time step.  Bottom line is that BMI gives a lot of flexibility to interact with a running MODFLOW 6 model.  We are continuing to better document this functionality and make this interaction more friendly.

One thing to note here is that the call to mf6.update() executes a full time step.  There are also ways to have finer control over a time step, including the ability to access and make changes to MODFLOW 6 variables at the outer iteration (Picard) level.
