### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by merzto** [MODFLOW-USGS/modflow6#593]
Hi,
I'm trying to run MODFLOW. New installed Win10Pro. I tried modflow6.2.0, 6.1.1, 6.1.0, 6.0.4
Im not shure where I should start troubleshooting. I tried running as admin but I can't open it.

Thanks

Lenovo Thinkpad L15
AMD Ryzen 7 PRO 4750U with Radeon Graphics   1.70 GHz 
Windows 20H2 19042.630

**Comment by langevin-usgs** [comment]
This is not a MODFLOW 6 issue.

**Comment by merzto** [comment]
sorry, I guess github is not for support requests.

I have the manual but I'm struggeling.
Do you know of a form where users turn to for help?
I've got Modflow 5.3 to run so thats alright. The readme of the current
build didn't help much though, I guess I miss a piece of the puzzle.
thanks anyway

Am Di., 24. Nov. 2020 um 16:00 Uhr schrieb langevin-usgs <
notifications@github.com>:
