### ISSUE TITLE
Also provide Intel binaries via oneapi-CI? And via conda-forge?

### ISSUE THREAD

**Issue by Huite** [MODFLOW-USGS/modflow6#611]
I was looking at the modflow6 DLL from the nightly releases, and the following quote struck me:

> Windows executables are statically linked and can be run without gfortran being installed. In order to use the MODFLOW 6 dynamic-link library (libmf6.dll) on Windows, the Mingw-w64 version of gfortran version 8.1.0 will need to be installed locally.

I guess there are good reasons to not statically link for the DLL, but it's a bit inconvenient -- I'm aware gfortran on Windows comes with a set of difficulties. At any rate, it had me wondering, does compiling with Intel compilers solve this? I've read before that Intel provides its compilers for open source development : https://software.intel.com/content/www/us/en/develop/articles/qualify-for-free-software.html 
There are other advantages to the Intel compiled binaries, as they do tend to run a bit faster especially on Intel CPUs.

After a bit of searching, I found this repo:

https://github.com/oneapi-src/oneapi-ci

As it states in the REAMDE, you can use excerpts as necessary. I forked and simplified here, limiting to just windows for brevity: https://github.com/Huite/oneapi-ci
I've edited the batch file a little and it seems to be working as expected:

https://github.com/Huite/oneapi-ci/blob/b9a25f12677219dcc893773d5d61e1fff9146652/scripts/build_windows.bat#L18
```
cd src/fortran
ifort hello.f90 /exe:hello.exe
dir /b
hello.exe
```

Prints (https://github.com/Huite/oneapi-ci/runs/1617643937#step:5:30):

```
hello.obj 
hello.exe
hello.f90
hello.obj
Makefile
Makefile.macos
Makefile.nmake
 Hello, world!
```

The OneAPI release notes mention:

> Intel® Fortran Compiler (Beta) (the “Materials”) are licensed to you under the Free User Type as defined in the enclosed Intel End User License Agreement for Developer Tools (Version October 2020) (“EULA”).

Which can be found here: https://software.intel.com/content/dam/develop/public/us/en/documents/intel-end-user-license-agreement-for-developer-tools-oct-2020.pdf

Ideally, we'd also be able to put this up on conda-forge. I've noticed there is a modflow6 feedstock on conda-forge:

https://anaconda.org/conda-forge/modflow6

https://github.com/conda-forge/modflow6-feedstock

But it doesn't support windows at all -- I guess since it also compiles separately? Haven't looked very carefully yet. At any rate, I personally think a conda feedstock is more important for the DLL than the exe, since general users are well versed with exe's while DLL's are expected to have been set up, so I think a separate libmodflow6 feedstock would be required.

I'm not sure about future plans for this Intel OneAPI, we might not want to rely on it too much, but at this rate it's pretty low effort: Basically copy parts of the of the OneAPI-CI repo to the github actions (and/or the modflow6-nightly-build repo?).

**Comment by langevin-usgs** [comment]
Hi @Huite, thanks for the thoughtful response.  It would be great to use Intel for our nightly builds, but we've been concerned about licensing issues.  The release versions of our executables are all statically built with Intel on our local machines, and so there are no additional Mingw or gfortran requirements.   I'm not following how we could make the Intel compilers available through a Github action, unless that action just triggered builds on a local machine somewhere that had Intel.  Do you see another option?  If so, maybe you could set it up on your test repo?

**Comment by Huite** [comment]
Hi Chris, my message might've rambled on a bit too much. With the Intel OneAPI thing, it's possible to have the Intel Compilers available on the CI machine. The people at Intel have been so kind to show how this can be done with the oneapi-ci repository, giving examples.

So it's exactly the same as the nightly builds, but instead of installing and calling gfortran it (and then uploading), it installs and calls ifort  -- but with the ifort doing some license checking in between. I figure they've got some way of figuring out that it's running on a public CI machine.

In the example above, I could run the ifort for a hello world example on the CI machine. Specifcally, this is the log of that github action:
https://github.com/Huite/oneapi-ci/runs/1617643937#step:5:30

I was indeed thinking of using the test repo to try and build modflow, but wanted to make sure you guys were interested since it does take a little figuring here and there! I'll try and make some progress tomorrow.

With regards to licensing I don't see any issues, the Intel documentation seems clear enough: you're allowed to build open source software with this (and then distribute the resulting binaries). Then again, I Am Not A Lawyer, I'll see if I can get some additional confirmation.

**Comment by langevin-usgs** [comment]
Hey @Huite, that all sounds very promising.  It would be great if you have the time and interest to see if you could get the build working for Win/Mac/Linux as a Github action.  Since we distribute Intel exe's for our official releases, it would sure be nice to distribute something that is consistent for our nightly builds.  So we are definitely interested if you are able to get it working.  If you can get something working on your modflow6 fork and/or could submit a PR, we'd be very interested.  It's a slow week for many of us, so we probably wouldn't move on anything until next week at the earliest, so there is no rush.  Thanks for looking into this!

**Comment by jdhughes-usgs** [comment]
@Huite I would suggest making a copy of https://github.com/MODFLOW-USGS/modflow6/blob/develop/.github/workflows/ci-latest-compilers.yml and substituting gfortran for the intel compiler for each OS. We are using pymake and one autotest to build all of the MODFLOW 6 related applications. So to use the intel compiler will require a little work to our build autotest.

I would suggest the first step be getting the new github action yml to install the intel compilers for each OS and then we can coordinate changes to our build autotest.

**Comment by Huite** [comment]
@jdhughes-usgs Thanks for the pointers, I had made a small start along those lines.
I was rather pleasantly surprised by how easy it is to switch compilers thanks to pymake! So on the whole, it appears to be less work than I had initially thought.

**Comment by langevin-usgs** [comment]
The CI is using intel oneAPI.  Closing.
