### ISSUE TITLE
ssm_sources with open/close

### ISSUE THREAD

**Issue by jtwhite79** [MODFLOW-USGS/modflow6#612]
Awesome work on the transport stuff!  One small thing I've noticed is that if the ssm sources are in an external file, mf6 (develop 6.2.1) doesnt like it.  

This doesnt work:
```
# File generated by Flopy version 3.3.3 on 12/28/2020 at 13:59:29.
BEGIN options
END options

BEGIN sources
    OPEN/CLOSE  'gwt_benchmark.ssm_sources.txt'
END sources
```
"gwt_benchmark.ssm_sources.txt" has one line: `WEL_LOADING  AUX  CONCENTRATION
` and if replace the open/close line with that one line, it runs.

**Comment by langevin-usgs** [comment]
I'm not able to reproduce this problem.  I took one of our examples and moved the contents of sources into a text file and it seems to run fine.  Do you remember the error that you received?  Some of the block reading has been fixed on the develop version, but you indicated that's what you're using.

**Comment by jtwhite79** [comment]
With the latest develop I cant reproduce it either, so user-error strikes again!
