### ISSUE TITLE
missing exponent for really small numbers

### ISSUE THREAD

**Issue by jtwhite79** [MODFLOW-USGS/modflow6#615]
I've only seen this so far in the transport list file mass budget, but if the value is <= 1.0e-100 ( still larger than underflow, but really small), fortran is dropping the "e" so you get things like `1.23-100` - wat?!  I guess this hackery is ok for fortran but python and c(++) dont like it.  For example numpy/numpy#5557 - looks like it can controlled with various output specifier options.  Any chance to mod the list budget routines?  Thanks for the killer work on mf6!

**Comment by langevin-usgs** [comment]
I'll work on a fix this week.  Thought we had rooted out all occurrences of those dropped "Es".  Any chance you have a simple way for me to reproduce this case?

**Comment by jtwhite79** [comment]
I have a model that causes it but lemme see if I can boil it down a little bit.

**Comment by langevin-usgs** [comment]
I just looked through all our tests, and I was able to find an example.  Strange that this has never showed up before (or maybe it has and we just haven't seen it).  The budget writing code is the same whether it's flow or transport, so it's buried in there deep.  Will need to think about how to fix as we probably don't want to change the width of the table.  Thanks for mentioning it!

```
  MASS BUDGET FOR ENTIRE MODEL AT END OF TIME STEP    1, STRESS PERIOD   1
  ---------------------------------------------------------------------------------------------------

     CUMULATIVE MASS      M       RATES FOR THIS TIME STEP      M/T          PACKAGE NAME    
     ------------------                 ------------------------                     ----------------

           IN:                                      IN:
           ---                                      ---
     STORAGE-AQUEOUS =           0.0000       STORAGE-AQUEOUS =           0.0000     MST             
               RCH-1 =         432.0000                 RCH-1 =          43.2000     SSM             
               CHD-1 =           0.0000                 CHD-1 =           0.0000     SSM             
     FLOW-CORRECTION =       3.7325E-10       FLOW-CORRECTION =       3.7325E-11     FMI             

            TOTAL IN =         432.0000              TOTAL IN =          43.2000

          OUT:                                     OUT:
          ----                                     ----
     STORAGE-AQUEOUS =         432.0000       STORAGE-AQUEOUS =          43.2000     MST             
               RCH-1 =           0.0000                 RCH-1 =           0.0000     SSM             
               CHD-1 =       2.1014-102                 CHD-1 =       2.1014-103     SSM             
     FLOW-CORRECTION =       9.6793E-08       FLOW-CORRECTION =       9.6793E-09     FMI             

           TOTAL OUT =         432.0000             TOTAL OUT =          43.2000

            IN - OUT =       1.0454E-07              IN - OUT =       1.0454E-08

 PERCENT DISCREPANCY =           0.00     PERCENT DISCREPANCY =           0.00

```

**Comment by jtwhite79** [comment]
Normally I couldn't careless about such ridic small numbers but it was causing flopy to bail on reading the whole budget record which then cascaded into a heap of pest problems - the whole house of cards collapsed from a 1e-100 mg/l - haha!

**Comment by langevin-usgs** [comment]
I feel like someone was asking for CSV output of those global budget numbers.  And I'm pretty sure that was you!  Might be time to just output those numbers in another form...

**Comment by jtwhite79** [comment]
I was asking for that and it would be sweet as!
