### ISSUE TITLE
Does the Farm Process Package (FMP2) work with MODFLOW 6, or can it be adapted ?

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#618]
I am asking about the possibility of linking the FMP2 package to MODFLOW 6, Is it possible in the meantime?

I am writing a Ph.D. proposal and was thinking to use the FMP2 with MODFLOW 6, but I don't have enough information if it can work or not.

If not, what are the feasible options that can be linked to MODFLOW 6 to simulate the irrigation activities?

**Comment by langevin-usgs** [comment]
The Farm Process Package capabilities are currently under consideration for a future addition to MODFLOW 6.  This is mentioned on the Wiki Page, so we'll close the issue here.
