### ISSUE TITLE
Variable name check in BMI

### ISSUE THREAD

**Issue by mjr-deltares** [MODFLOW-USGS/modflow6#624]
ambitious cleaning made this disappear...

**Comment by langevin-usgs** [comment]
@mjr-deltares, I'm not sure what this means.  Are you able to restore the name check prior to our next release, which will likely be the week of Feb 15?

**Comment by mjr-deltares** [comment]
Yes, working on it right now

**Comment by mjr-deltares** [comment]
There used to be a check whether the BMI variable exists in the memory manager before the pointer was assigned, this then moved to the memory access mechanism, and then we decided to get rid of that access mechanism, thereby unintentionally (my bad) removing the check.
