### ISSUE TITLE
support for reading modflow 6 transport file budgets

### ISSUE THREAD

**Issue by prashanth31** [MODFLOW-USGS/modflow6#638]
flopy.utils.mflistfile.Mf6ListBudget currently doesn't seem to have code to read in modflow 6 transport budgets from the list file. Can this code be added ?

**Comment by jtwhite79** [comment]
```
class Mf6TListBudget(flopy.utils.mflistfile.ListBudget):
        def set_budget_key(self):
            self.budgetkey = "MASS BUDGET FOR ENTIRE MODEL"
            return
```

I've been using that in some mf6 gwt stuff I've been doing.  If you add that to the top of your script, it should work just like the other list file readers. Not sure if it covers all the gwt possibilities, but worked for what I needed.

**Comment by prashanth31** [comment]
Thanks dude! That was perfect.
Closing the issue.
