### ISSUE TITLE
SURFDEP in UZF Package increase or decrease GW Seepage ?

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#648]
According to MD6 manual, trying equation (7-91) to (7-96) with arbitrary numbers in a spreadsheet, it looks likes to me that with increasing SURFDEP, GW seepage will increase and vise versa

in my understanding: the SURFDEP is a user specified depth that allows GW Seepage to start from below the land surface, using the elevation ξ, which ξ = TOP-cell elev - 0.5*SURFDEP

However, with trying different values of SURFDEP in my 7 years trainset model (for the sensitivity analysis of my paper), I get the opposite as below (Simulated GW Seepage = % of specified infiltration):
Case 1:  SURFDEP = 0.05 , Simualted GW Seepage = 30.7% 
Case 2:  SURFDEP = 0.25, Simualted GW Seepage = 28.9%
Case 3:  SURFDEP = 0.45, Simualted GW Seepage = 26.4%
Case 4:  SURFDEP = 1, Simualted GW Seepage = 20.7%

So, it became confusing to me what SURFDEP exactly does with GW seepage!

appreciate your clarification

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 I used the small example (3 layers, 1 row, 10 columns) attached to this response to check the UZF-calculated response to varying surfdep, and everything looks as expected to me.  First, I check a groundwater discharge only case.  To do that, I used constant heads to control the elevation of the water table.  With the water table 0.5 m below land surface, I tried SURFDEP = 2.0 (first screen shot below) and 3.0 (second screen shot below), and the model with SURFDEP = 3.0 yielded more groundwater discharge, as expected.  

Your problem may be different in that rejected infiltration was not responding as you expected, so I checked that by modifying the test model to use general heads in place of constant heads, upped the FINF values and reduced the VKS values.  When I ran the attached example simulation with surfdep = 1.3, rejected infiltration equaled 1.5656; with surfdep = 1.5 rejected infiltration increased to 1.5809, which I think it what you were expecting?  That is, the % of rejected infiltration went up with increasing surfdep.  Note also that the gw discharge increased with increasing surfdep in this second set of conditions.

I may not be catching your specific set of conditions with the current setup, so please feel free to modify the attached example model in way that recreates what you're seeing and we will look at it further.

**surfdep = 2.0**
![surfdep_2](https://user-images.githubusercontent.com/3236576/109398204-3a44be80-78f0-11eb-8bd5-76af1411f446.png)

**surfdep = 3.0**
![surfdep_3](https://user-images.githubusercontent.com/3236576/109398212-50eb1580-78f0-11eb-9606-407d88f729ed.png)

[uzf_3lay_srfdchk.zip](https://github.com/MODFLOW-USGS/modflow6/files/6055242/uzf_3lay_srfdchk.zip)

**Comment by MostafaGomaa93** [comment]
@emorway-usgs What i face is with increasing SURFDEP, Rejected infiltration increased and groundwater discharge decreased which i don't know why!!

Indeed my system is complex with very different set of conditions (stresses) between dry and wet seasons. your example is only one stress period, so more straightforward than mine. I am not sure, maybe testing many stress periods can have different results.

Anyway, i will try to test your attached example to show you something similar to what i face.

Thank you

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 Given the transient nature of your problem combined with what you describe as complex set of conditions, I'm wondering if the additional rejected infiltration is due to something other than SURFDEP, like increases in FINF, increasing heads, or something else?  Maybe have a look at what the heads and/or water contents are doing through time in one of the cells where you're seeing this behavior.

**Comment by MostafaGomaa93** [comment]
@emorway-usgs no no. I am only changing SURFDEP while all other parameters and stresses are the same

The point is that i wrote in my paper draft the following statement "The MF6 UZF package intoduce the new SURFDEP that allows groundwater discharge to start from below the land surface."

Then was thinking to confirm my statement with the sensitivity analysis of SURFDEP, but was shocked with the results as mentioned earlier.

**Comment by MostafaGomaa93** [comment]
@emorway-usgs 
Please have a look at the attached example. This is a steady-state example with similar conditions to my model. I change the SURFDEP 3 times where all other conditions do not change. I attach also three screenshots of the UZF-GWD and UZF-GWD-To-MVR and three screenshots of REJ-INF

so, with increasing SURFDEP, REJ-INF increased and UZF-GWD decreased

[SURDEP_tests.zip](https://github.com/MODFLOW-USGS/modflow6/files/6056752/SURDEP_tests.zip)

**Comment by MostafaGomaa93** [comment]
![GWD@SURFDEP=1 45](https://user-images.githubusercontent.com/54531356/109417926-f91ede00-79c5-11eb-8751-1792f8f6c7d2.PNG)

**Comment by emorway-usgs** [comment]
Hello @MostafaGomaa93, all three models have % discrepancies (for the entire model) in the neighborhood of 70% making it difficult to know if UZF isn't working correctly.  I think it is important to get the percent discrepancies in the neighborhood of 1% (or less) before diagnosing what may be happening with SURFDEP.

**Comment by MostafaGomaa93** [comment]
Hi @emorway-usgs, sorry for that mistake. anyway, I update the previous zip file and all the screenshots above. please have a look again

**Comment by jdhughes-usgs** [comment]
`SURFDEP` is also used to calculate rejected infiltration. The infiltration applied to the saturated portion of the cell is rejected. The saturated portion of the cell is a linear function of the water level and `SURFDEP`.

Everything looks ok in the code but will add an update if I find any issues.

**Comment by MostafaGomaa93** [comment]
@jdhughes-usgs But according to the MD6 manual, trying equation (7-91) to (7-96) with arbitrary numbers in a spreadsheet, it looks likes to me that with increasing SURFDEP, UZF-GWD should increase

while in my model, I am facing the opposite!! That's my concern

**Comment by jdhughes-usgs** [comment]
@MostafaGomaa93 Increasing `SURFDEP` is going to change rejected infiltration which is going to change actual infiltration to the UZF which will change water-levels and groundwater discharge to the surface. The water budget results you included in the issue showed an increase in rejected infiltration with increasing `SURFDEP`. Increase rejected infiltration is coincident with reduced groundwater discharge to the surface, which seems consistent with reduced actual infiltration to the unsaturated zone.

**Comment by MostafaGomaa93** [comment]
@jdhughes-usgs 
I understand what you are saying but the equations do different results. please check the attached fig. This is a test of equations (7-91) to (7-96) with two cases: SURFDEP = 1 and SURFDEP = 2

For me, it looks like the actual infiltration is responding differently when the water table is above and below the land surface elevation (in the attached fig, land surface = 100). So,

For Case 1: when water level = 99.75, so below the land surface but still above the specified surface (land surface - 0.5*SURFDEP)  

Act-INF @ SURFDEP = 1 is more than Act-INF @ SURFDEP = 2, which means  
Rej-INF @ SURFDEP = 1 is less than Rej-INF @ SURFDEP = 2

For Case 1: when water level = 99.75, so below the land surface but still above the specified surface (land surface - 0.5*SURFDEP)  

Act-INF @ SURFDEP = 1 is more than Act-INF @ SURFDEP = 2, which means  
Rej-INF @ SURFDEP = 1 is less than Rej-INF @ SURFDEP = 2

For Case 2: when water level = 100.25, so above the land surface

Act-INF @ SURFDEP = 1 is less than Act-INF @ SURFDEP = 2, which means  
Rej-INF @ SURFDEP = 1 is more than Rej-INF @ SURFDEP = 2

and in both cases, GW discharge @ SURFDEP = 2 is more than GW discharge @ SURFDEP = 1

This is still different from what my model test produce

![test_equations](https://user-images.githubusercontent.com/54531356/109690072-3c27af80-7b86-11eb-8636-6519943bf76d.PNG)

**Comment by jdhughes-usgs** [comment]
@MostafaGomaa93 The heads in your model are not controlled by a constant head. It makes sense to me that the simulated results are different from your evaluation of the functions using specified heads.

**Comment by MostafaGomaa93** [comment]
@jdhughes-usgs 
Okay last clarification, please. 

Are the statements below correct:

1- SURFDEP is a user-specified depth that allows GW-discharge to start from below the land surface.

 2-In the excess saturation case, SURFDEP controls the partitioning between the rejected infiltration and groundwater exfiltration based on the groundwater heads.

**Comment by jdhughes-usgs** [comment]
@MostafaGomaa93 

1. Yes - groundwater seepage to the surface starts at `SURFDEP / 2` meters/feet/etc. below land surface
2. No - `SURFDEP` does not control partitioning between rejected infiltration and groundwater seepage to the surface. The saturated area of a cell is calculated using `SURFDEP`. All infiltration is rejected from the saturated area of the cell. There may be additional rejected infiltration from the cell if the infiltration rate exceeds `vks`. The groundwater seepage is calculated as the product of the head difference (`h - top - SURFDEP / 2`), the groundwater seepage conductance, the cell area, and the ratio of the saturated area and the cell area (saturated fraction of the cell). Groundwater seepage to the surface is only calculated if the `SIMULATE_GWSEEP` option is specified but rejected infiltration always occurs from saturated portions of a cell.

**Comment by emorway-usgs** [comment]
@MostafaGomaa93 I tried running the test models you re-uploaded to this issue, but am getting an error (see below).  I like @jdhughes-usgs response, the balance (equilibrium) that the code will settle on will likely be different than your external calculations based on a fixed head.  Of course, MF is going to calculate the head and not hold it fixed, unless you specify the head in the cell from which gw seep is occurring, but that wouldn't be a good use of the UZF package, in my opinion.

![MF6_error](https://user-images.githubusercontent.com/3236576/110052257-247a3380-7d0c-11eb-8b59-488fd1a92787.png)
