### ISSUE TITLE
OPEN/CLOSE not supported by GWT SSM SOURCES?

### ISSUE THREAD

**Issue by mkennard-aquaveo** [MODFLOW-USGS/modflow6#649]
Table A-1 (page A-4) of mf6io.pdf for version 6.2.0 indicates that the SOURCES block of the SSM package of GWT should support OPEN/CLOSE. However, when I try to use OPEN/CLOSE there MODFLOW reports the following at the bottom of the mfsim.lst file:

ERROR REPORT:

  1. ERROR.  PACKAGE CANNOT BE FOUND: OPEN/CLOSE

I am using example ex-gwt-mt3dms-p03. The SOURCES block in the original file looks like this:

BEGIN sources
  WEL-1  AUX  CONCENTRATION
END sources

I changed it to the following and put the one line 'WEL-1  AUX  CONCENTRATION' in a separate file called ssm_sources.txt which I attached:

BEGIN sources
  OPEN/CLOSE ssm_sources.txt
END sources

[ssm_sources.txt](https://github.com/MODFLOW-USGS/modflow6/files/6070602/ssm_sources.txt)

**Comment by langevin-usgs** [comment]
I think this is fixed in our latest 6.2.1 release.

**Comment by mkennard-aquaveo** [comment]
Great! Thanks!
