### ISSUE TITLE
Model with transport+density running on Linux but not Windows

### ISSUE THREAD

**Issue by dbrakenhoff** [MODFLOW-USGS/modflow6#651]
A student I'm supervising is working on a model with transport and density. She ran into the following error when attempting to run the model on her PC (Windows). The screenshot below shows the error. I managed to reproduce it using the downloaded pre-compiled mf6 from the USGS website (VERSION 6.2.1 02/18/2021). 

![image](https://user-images.githubusercontent.com/6552225/110135784-32dd5380-7dcf-11eb-8368-ff2840bc05df.png)

Weird thing is I'm able to run the model without any errors from Linux using the latest stable version of mf6 compiled with pymake (VERSION 6.2.1 02/18/2021). Any idea what's going on here, and how Windows users should proceed?

The mf6 files are contained in the zip:
[mf6_transport_model.zip](https://github.com/MODFLOW-USGS/modflow6/files/6091483/mf6_transport_model.zip)

Hope I'm not missing something and this is a MF6 issue... Thanks in advance for taking a look!

Davíd

**Comment by langevin-usgs** [comment]
Hey @dbrakenhoff, so the issue is that your dis packages are different.  The current implementation requires that the DIS Packages be identical for flow and transport.  This is something that we may relax in the future, but right now they have to be the same.  

For the GWF Model, I see this in the listing file:

```
 THE SPECIFIED IDOMAIN RESULTS IN A REDUCED NUMBER OF CELLS.
 NUMBER OF USER NODES: 605010
 NUMBER OF NODES IN SOLUTION: 349265
```

For the GWT Model, I see this in the listing file:
```
 THE SPECIFIED IDOMAIN RESULTS IN A REDUCED NUMBER OF CELLS.
 NUMBER OF USER NODES: 605010
 NUMBER OF NODES IN SOLUTION: 330487
```

Looks like you are using different IDOMAINS.  They will need to be the same.

**Comment by dbrakenhoff** [comment]
Thanks for the quick response @langevin-usgs! That solved the problem! 

But I'm still a bit curious why this didn't result in an error on Linux? That fact kind led us away from the idea that it might be an input-data issue...

**Comment by langevin-usgs** [comment]
That mismatch in the dis idomain caused the program to access a part of an array that didn't exist.  That array access violation behaves different with different compiler switches and on different platforms.  The program may continue to run with invalid numbers if there is a trap for this condition.
