### ISSUE TITLE
Specifying GNCs when the connection cells are active, but the J-cell isn't

### ISSUE THREAD

**Issue by aleaf** [MODFLOW-USGS/modflow6#670]
Hi, in attempting to implement ghost node corrections for a parent/child model LGR setup (produced by the Lgr utility in flopy), I came across the situation of valid GWF Exchange Package connections (where both the parent and child cells are active) that do not have active jcells (for performing the ghost node head interpolation). In the figure below, the black cells are pinched out (``idomain=-1``). The child cells below the red line are active, but GNC can't be applied to their connections because there is no J-cell to the left. I tried setting the corresponding alphaj values to 0, but got this message:
```
  1. PFL_LGR_PARENT Cell is outside active grid domain: (3,56,29)
  2. PFL_LGR_PARENT Cell is outside active grid domain: (3,56,29)
  3. PFL_LGR_PARENT Cell is outside active grid domain: (3,56,29)
  4. PFL_LGR_PARENT Cell is outside active grid domain: (3,56,29)
  5. PFL_LGR_PARENT Cell is outside active grid domain: (3,56,29)
```
Removing the GNCs results in a mismatch between the number of exchanges and GNCs, also resulting in an error. Removing both the exchanges and GNCs allows the model to run, but then there are no exchanges for those cells.

Thanks for all of the great work on MODFLOW-6!
![Screen Shot 2021-03-16 at 2 20 49 PM](https://user-images.githubusercontent.com/3923387/111368533-042f6a80-8664-11eb-842c-1f552a32cb51.png)

**Comment by langevin-usgs** [comment]
Since those cells are idomained out, just set J to the parent cell and alpha to zero.  Will that work?

**Comment by langevin-usgs** [comment]
Also, you can set the cellid to zero, for those, I believe.  At least according to the mf6io.pdf manual.

![image](https://user-images.githubusercontent.com/3372403/111373814-5bd0d480-866a-11eb-8d1f-11de860ad15e.png)

**Comment by aleaf** [comment]
Good idea on setting J to the parent cell, I hadn't thought of that. Doing that works.

When I try setting cellid to zero, I get this error:

```
ERROR REPORT:

  1. File unit 1056: Error converting "0.00" to an integer in following line:
  2. 3 56 30  3 1 91  0  0.00
```

**Comment by langevin-usgs** [comment]
you would specify three zeros for the cellid for a structured grid.

**Comment by aleaf** [comment]
That works, thanks! sorry for missing that detail.
