### ISSUE TITLE
mf5to6 converter produces duplicate diversion records

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/modflow6#677]
From user:

There appears to be a bug in the mf5to6 utility regarding diversions in the SFR package. The package we are converting has 14 diversions, and for some reason the mf5to6 utility appears to get stuck in a loop when generating period data for those diversions and adds numerous lines with erroneous diversion specifications in the PERIOD data blocks. Example with the diversion at segment 4795:

The DIVERSION block correctly specifies the number of diversions:

```
BEGIN DIVERSIONS
  # rno idv iconr iprior
  1749  1  5077  UPTO     
  1834  1  5078  UPTO     
  2587  1  5080  UPTO     
  2596  1  5079  UPTO     
  3768  1  5081  UPTO     
  4097  1  5082  UPTO     
  4203  1  5083  UPTO     
  4305  1  5084  UPTO     
  4423  1  5085  UPTO     
  4451  1  5086  UPTO     
  4483  1  5087  UPTO     
  4642  1  5088  UPTO     
  4692  1  4735  FRACTION
  4795  1  4796  FRACTION
END DIVERSIONS
```
 
The PERIOD 1 data block is also correct:

```
BEGIN PERIOD 1
…

4795 diversion 1   0.00000000000000
END PERIOD
```
 
The Period 2 data block, however, starts making duplicate diversion entries with incrementing priority numbers:

```
BEGIN PERIOD 2
…
4795 diversion 1   0.00000000000000
4795 diversion 2   0.00000000000000
4795 diversion 3   0.00000000000000
END PERIOD
```
 
By the time we reach stress period 585, the number of duplicates has increased dramatically (creating a 20+GB SFR Package before we stopped the code):

 ```
BEGIN PERIOD 585
…
4795 diversion 171403   0.00000000000000
4795 diversion 171404   0.00000000000000
4795 diversion 171405   0.00000000000000
END PERIOD
```

**Comment by danwalters** [comment]
This is a simple test model that recreates the error mentioned in Chuck’s e-mail. The SFR_MF6_Problem files are the MF2005 build, and the SFR_MF6_Converted files are for MF6. The SFR_MF6_Converted.sfr file has the iterative diversions problem mentioned previously.

[MF6_SFR_Conversion_Issue.zip](https://github.com/MODFLOW-USGS/modflow6/files/6204660/MF6_SFR_Conversion_Issue.zip)

**Comment by langevin-usgs** [comment]
Can you see if this version of the converter works for you?  Unfortunately, the converter and SFR is a can of worms.  There are an unlimited number of SFR options and having a comprehensive conversion utility is problematic.  This might get past the current diversion duplication problem.  If this works for you, then I'll add these changes to our next release.

[mf5to6.exe.zip](https://github.com/MODFLOW-USGS/modflow6/files/6215744/mf5to6.exe.zip)

**Comment by danwalters** [comment]
The latest version of the converter does eliminate the iterative duplication problem. There is still an issue, however, regarding the assignment of upstream fractions. Running in MODFLOW produces the following error;

  1. Reach 4692 is connected to reach 4735 by a diversion but the upstream
     fraction is not equal to zero (1.000000000000000). Check SFR_1 package
     diversion and package data.

  2. Upstream fractions for reach  4692 is not equal to one
     (2.000000000000000). Check SFR_1 package reach connectivity and package
     data.

When a diversion occurs, the upstream fraction value in the PACKAGEDATA block (ustrf) should be set to 0 rather then 1.

  4735 1 186 327    219.0000        200.0000       0.1310000E-02    2120.100        219.0000        400.0000       0.3000000E-01  2  0.0000  1

Should be changed to...

  4735 1 186 327    219.0000        200.0000       0.1310000E-02    2120.100        219.0000        400.0000       0.3000000E-01  2  0.0000  0

A quick test suggests that replacing the ustrf value for the appropriate upstream segment allows the model to proceed successfully.

Thanks!

**Comment by langevin-usgs** [comment]
The converter has trouble with complicated SFR packages.  Closing for now.
