### ISSUE TITLE
UZF package with Richard equation !

### ISSUE THREAD

**Issue by MostafaGomaa93** [MODFLOW-USGS/modflow6#703]
For any of the coming versions of MODFLOW 6, Is there any plan to include the 1D or 3D Richard equation in the UZF package instead of the kinematic wave approximation?

**Comment by langevin-usgs** [comment]
Added this to request to the roadmap for MODFLOW 6 development.  It is something that we would like to implement.  Just not sure when that will happen.  https://github.com/MODFLOW-USGS/modflow6/wiki
