### ISSUE TITLE
storage change dependent on elevation datum

### ISSUE THREAD

**Issue by aprovost-usgs** [MODFLOW-USGS/modflow6#711]
The change in storage in a cell should be independent of the elevation datum (the vertical position relative to which elevations and heads are defined).  However, the compressible storage change is apparently sensitive to the elevation datum, as can be seen by adding an arbitrary constant to the old and new heads in eqn. 5-3 of the MF6 documentation (USGS T&M 6-A55).  Unexpected sensitivity of simulation results to the elevation datum has been observed in a variation on MF6 test problem test007_75x75.

**Comment by langevin-usgs** [comment]
Closed with https://github.com/MODFLOW-USGS/modflow6/commit/85ca6895898bc8000b5299c1b4de44ee693efef2
