### ISSUE TITLE
MAW appears to calculate conductance incorrectly.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#713]
In the attached model, the MAW package calculates negative conductances for reasons that aren't obvious. This is a simplified version of a model by David Ström david.strom@sweco.se
[Strom.zip](https://github.com/MODFLOW-USGS/modflow6/files/6321917/Strom.zip)

**Comment by rbwinst-usgs** [comment]
The well screen diameter is greater than the cell size.

**Comment by rbwinst-usgs** [comment]
According to David Ström, the model runs without a problem in version 6.1 but not in version 6.2.1.

**Comment by langevin-usgs** [comment]
Unclear if this is an error in the code.  Feel free to reopen and provide more details if the problem persists.
