### ISSUE TITLE
Upstream weighting conductance for GHB

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#724]
Currently, if the GHB head is lower than the cell bottom the model run will be terminated.

Can we implement something similar to upstream weighting for the GHB conductance such that when the head is lower than the cell bottom the conductance will be reduced to zero?

This will help during model calibration that the GHB head is calculated by PEST and can be updated to a value lower than the cell bottom.

**Comment by langevin-usgs** [comment]
Hi @ougx, not sure this is still needed.  Seems like you could use bounds for the GHB head when running PEST?  Feel free to reopen if you feel this is critical.
