### ISSUE TITLE
DISU with inactive nodes prompts "access violation" error

### ISSUE THREAD

**Issue by geowat** [MODFLOW-USGS/modflow6#745]
Modflow6 DISU file was generated with Algomesh (multi-layer voronoi mesh). 

a) The model runs fine with the DISU file generated by Algomesh without IDOMAIN (hence all the nodes are active),

b) it also runs fine with IDOMAIN if all the nodes are ones (hence they are still active), 

c) but we are getting CONNECTIONSMODULE error message when any of the cells are inactive (e.g. the cell which is inactive has layers underneath so initially we thought it may have something to do with recharge but Modflow6 can apply RCH to the most active layer). 

![disu_idomain_access_violation](https://user-images.githubusercontent.com/17356020/123075086-cdf64980-d40f-11eb-9d65-14a1ee0e419b.PNG)

In our understanding, inactive cells should not affect the connections but those inactive cells are just removed from the groundwater equation. Since we are just pasting IDOMAIN list array straight into DISU manually – would the inactive cells affect any of the connections – if they do, how should we generate DISU file with inactive cells? We can't pinch out those inactive nodes due to the recharge model requiring extra cells which are set to inactive in DISU.

**Comment by langevin-usgs** [comment]
I can see in the program where the run is dying based on the error message you posted (thanks for that).  It looks like to me like there is some sort of error in the IA or JA array that is provided in the DISU input file.  Is that possible?  The DISU capability to have an IDOMAIN array with zeros and ones is a relatively new option (note that -1 values are not supported for DISU).  We've tested this new IDOMAIN capability and know it works, but maybe there is something peculiar to your problem.  If you can recreate the problem with a relatively small test, I'd be happy to take a look.  You can copy a zip file of the model into this issue.

**Comment by geowat** [comment]
I have emailed you the link to download the input files which also has both DISU files (with/without IDOMAIN). I wouldn't be able to replicate the same error with a smaller model (although didn't try). We already have a couple of models with DISU/IDOMAIN which are working fine, so there must a specific case which Modflow6 code is missing. If the error was with IA/JA arrays then that would be Algomesh specific. Hopefully it's easy for you to find out. The only reason we are hesitant to say that it's Algomesh specific is because the model is running fine without any inactive nodes (so probably connections are fine?) - we already contacted Algomesh team and they recommended to raise a GitHub issue. Many Thanks for looking!

**Comment by langevin-usgs** [comment]
When IDOMAIN is used with DISU and any IDOMAIN  value is zero, then the program is expecting all JA values to be positive.  We allow a negative JA value to be specified for the corresponding cell (in the diagonal position), but this is not working for the new IDOMAIN capability.  I will submit a fix.  For your problem, if you just make sure that all JA values are positive, then your model should run.  Thanks for reporting the issue.

**Comment by geowat** [comment]
Great - thank you so much! Just to confirm that it has worked with positive node numbers!
