### ISSUE TITLE
Modelling heat transport

### ISSUE THREAD

**Issue by Martin-Pujol** [MODFLOW-USGS/modflow6#753]
Hi,
 
I am keen to move to MODFLOW 6 unfortunately as far as I understand the new BUY package only allows density to vary but not the viscosity. As we have been using SEAWAT for modelling thermal breakthrough for geothermal applications this is an essential package for us.
 
Just wondering if there are any plans to develop a viscosity package for MODFLOW 6 or even better consider more intuitive heat transport model for MODFLOW 6 that uses native thermal units. Ability to activate deactivate variable density and variable viscosity and define the equation of state would be a plus.
 
Cheers
Martin Pujol

**Comment by haugwitz** [comment]
I think I remember from a recent USGS presentation that heat transport is in the pipeline for modflow 6, but I don't recall a time schedule for it.

**Comment by langevin-usgs** [comment]
Thanks for this feedback.  This is on our development list (https://github.com/MODFLOW-USGS/modflow6/wiki) and we are hoping to get started on it this fall.
