### ISSUE TITLE
Database of mfsim files to optimize ims solver settings

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#755]
Random idea, there should be an option for the ims solver to write a highly detailed diagnostic file and then upload it to a repository somewhere where they can be used to train an algorithm that can recommend optimal solver settings

**Comment by langevin-usgs** [comment]
@RyanConway91, thanks for the interesting idea.  This is certainly something that would be worth pursuing at some point.  I'm going to close this issue as it is not something that we can immediately address, but we will keep this in mind for future development.
