### ISSUE TITLE
GridIntersect does not include cells with identical vertices, even with DISU

### ISSUE THREAD

**Issue by mkennard-aquaveo** [MODFLOW-USGS/modflow6#767]
If I am dealing with DISU and a vertex grid, I want GridIntersect to return all cells intersected, but currently it removes cells that share the same vertices as a previously intersected cell. This is fine for layered grids such as with DIS and DISV, but with DISU which has no layers, it is a problem.

GridIntersect ._intersect_point_shapely() includes these lines which cull the results and which I would like to bypass:
```
if verts in parsed_points:
    continue
```

GridIntersect._intersect_linestring_shapely() has a similar code block. I would like a way to make that optional so that I can get all intersected cells in the results. Perhaps a kwarg called something like "keep_all_layers" could be used to bypass that code block.

**Comment by jdhughes-usgs** [comment]
@mkennard-aquaveo Could you post this as a flopy issue.
