### ISSUE TITLE
Zonebudget errors if path contains a space.

### ISSUE THREAD

**Issue by mkennard-aquaveo** [MODFLOW-USGS/modflow6#771]
This may be related to this issue (and is maybe now fixed?): [MODFLOW 6 executable cannot be found if path contains a space](https://github.com/MODFLOW-USGS/modflow6/issues/100)

Zonebudget cannot run correctly if there are spaces in the path to the executable, even if the path is in quotes. In the attached files, if you run the batch file "\zbud6_spaces_in_path_bug\t039\run_zonebudget_with_space_quoted.bat" you'll see the error. This batch file is trying to run Zonebudget using this command line: "..\zbud6 exe\zbud6" zonebud.zbnam

[zbud6_spaces_in_path_bug.zip](https://github.com/MODFLOW-USGS/modflow6/files/7041421/zbud6_spaces_in_path_bug.zip)

**Comment by langevin-usgs** [comment]
Thanks for pointing this out.  Looks like we do need to refactor the zone budget code for how it handles command line arguments as we did for the mf6 code.  I don't think any of us developers have spaces in our directory names!
