### ISSUE TITLE
HFB package does not seem to accept "open/close" in period data specification. 

### ISSUE THREAD

**Issue by JoerivanEngelen** [MODFLOW-USGS/modflow6#787]
There seems to be a bug where I cannot specify external files with period data for Modflow6.
It seems to try to convert the "open/close" to an integer:
```
                                   MODFLOW 6
                U.S. GEOLOGICAL SURVEY MODULAR HYDROLOGIC MODEL
                   VERSION 6.3.0 release candidate 07/30/2021
                               ***DEVELOP MODE***

  MODFLOW 6 compiled Sep 17 2021 17:17:08 with GFORTRAN compiler (ver. 8.1.0)

... 

ERROR REPORT:

  1. File unit 1009: Error converting "open/close" to an integer in following
     line:
  2. open/close gwf1/hfb/hfb.bin (binary)

UNIT ERROR REPORT:

  1. ERROR OCCURRED WHILE READING FILE 'gwf1/hfb.hfb'

STOP 2
```

It also fails with versions 6.2.2 and 6.2.1.

The release notes for v6.2.1 state:
_Several packages had input blocks that could not be specified using the OPEN/CLOSE keyword.
The program was modified so that OPEN/CLOSE is supported for all intended blocks._

But I guess this is an overlooked case? All the examples I could find wrote all arrays directly as text in the .hfb file.
When I did this as well, the model worked without any problems.

Either that, or the files I wrote are wrong, which is perfectly possible, but then I'd expect a different error message.
See added test models. 

[test_model_fails.zip](https://github.com/MODFLOW-USGS/modflow6/files/7204348/test_model_fails.zip)

[test_model_works.zip](https://github.com/MODFLOW-USGS/modflow6/files/7204350/test_model_works.zip)

**Comment by langevin-usgs** [comment]
Hi @JoerivanEngelen,

There are two uses of open/close.  One is for reading arrays, such as hydraulic conductivity.  In that case, the (binary) tag works.  The other use case is when the contents of a block are located in another file.  In that case, that other file must be a text file.  So for your model, if you change the hfb list to text, then it works fine.

```
begin period 1
  open/close gwf1/hfb/hfb.txt
end period
```

**Comment by JoerivanEngelen** [comment]
Yes that indeed works. Thanks for the quick reply. I erronously thought that list input for a PERIOD block could be written to binary for any package, except the Advanced Stress Packages. But this only holds for the stress packages (CHD, WEL, DRN, RIV,
GHB, RCH, and EVT).

For anybody running into similar issues, reading the documentation better, it is implicitly stated that this should not work for the HFB:
_Lists for the stress packages (CHD, WEL, DRN, RIV,
GHB, RCH, and EVT) have an additional BINARY option. The BINARY option is not supported for the
advanced stress packages (LAK, MAW, SFR, UZF)._
