### ISSUE TITLE
Do ghost nodes work on 

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#788]
The ghost node example discussed in the documentation focuses on connecting a nested grid laterally. 
Can ghost nodes be used when connecting a nest with layer refinements? For example, a nested grid with the same row column spacing as the parent but with several layers for each parent model layer?

**Comment by langevin-usgs** [comment]
Yes, ghost nodes should work in this situation.  You will need to calculate the alpha factors correctly, but then the ghost-node interpolation will work as you would expect.
