### ISSUE TITLE
Preliminary parallelization capability in development branch?

### ISSUE THREAD

**Issue by Darksaber501st** [MODFLOW-USGS/modflow6#792]
Hi, I saw on the wiki that parallelization via MPI for HPC environments is included in the development map for 6.4.0.

On one of the MODFLOW 6 USGS webpages, it says a preliminary version of this capability has already been tested, and I see that there's an unused "parallel" branch here on Github and that there's already been a conference paper on this. I know the parallelization is still probably a work in progress, but is this capability currently included in any of the available development builds? I tried hunting for it in the docs but couldn't find anything. I've got some large-ish MODFLOW 2005 and NWT models I would love to convert to MODFLOW 6 and try running using my available HPC environment, even if I have to trial and error a lot of stuff since it's not release-ready.

**Comment by langevin-usgs** [comment]
The parallel capabilities are not available through our main MODFLOW6 repository yet.  I believe you sent a separate email to our usgs modflow address.  I responded to that request with some additional information.
