### ISSUE TITLE
Steady state option for solute transport in MODFLOW 6

### ISSUE THREAD

**Issue by Sbai7** [MODFLOW-USGS/modflow6#799]
Dear @langevin-usgs & @jdhughes-usgs  

In a couple of months, I plan to implement a method that calculates the advective travel time by directly solving the advective part of the solute transport equation. Hence, it can be used as an alternative to particle tracking. The same technique delineates the spatial partitions in the aquifer connecting all inflowing and outflowing boundary conditions of a GWF model. 

A prototype of the method has been implemented in MATLAB and documented in the following publications:
1- https://doi.org/10.1111/gwat.12646
2- https://doi.org/10.1111/gwat.12978
But, I'm missing many of the MODFLOW features to make the method works for more general models. 

Basically, the method solves a steady-state groundwater flow model followed by many steady-state advective transport runs using different sets of boundary conditions. 

As a steady-state option for a GWT model does not exist yet in MODFLOW 6 (maybe this is ok now?). Are there any future plans to include this option? If not, can you give some thoughtful hints on how to do it more efficiently? Perhaps by subclassing an existing Fortran module?

After this first step (i.e. when the steady-state transport option is available), I guess the method could be tested using FloPy without supercharging the core MODFLOW 6. But, my abilities to do OO Fortran are much better, so I can promptly implement it as a separate Fortran module. Do you agree to my proposal? Any comments?

Kind Regards,
Adil

**Comment by langevin-usgs** [comment]
Add steady state GWT to list of requested features.
