### ISSUE TITLE
Time Array Series issue - Intel compiler on MacOS

### ISSUE THREAD

**Issue by jdhughes-usgs** [MODFLOW-USGS/modflow6#813]
Autotest from testmodels (`test_z01_testmodels_mf6.py::test_mf6model[29-test001h_rch_array4]`) intermittently fails on MacOS with:

` AssertionError: Unsuccessful comparison run`

See: https://github.com/MODFLOW-USGS/modflow6/pull/812/checks?check_run_id=3930840337

Add additional failures as Comments to this issue so that this failure can be tracked.

**Comment by langevin-usgs** [comment]
It failed here: https://github.com/MODFLOW-USGS/modflow6/runs/4090998637?check_suite_focus=true

It looks like it is dying at the beginning of time step four, based on what it is written to mfsim.lst, but it could be just that the file buffer wasn't written.  I'm guessing that it is somewhere in the finalize routines.

**Comment by langevin-usgs** [comment]
It failed here: https://github.com/MODFLOW-USGS/modflow6/runs/4992024733?check_suite_focus=true

**Comment by langevin-usgs** [comment]
Haven't seen this much lately.  Closing for now.  Reopen if mac fails with `test001h_rch_array4`.
