### ISSUE TITLE
Problem:The mf6.exe can not be used and the compiling is not successfully

### ISSUE THREAD

**Issue by haifan-upc** [MODFLOW-USGS/modflow6#829]
Dear sir, 

    I downloaded the executables and found that all executables can be opened successfully except mf6.exe. Then i opened the .sln file in msvs and tried to compile the program using VS2019. The  building process seems good, but the executable is not created. It is reported that "The thread 0X6998 has exited with code 2".  What's wrong with the compiling process or my system? Thanks!

![QQ截图20211031223657](https://user-images.githubusercontent.com/86347862/139588762-addae318-b3d4-434c-9541-c128604c30d7.jpg)
![QQ截图20211031223744](https://user-images.githubusercontent.com/86347862/139588764-ff511ee1-fe19-46f9-887f-b65bf5c57a6d.jpg)
![QQ截图20211031223754](https://user-images.githubusercontent.com/86347862/139588767-294810a1-4c4e-4363-a3b1-9697a241a94c.jpg)

**Comment by langevin-usgs** [comment]
It looks like MODFLOW 6 compiled just fine.  You should be able to see mf6.exe in the bin folder.

It's unclear what you are trying to do.  Are you running the examples?

I'm going to close this issue, because there doesn't seem to be a problem.
