### ISSUE TITLE
flow model boundary fluxes in FMI with API

### ISSUE THREAD

**Issue by jtwhite79** [MODFLOW-USGS/modflow6#835]
I wish I could get a few more acronyms in that title!  

Im super new to the API usage but I cant find flow model boundary info and/fluxes exposed thru the API.  maybe Im missing it?

**Comment by mjr-deltares** [comment]
Hi, 

if you run your simulation with option 'MEMORY_PRINT_OPTION ALL' in mfsim.nam, does the variable you're interested in show up in the list? For example, the boundary package (`BndType`) has the variable simvals

`real(DP), dimension(:), pointer, contiguous :: simvals => null()             !< simulated values`

where flow rates are stored. Would that be the one you are after?

**Comment by langevin-usgs** [comment]
This one is on me.  I need to refactor the code so that boundary flows for each GWF stress package are stored through the memory manager.  Right now, that memory is allocated directly and stored in a helper class.  This is only an issue when GWT is run in a separate simulation from a GWF simulation.

**Comment by jtwhite79** [comment]
just a followup to this: Im also after the concentration of injection wells thru the API - I want to be able to change these for each stress period.  Are these values also currently not exposed thru the API?  Its also very possible Im just missing them...

**Comment by langevin-usgs** [comment]
Good questions @jtwhite79.  There are a few things to consider here:

1. If your well concentrations are being assigned based on AUX variables stored in the budget file, then we are still working to get that information accessible through the API (this is the same issue with the actual well flow rates, which are also not available yet, so leaving this issue open).
2. If you use MAW and the corresponding MWT Package to calculate a borehole concentration, then well injection concentrations can be accessed through the API using MODELNAME/MWTNAME/CONCRATE.
2. The SSM Package has a new SPC option for specifying source concentrations to be associated with a stress package.  The SSM input example below shows how SPC input can be assigned to packages.  To access or change those through the API, the vector of concentrations is found through the memory manager at MODELNAME/SPC-1/DBLVEC, MODELNAME/SPC-2/DBLVEC, etc., where the numbers are the consecutive SPC numbers in the FILEINPUT block.
```
BEGIN OPTIONS
  PRINT_FLOWS 
  SAVE_FLOWS
END OPTIONS

BEGIN SOURCES  								
  # pname srctype auxname
  WEL-1 AUX CONCENTRATION LAK-1 AUX CONCENTRATION
  EVT-1 AUXMIXED ETCONC 
END SOURCES

BEGIN FILEINPUT
  GHB-1 SPC6 FILEINPUT mymodel.ghb1.spc 
  EVT-2 SPC6 FILEINPUT mymodel.evt2.spca MIXED
END FILEINPUT
```

Hope that helps.

**Comment by langevin-usgs** [comment]
I have a PR (#850) that should be ready to merge once the tests pass.  The information that you need should now be accessible through the FMI package.  The following shows a list of the variables printed with the MEMORY_PRINT_OPTION set to ALL.  In this list, you can see FMI-FT1 and FMI-FT2, and there may be others.  Each one of these corresponds to a "flow term".  FT1 may be well flows, for example.  Note that if a package has an active water mover, then the simulated water mover flow rates will be contained in a separate and additional "flow term".  So there may be DRN-1 package with DRN budget text and DRN-1 package with DRN-TO-MVR budget text.  

The variables accessible through the API include the following:

* NAME -- the package name (WEL-1, WEL-2, SFR-7, etc.);
* BUDTXT -- the type of flows (CHD, DRN, DRN-TO-MVR, GHB, etc.);
* NAUX -- number of auxiliary variables;
* AUXNAME -- array of auxiliary variable names (array is of size naux);
* NBOUND -- number of active entries for this package for this stress period;
* NODELIST -- vector of reduced cell numbers (reduced is the consecutive cell number NOT including IDOMAIN <= 0;
* FLOW -- vector of groundwater flow rates, positive is into the cell;
* AUXVAR -- 2D array of auxiliary variables; these may have concentrations in them if this is how SSM concentrations are assigned.

```
...
 TRANSPORT/FMI-FT1                 NAME             STRING LEN=16                      16 --                                                
 TRANSPORT/FMI-FT1                 BUDTXT           STRING LEN=16                      16 --                                                
 TRANSPORT/FMI-FT1                 NAUX             INTEGER                             1 --                                                
 TRANSPORT/FMI-FT1                 AUXNAME          STRING LEN=16                      16 --                                                
 TRANSPORT/FMI-FT1                 NBOUND           INTEGER                             1 --                                                
 TRANSPORT/FMI-FT1                 NODELIST         INTEGER                             1 --                                                
 TRANSPORT/FMI-FT1                 FLOW             DOUBLE                              1 --                                                
 TRANSPORT/FMI-FT1                 AUXVAR           DOUBLE                              1 --                                                
 TRANSPORT/FMI-FT2                 NAME             STRING LEN=16                      16 --                                                
 TRANSPORT/FMI-FT2                 BUDTXT           STRING LEN=16                      16 --                                                
 TRANSPORT/FMI-FT2                 NAUX             INTEGER                             1 --                                                
 TRANSPORT/FMI-FT2                 AUXNAME          STRING LEN=16                       0 --                                                
 TRANSPORT/FMI-FT2                 NBOUND           INTEGER                             1 --                                                
 TRANSPORT/FMI-FT2                 NODELIST         INTEGER                             1 --                                                
 TRANSPORT/FMI-FT2                 FLOW             DOUBLE                              1 --                                                
 TRANSPORT/FMI-FT2                 AUXVAR           DOUBLE                              0 --
...
```
