### ISSUE TITLE
Modpath7 particle tracking through exchange model. Best practice?

### ISSUE THREAD

**Issue by haugwitz** [MODFLOW-USGS/modflow6#836]
Is there a method for tracking a particle with modpath7 through a modflow6 exchange model? (Im currently using Flopy 334)

I tried my luck on stackoverflow, but I would like to know if there is an "official" solution or if it is a work in progress.

https://stackoverflow.com/questions/67993569/is-it-possible-to-do-modpath7-particle-tracking-between-a-child-and-parent-mf6-m

I have a parent and child model where I spread particles around the parent model and some particles end up in the child model some particles stay in the parent models and some seemingly go through the child model by going along the edge.
(Exported the lines to shapefiles and visualised in ArcGIS Pro)

![image](https://user-images.githubusercontent.com/6904973/141120679-1f23f4de-1aa2-4162-b46a-4d8f3b4a4059.png)

**Comment by langevin-usgs** [comment]
We are working on new particle tracking capabilities that are being built directly into MODFLOW 6.  The goal for that effort is to support general unstructured grids as well as the passing of particles from one model to another.  As you've found, modpath7 isn't really set up to handle multiple models, and it is likely seeing a zero flow along the shared edge between the two models.  So this is something that we are working on, but it is going to take some time.
