### ISSUE TITLE
AUXILIARY NAME CANNOT BE FOUND 

### ISSUE THREAD

**Issue by briochh** [MODFLOW-USGS/modflow6#852]
Just a heads up that somewhere a change since 30 November 2021 has done something to the ssm/auxillary reading.
Perhaps there is an intentional formatting/parameter change that I am missing. 

I now get this error when mf6 is initialising the ssm. 
```
AUXILIARY NAME CANNOT BE FOUND: AUXVAR1
ERROR OCCURRED WHILE READING FILE 'sim_d\gwt_d\aux.ssm_sources.txt'
```

my SSM:
```
# File generated by Flopy version 3.3.5 on 12/14/2021 at 16:17:58.
BEGIN options
END options

BEGIN sources
    OPEN/CLOSE  'gwt_d\aux.ssm_sources.txt'
END sources
```

and gwt_d\aux.ssm_sources.txt:
``` 
  rcha_0  aux  auxvar1
````

and .rcha looks like this:
```
# File generated by Flopy version 3.3.5 on 12/14/2021 at 16:16:54.
BEGIN options
  READASARRAYS
  auxiliary  auxvar0 auxvar1
END options

BEGIN period  1
  recharge
    OPEN/CLOSE  'gwf_d\recha_0.txt'  FACTOR  1.0
  nconc
    OPEN/CLOSE  'gwf_d\auxvar0_0.txt'  FACTOR  1.0
  tritconc
    OPEN/CLOSE  'gwf_d\auxvar1_0.txt'  FACTOR  1.0
END period  1

...
```

So it looks like we are seeing `auxvar1` in the ssm_sources file but not connecting the dots to the gwf recharge array package where it is listed as an aux?

**Comment by langevin-usgs** [comment]
I'm sure I broke something with #850 trying to fix #835.  Surprised the tests didn't catch the issue.  I'll take care of it.

**Comment by langevin-usgs** [comment]
@briochh, I can't reproduce the problem you are having.  One thing I noticed in your example above is that you have NCONC and TRITCONC listed in the period block for the recharge package, but these are not listed as auxiliary variables in the recharge package options block.  But doing something similar on my end gives me an error in the recharge package, so something seems a little off here.  Can you verify that there is an issue?  We have continued to refine things on our end in the MODFLOW code and in FloPy, so hopefully we can track down the cause of the issue.

**Comment by briochh** [comment]
Hey @langevin-usgs, thanks for looking into this. I missed those nconc and tritconc entries when I was attempting to sanitise my post. They should also read auxvar0 and auxvar1. 

I only see them error when using nightly builds 20211213 and 20211214. 20211201 flies through just fine.

**Comment by langevin-usgs** [comment]
[mf6bug.zip](https://github.com/MODFLOW-USGS/modflow6/files/7714495/mf6bug.zip)

@briochh, can you download and run this attached model and let me know if it works?  I tried to pattern it after your description and it runs fine for me on my Mac using the latest nightly build and on Windows using a fresh exe.  Clearly there is something smoldering here and I'd like to understand what's going on, if possible.  We did some refactoring on the FMI parts recently that could cause the issues you are seeing, but it would be helpful if I could reproduce the problem.

**Comment by briochh** [comment]
@langevin-usgs, your min working solution works ok for me too. I am certainly not ruling out user error here!
Potential added complexity in my simulation incl: 
* 2 transport models within the sim. (but I still get the error when just reducing to 1)
*  Models in subdirectories (urgh)
* External data files

I'll have a quick play with your example to see if I can break it.

**Comment by langevin-usgs** [comment]
@briochh, any further progress on this?  Should we close for now?

**Comment by briochh** [comment]
Hi @langevin-usgs, I haven't been able to reproduce with your min working solution. Can close for now, I'll keep an eye out my end and test with upcoming releases. I may be able to slim my breaking version down for you to look at if the problem persists (or run a debug compile here), after holidays.
