### ISSUE TITLE
ERROR FILE ALREADY OPEN ? - mf6

### ISSUE THREAD

**Issue by Flopynoob** [MODFLOW-USGS/modflow6#864]
Hello,

I am trying to build my model using mf6 (it was working perfectly with mf5 and mt3dms). Anyway,The flow model seems to work fine, however, when I added the transport packages gwt it keep showing me different errors, and the most recent is the following error:

> ERROR REPORT:
> 
>   1. *** FILE ALREADY OPEN ON UNIT: 1005
>   2.       SPECIFIED FILE STATUS: OLD
>   3.       SPECIFIED FILE FORMAT: FORMATTED
>   4.       SPECIFIED FILE ACCESS: SEQUENTIAL
>   5.       SPECIFIED FILE ACTION: READ
>   6.         IOSTAT ERROR NUMBER: -1
>   7.  -- STOP EXECUTION (openfile)
> 
> 2
> []
> False

What is the source of this error? how can it be solved

[mf6 gwf gwt.zip](https://github.com/MODFLOW-USGS/modflow6/files/7914409/mf6.gwf.gwt.zip)

The notebook file for the whole code can be found in this zip file.

**Comment by spaulins-usgs** [comment]
@Flopynoob, The error you are seeing is caused by your flow and transport models having the same dis file.  You can fix this by changing the line where you define your transport dis file to something like:

        flopy.mf6.ModflowGwfdis(gwt, nlay=nlay, nrow=nrow, ncol=ncol, delr=delr, delc=delc, top=ztop, botm=botm[1:], length_units='METERS',idomain=1, filename="{}.dis".format(gwtname))

You also have a problem with your obs and wel packages.  An observation at row 101 (100 --> 101 since it is zero based) is not possible in a model with only 70 rows.  In your wel file you need to include values for concentrations, you defined the auxiliary variable CONCENTRATION but did not define any concentration values.

**Comment by Flopynoob** [comment]
@spaulins-usgs Thank you so much, the error has gone now. However, there is a new Error which is :
`ERROR REPORT:

  1.    ***ERROR. SPECIFIC DISCHARGE NOT FOUND IN BUDGET FILE.
     SAVE_SPECIFIC_DISCHARGE AND SAVE_FLOWS MUST BE ACTIVATED IN THE NPF
     PACKAGE.
  2.    ***ERROR. SATURATION NOT FOUND IN BUDGET FILE. SAVE_SATURATION AND
     SAVE_FLOWS MUST BE ACTIVATED IN THE NPF PACKAGE.
  3.    ***ERROR. FLOWJA NOT FOUND IN BUDGET FILE. SAVE_FLOWS MUST BE
     ACTIVATED IN THE NPF PACKAGE.
`
Even though the save flow, specific discharge, and saturation are all active in the NPF package! you can check the file here
[mf6nofun2 (1).zip](https://github.com/MODFLOW-USGS/modflow6/files/7920525/mf6nofun2.1.zip)

**Comment by spaulins-usgs** [comment]
@Flopynoob, Looks like you are missing an exchange file.  Here is some example flopy code to add an exchange file:

    gwfgwt = flopy.mf6.ModflowGwfgwt(
        sim,
        exgtype="GWF6-GWT6",
        exgmnamea=gwfname,
        exgmnameb=gwtname,
        filename="flow1_transport1.gwfgwt",
    )
