### ISSUE TITLE
rerunning an API simulation

### ISSUE THREAD

**Issue by jtwhite79** [MODFLOW-USGS/modflow6#866]
Im getting a strange list file budget issue if I rerun an API simulation in the same python script.  I'm calling `finalize()` and Im even nuking the working directory and recreating the dir and the `ModflowApi` instance.  The second time thru the "SFR" budget component is replaced with "VALUE          2".  The values for the budget components are the same and "SFR" appears to just be renamed "VALUE      2". The attached files and script show this issue - the script bombs at the end because "SFR" isnt in the budget anymore.  Thanks for any help!
[Archive.zip](https://github.com/MODFLOW-USGS/modflow6/files/7929524/Archive.zip)

**Comment by mjr-deltares** [comment]
Hi @jtwhite79, thanks for reporting this. I ran your script on Windows (after renaming one of the output directories to get it to work) and managed to produce the plot without errors (attached). However, in general it is not a good idea to assume that you can _reinitialize_ the API. MODFLOW has a lot of static memory which is not cleared even if you try to reload the DLL.  Could very well be that the behavior depends on the OS you are working on. We are looking into ways of reorganizing the code to better support these types of application. However, if you are interested in a short term fix, you could try and rename the DLL/so for the second run to, say, libmf6-2.dll, it should then use a new piece of memory preventing any interference effects. Alternatively, you could start a new process (not a thread) for every new simulation, but you might prefer the former if I am understanding your use case correctly. Please let me know if this works for you.
![Figure_1](https://user-images.githubusercontent.com/45555666/151539316-1a6fab50-789c-4975-9d80-72a962681cac.png)

**Comment by jtwhite79** [comment]
right on - thanks for looking at this @mjr-deltares .  I am running this on mac and I get the complexities of shared libs and OS runtime interactions.  This showed up first when using this script in a notebook and re-executing cells.  I found if I restart the kernel that all was good.  Anyway, appreciate you looking into this.
