### ISSUE TITLE
suppress tvk, tvs writing to lst file 

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#871]
I am using a recent daily build as I am testing out the tvk, tvs functionality. Is there a way to suppress writing every tvk/tvs node to the lst? I have a large model with a lot of timesteps and lst file is becoming several gigs and I cant open it.

**Comment by langevin-usgs** [comment]
I can confirm that there could be excessive writing to the gwf list file.  The following code is from gwf3tvbase8.f90.  This write statement should probably occur only if PRINT_INPUT is set.

![image](https://user-images.githubusercontent.com/3372403/151614692-f1d2d1d3-d6e9-48f1-aa31-e8212ef90312.png)
