### ISSUE TITLE
Deactivating UZF cells by stress period

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#876]
How do you deactivate UZF cells? There is no "status" flag like other advanced packages. 

The documentation states:
"To turn off all of the advanced stresses for a stress period, a PERIOD block must be specified with settings that deactivate
the UZF cells"

What are the "settings that deactivate the UZF cells"? If I set all the stresses to 0, will that turn off the UZF cell and stop GWSEEP? What if I still want GWSEEP without stress being applied? I think including a "status" input would be much clearer

**Comment by langevin-usgs** [comment]
UZF cells can be deactivated by specifying a period block with no entries.  The GWSEEP option is better represented with the drain package.
