### ISSUE TITLE
How does MVR determine package size?

### ISSUE THREAD

**Issue by wkitlasten** [MODFLOW-USGS/modflow6#889]
I am trying to set up a MVR package with 1 supplier ("drn") and 2 receivers ("sfr" and "ghb_coast"). This should be possible, right?. I am getting the following error, presumably from the first line of the MVR data: 

```
ERROR REPORT:

  1. RECEIVER ID < 1 OR GREATER THAN PACKAGE SIZE
  2.    RECEIVER ID = 1; PACKAGE SIZE = 0

```

MVR data:
```
# pname1 id1 pname2 id2 ptype value
drn 1 ghb_coast 1 factor 0.5
drn 1 ghb_coast 3 factor 0.5
drn 2 ghb_coast 2 factor 0.5
drn 2 ghb_coast 4 factor 0.5
drn 3 sfr 2409 factor 1.0
drn 4 sfr 2390 factor 1.0
drn 5 sfr 2399 factor 0.5
drn 5 sfr 2409 factor 0.5
drn 6 sfr 2399 factor 1.0
```
The .ghb package file associated with "ghb_coast" has a MAXBOUND of 1193, consistent with the length of the .ghb.dat input file. Similarly, the .drn package and .sfr package seem to have the correct "size" and are consistent with the data files. The MVR file has MAXMVR  of 135556 and MAXPACKAGES  3 and the "mvr__package" file contains "drn",  "ghb_coast", "sfr".

Where does the MVR package get the package size and why is it seeing a size of 0? Do I need a separate mvr.dat file for each exchange? (If so, I will have a flopy question!!)

I have attached some relevant files. Please let me know if I missed something.

Thanks
[si_vd_6_s4_2000.zip](https://github.com/MODFLOW-USGS/modflow6/files/8036719/si_vd_6_s4_2000.zip)

**Comment by wkitlasten** [comment]
Perhaps the mvr package does not support ghb?

**Comment by langevin-usgs** [comment]
GHB cannot be a receiver.  Only advanced packages can be a receiver.  Since GHB has a specified head, it doesn't make sense to add water to it.  Does that explain it?

**Comment by wkitlasten** [comment]
Yes, that clears it up. It makes more sense to just leave that DRN cell out of the MVR. Thanks.
