### ISSUE TITLE
Error in LAK SUMMARY OF FLOWS

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#893]
When I look at the summary of flows for the LAK package, it appears that if a non-zero INFLOW is encountered, it is filled for the remainder of the LAKs
![image](https://user-images.githubusercontent.com/25184697/154133989-a9dbbe67-d453-49df-849e-c2b247687873.png)

In this example, LAK 2 and LAK 3 are connected by an outlet, but none of the others are, so there should be no INFLOW for LAK >3.
Here is the OUTLET section of the .lak file:

BEGIN OUTLETS
#outletno lakein lakeout couttype invert width rough slope
        1     1     0 MANNING              4.138200e+02 7.620093e-01 5.000000e-02 1.000000e-05
        **2     2     3 MANNING              4.111990e+02 4.572056e+00 5.000000e-02 1.000000e-05**
        3     3     0 MANNING              4.114270e+02 7.620093e-01 5.000000e-02 1.000000e-05
        4     4     0 MANNING              4.129300e+02 1.371617e+00 5.000000e-02 1.000000e-05
        5     5     0 MANNING              4.112790e+02 4.114850e+00 5.000000e-02 1.000000e-05
        6     6     0 MANNING              4.112130e+02 7.620093e-01 5.000000e-02 1.000000e-05
        7     7     0 MANNING              4.086790e+02 2.310000e+01 5.000000e-02 1.000000e-05
        8     8     0 MANNING              4.091400e+02 7.620093e-01 5.000000e-02 1.000000e-05
END OUTLETS

If I look at LAK-1 BUDGET FOR ENTIRE MODEL AT END OF TIME STEP, there is 0% mass discrepancy:
![image](https://user-images.githubusercontent.com/25184697/154135119-c1658cd9-eba2-40eb-bde5-c969a8afcf31.png)

However, in the  LAK SUMMARY OF FLOWS section, there are very high percent discrepancies associated with LAK >3. If I subtract out the INFLOW, I get back to the ~0% mass error.

**Comment by langevin-usgs** [comment]
Thanks.  That looks like a bug it the output table.  What version of the code are you using?  And do you have a small example problem that you can zip and copy into this issue?

**Comment by RyanConway91** [comment]
I am using VERSION 6.3.0 release candidate 02/08/2022

This is from a "real world" model that is quite large and complex. I dont want it public at this time and I think its probably to large to email. If you want to try and coordinate another way of sharing, I'd be happy to send it.

**Comment by langevin-usgs** [comment]
[mf6.exe.zip](https://github.com/MODFLOW-USGS/modflow6/files/8074789/mf6.exe.zip)

Can you try this windows executable and see if it fixes it.  It's a long shot.  It it doesn't fix it, then it would be helpful to get your model somehow.  Maybe you can contact me through my usgs email address.

**Comment by RyanConway91** [comment]
That appears to have fixed it

![image](https://user-images.githubusercontent.com/25184697/154151396-a1c89d6c-7452-44dc-9b74-b4ab0fee2945.png)

**Comment by langevin-usgs** [comment]
Great, thanks.  Please leave this issue open.  I'll close it when I formally commit the fix.  Glad you pointed this out.
