### ISSUE TITLE
 Explicitly specify output times when using ATS

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#900]
In the documentation it is stated:

"A limitation with the present ATS implementation is that there is no way to explicitly specify times within
a stress period for saving output."

Are there plans to add this functionality? With the current setup, it seems like the only way to ensure you get simulation results near desired times in transient/multi time step models is to save everything. This is unworkable for large transient models.

**Comment by langevin-usgs** [comment]
We have no plans to add this in the near future, but we are aware of the limitation.  Observations are written every timestep, and so detailed information is available, but only for observations.

**Comment by langevin-usgs** [comment]
Closing.  Possible path forward described in #899.
