### ISSUE TITLE
Add "surface" variable to UZF period data

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#902]
It would be nice if the user could explicitly define a surface elevation for GWSEEP (preferably by period) similar to what it is done in EVT.

**Comment by emorway-usgs** [comment]
Will `SURFDEP` meet your needs?  It is specified in the `PACKAGEDATA` block, and as such doesn't vary by time step, but maybe you could offer an example of why it should vary in time?

**Comment by langevin-usgs** [comment]
We are trying to move away from GWSEEP and instead using the drain package, which can replicate the GWSEEP functionality using the drain conductance scaling.

**Comment by RyanConway91** [comment]
It didn't occur to me to use the DRN package instead. In theory this combined with MOVER would get me what I need. Thanks!

Motivation is as follows: SURFDEP is based on the top of the cell in which the UZF resides. Sometimes the the GW desired discharge surface may not be accurately represented in the layer geometry. Having a separate variable would mean the dis does not need to be updated just to change the discharge surface. Changing by period would allow for representation of changing geometry through time. For example, my current use of the package is the development of a tailings basin through time. Basically I want to keep basin that does not yet exist dry and route any ponded water to bottom of the basin.  But, I think all in all DRN gives me an easier solution.

**Comment by langevin-usgs** [comment]
I'm going to close this issue.  GWSEEP is essentially a drain calculation that is better served by using the drain package.  We added the drain conductance scaling option to reproduce what SURFDEP does so that DRN Package can do exactly what GWSEEP does in UZF.
