### ISSUE TITLE
examples: OSError: ..\data\ex-gwf-lak-p01\idomain-01.txt not found.

### ISSUE THREAD

**Issue by chenmingzhang** [MODFLOW-USGS/modflow6#912]
Hi:

  when running the [lake 1 notebook example ](https://github.com/MODFLOW-USGS/modflow6-examples/blob/master/notebooks/ex-gwf-lak-p01.ipynb), it returns a error 

```
OSError: ..\data\ex-gwf-lak-p01\idomain-01.txt not found.
```

  i checked the data folder and see there is no such file in the repo.

  would be great if this file can be uploaded. 

Thanks, Chenming

**Comment by langevin-usgs** [comment]
Sorry about that.  These notebooks are created automatically from the python scripts in the scripts folder, and some of them needed to be recreated because the script changed.  Can you try it again?
