### ISSUE TITLE
Write package cbb without writing main cbb

### ISSUE THREAD

**Issue by Smith0710** [MODFLOW-USGS/modflow6#926]
Hi. I have been trying to write package cbb files (e.g., maw and sfr) without writing the main cbb file but have not succeeded to date. Is this possible? It seems to be all cbbs or none. If I can remove writing to the main cbb it will reduce the model run time from around 5 mins to 4 mins, which will be helpful during calibration. More generally, the main cbb file is large and in my current application I don't need it, whereas I do need the maw and sfr budget files. Thank you.

**Comment by langevin-usgs** [comment]
In Output Control, you should save budget for the periods that you want; this will cause MAW and SFR to write output at the desired times.  In NPF and STO, make sure you do not have the SAVE_FLOWS option specified.  That should write the advanced package flows but not the NPF/STO flows.  Let us know if that doesn't work.

**Comment by Smith0710** [comment]
Thanks for this strategy. It took the following to get something working:

- Set SAVE BUDGET LAST for all stress periods in oc6
- Set SAVE_FLOWS option only for maw and sfr pacakages and with BUDGET FILEOUT options set to unique cbb filenames
- Removed SAVE_FLOWS option from all other packages (chd, drn, evt, ghb, npf, rch, sto)
- Also remove SAVE_FLOWS option from name file (didn't work without this)

This strategy resulted in a 2.3 MB _maw.cbb, 14.8 MB _sfr.cbb and 2.2 MB .cbb file (which is otherwise 1.1 GB). However, there is not much of a runtime saving and the number of changes required to made to the package files is a little on the fiddly side.

Thanks again for your help.
