### ISSUE TITLE
RCH Reduction

### ISSUE THREAD

**Issue by VermeulenPTM** [MODFLOW-USGS/modflow6#929]
Hi,

In the WEL package there is a feature **AUTO_FLOW_REDUCE** to reduce the well strength to unconfined conditions and therefore increase the ability to converge. I’ve noticed that the RCH needs something like that too. As RCH can be assigned to subsequent layers and the permeability does not increase but decrease, the model often does not convergence. As the reduction with the WEL packages reduces the strength, the correction of the RCH might increase or decrease the strength a bit as well to enforce convergence. 

Greetings,
Peter Vermeulen
Deltares - NLD

**Comment by langevin-usgs** [comment]
Hey @VermeulenPTM, the well reduction option works for extraction wells so they turn off or the extraction rate is reduced if the aquifer can't supply the water.  The recharge package is used primarily to add water to a cell, so I'm not sure we would want to add something similar.  Am I missing something?

**Comment by VermeulenPTM** [comment]
Hi Christian,

Thanks for your quick email.

In unconfined conditions the RCH can shift from one layer to another, I've noticed non-convergence because of oscillations as the RCH is moved from one layer to another especially whenever the permeability of the lower layer is significant less than the one on top of that layer. The RCH changes in that case from a linear- boundary to a severe non-linear boundary condition. The example below ran via the regular MF6 solver, I need to try it with Newton but it seems to me that a stable solution is only possible if the RCH is modified a bit (just as with the WEL-extraction). In the end we want to use/try the UZF, that might be more gentle to supply precipitation in complex geology. The concept of displacing RCH over great depth is invalid perhaps in geohydrological sense?

Greetings,

Peter

***@***.***

**Comment by VermeulenPTM** [comment]
Hi Christian,
Regarding this subject, would it be an idea to modify (or build-in an additional feature) to ensure that RCH is not only shifted vertically to the first active node, which makes sense of-course, but also to the first active node **with** a significant permeability (to be given in the OPTIONS sections of the RCH module perhaps). I've noticed in my 3D-model that RCH can be passed into very low permeable layers (previously known as aquitards) which makes conversion impossible (Newton and complex settings). Avoiding this by passing the RCH to underlying higher pemeable layers, might create a more robust solution.
Greetings,
Peter Vermeulen

**Comment by langevin-usgs** [comment]
Hey Peter, I'm not sure I understand the physical significance of having recharge bypass low permeability material.  But if this were something that you wanted to do, you could easily change which cell recharge is applied to by changing the layer number, if specifying recharge in a list, or the IRCH variable if using an array.  I don't think we'd want to add a specific option into the recharge package itself to reassign based on permeability.

I'm going to close this issue, because I don't think there is a bug in MODFLOW that we need to fix.  If you discover a general and robust method for improving convergence, please let us know.  We've found very good behavior with the Newton-Raphson approach.

**Comment by VermeulenPTM** [comment]
Hi Christian,
Okay you can close it as it is not a bug. In Modflow2005 the Rch package skips aquitards as well, so therefore Mf6 could skip those aquitards (represented by low permeable material, k<0.0001m/d) as well. Is the same concept. Indeed, rch below low permeable material is ackward, but the prior model might be wrong for several reasons and a converging model would be nice at that stage too. True, the Newton is very powerfull, nevertheless it fails to convert my model, if you want I can send you the mf6 model? In the meantime we will experiment to modify the layer assignment to achieve conversion.
Cheers,
Peter
________________________________
