### ISSUE TITLE
Troubles using segmented evapotranspiration in MF6

### ISSUE THREAD

**Issue by sebmeng** [MODFLOW-USGS/modflow6#930]
Hello, community!
I was re-building a former USG model to Modflow 6. I used GWV8 to do some testing. I had problems with the segmented evapotranspiration package in the MF6 model, having difficulty at several time steps in reaching the convergence criteria. In fact, I had to use the CONTINUE option in the NAM package to finish the simulation. To find out what the problem was, I built a simple 3-layer model, CH in the left and right borders, and two-segmented evapotranspiration zones, with 6 segments each. The layout of the model and the ET parameters are shown below:

![image](https://user-images.githubusercontent.com/48210348/163207450-bd888f14-b035-43bd-a0a3-b4cff6edc02e.png)
From this model, I’ve built four simulations: two with Modlfow USG, using the segmented evapotranspiration in one simulation (ETS package), and ET without segments in the other simulation. And two MF6 simulations with segmented ET in one simulation and another without segments.
In short, I had the same problem with this simple MF6 simulation with segments. It had problems reaching the convergence criteria in several time steps, so I had to use the CONTINUE option as well. The budget for the four simulations is shown below:

![image](https://user-images.githubusercontent.com/48210348/163205513-0fadcff9-838a-4e82-b6b0-35d342e59369.png)

First of all, I was expecting to find similar results between both models, M6 and ModUSG. It kind of happens between “no segments” models, although ET output is pretty much higher on ModUSG. 
On the other hand, when comparing “segmented” models, modUSG behaves as expected. but the output of m6 shows strange behaviour. Also, the ET output is not as reduced between m6 simulations as on modUSG.

I repeated the procedure, but instead of using 6-segment curves, I used 2-segment curves that resembled the originals. In this case, the results make much more sense, being similar between mod6 and modUSG, and ET balances are reduced between “no segments” and “segmented” as expected. Also, the MF6 simulation did not have any convergence problems:

![image](https://user-images.githubusercontent.com/48210348/163205795-d0892001-d03d-43af-afd8-1247f6cd43ff.png)
Is there any chance that MF6 has problems when using the segmented ET parameters for more than 2 segments? I checked the inputs myself and wrote to Jim Rumbaugh (just in case) and he verified that Vistas is writing all the inputs fine. I have attached the six simulation versions of USG and MF6 if you would like to check them out in this wetransfer link: https://we.tl/t-Go4kxWwFE3. 

Thank you in advance for your valuable help!
Regards

**Comment by langevin-usgs** [comment]
Hi @sebmeng, I'm guessing that something isn't set consistently between your mf6 and mfusg simulations.  For example, mf6 handles storage a bit differently than mfusg handles it.  For example, you may need to set the SS_CONFINED_ONLY option in the mf6 STO package in order for it to behave similarly to mfusg.  The NPF and LPF packages may have some differences as well.  I think if you look into specific behavior of NFP, LPF, and STO you should be able to get mfusg and mf6 results to show good agreement.

**Comment by langevin-usgs** [comment]
@sebmeng, any luck with this one?  I'm closing, but feel free to reopen if you determine there is an error in the MODFLOW 6 code.
