### ISSUE TITLE
feat: include missing external file names in error reports

### ISSUE THREAD

**Issue by aleaf** [MODFLOW-USGS/modflow6#931]
Hi, I am using Modflow 6 version 6.3, and noticed that when an external file is missing (i.e. that would be referenced with an open/close statement), the error report looks like the one below, with no reference to the missing file:
```
ERROR REPORT:

  1.        SPECIFIED FILE STATUS: OLD
  2.        SPECIFIED FILE FORMAT: FORMATTED
  3.        SPECIFIED FILE ACCESS: SEQUENTIAL
  4.        SPECIFIED FILE ACTION: READ
  5.          IOSTAT ERROR NUMBER: 29
  6.   -- STOP EXECUTION (openfile)
  ```
Including the name of the missing file would be a big help in troubleshooting these kinds of errors. Thanks for all of your work developing Modflow 6!

**Comment by langevin-usgs** [comment]
@aleaf, thanks for pointing this out.   We will get it fixed.

**Comment by jdhughes-usgs** [comment]
revised output will look like:

```
ERROR REPORT:

  1. Could not open "flow15.dis" on unit 1006. File already open on unit
     1005. Specified file status OLD. Specified file format FORMATTED.
     Specified file access SEQUENTIAL. Specified file action READ. IOSTAT
     error number -1. STOP EXECUTION in subroutine openfile().
```
