### ISSUE TITLE
Unable to use ATS

### ISSUE THREAD

**Issue by hjia1005** [MODFLOW-USGS/modflow6#944]
I am trying to use ats package in my model and followed the example. But keep getting errors. Below is my code. Using mf6.3.0 and flopy 3.3.6.

ats_filerecord=None
tdis = flopy.mf6.ModflowTdis(sim,pname='tdis', 
                             time_units='DAYS', 
                             nper=nper, 
                             perioddata=tdis_rc,
                             ats_filerecord=ats_filerecord)

dt0 = 30
dtmin = 1.00e-5
dtmax = 100.0
dtadj = 2.0
dtfailadj = 5.0

if True:
    ats_filerecord = sim_name + ".ats"
    atsperiod = [(0, dt0, dtmin, dtmax, dtadj, dtfailadj)]
    tdis.ats.initialize(
        maxats=len(atsperiod),
        perioddata=atsperiod,
        filename=ats_filerecord,
    )

Error message:
  Input In [274] in <cell line: 13>
    tdis.ats.initialize(

AttributeError: 'ModflowTdis' object has no attribute 'ats'

**Comment by hjia1005** [comment]
Found the problem.
ats_filerecord = sim_name + ".ats" 
"sim_name" should be "model_name"
 Closed.

**Comment by hjia1005** [comment]
Finally had to do this to get the ats package working.
ats=flopy.mf6.ModflowUtlats(gwf, perioddata=atsperiod, maxats=len(atsperiod))

The following from the auto-test is not working for me:
tdis.ats.initialize(maxats=len(atsperiod), perioddata=atsperiod, filename=ats_filerecord,)

Want to know why...

**Comment by langevin-usgs** [comment]
Might be related to this: https://github.com/modflowpy/flopy/pull/1394.  Closing as this is not a MODFLOW 6 issue.
