### ISSUE TITLE
In TVK, 'K22' & 'K33' may not be coded consistently

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/modflow6#989]
@damianmerrick  I was touring through existing MF6 code looking for 'how-to' examples for some of my work and noticed what I think may be an inconsistency in TVK?  In the code below, which is from `gwf3tvk8.f90`, I've highlighted two lines with red arrows.

I would've guessed that the second of the two highlighted lines would be more like the first.  That is, should the term being pointed to by the 2nd red arrow be "this%**k11**(n)" instead of "this%**k33**(n)"?:

![k33](https://user-images.githubusercontent.com/3236576/180058150-3122c5c2-409b-4a83-9991-f5106e979f3a.png)

It may well be that I've misunderstood what's going on here.  My apologies if so.

**Comment by jdhughes-usgs** [comment]
This is a bug. The [line in gwf3npf8.f90](https://github.com/MODFLOW-USGS/modflow6/blob/54b208bf2d7a5afb42596081c9e0e73fe2051b87/src/Model/GroundWaterFlow/gwf3npf8.f90#L1937) is `this%k33(n) = this%k33(n) * this%k11(n)`.

**Comment by damianmerrick** [comment]
@emorway-usgs You're right. Thanks for the pick-up. Will fix.
